### ISSUE TITLE
ksql-restore-command-topic class not found exception when trying to run command in docker image

### ISSUE THREAD

**Issue by stevenpyzhang** [confluentinc/ksql#6960] opened 2021-02-05 20:18 UTC
**Describe the bug**
We can't run this command from a docker image
```
# ./ksql-restore-command-topic -h
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: Could not find or load main class io.confluent.ksql.rest.server.restore.KsqlRestoreCommandTopic
Caused by: java.lang.ClassNotFoundException: io.confluent.ksql.rest.server.restore.KsqlRestoreCommandTopic
```

**To Reproduce**
Exec into a docker image of ksqlDB and try to run `./usr/bin/ksql-restore-command-topic -h`

**Expected behavior**
The help display appears

**Actual behaviour**
An exception is thrown

**Comment by spena** [comment] 2021-02-05 21:17
This is not an issue with the docker images created by ksql. I looked at Cloud, and the issue is our Cloud instances do not set the correct classpath to find the ksql jars. I'll close this as not an issue.

**Closed by spena** 2021-02-05 21:17 UTC
Labels: P0, bug
