### ISSUE TITLE
Remove KSQL_WINDOWED_SESSION_KEY_LEGACY_CONFIG

### ISSUE THREAD

**Issue by hjafarpour** [confluentinc/ksql#3179] opened 2019-08-06 20:47 UTC
Currently we have a config variable, `ksql.windowed.session.key.legacy` which forces session windows to be red as time windows if set true. The bug for the was fixed in 5.2. 
We should remove this in the next major release.

**Comment by agavra** [comment] 2019-11-20 20:44
Duplicate of #3622

**Closed** 2019-11-20 20:44 UTC
Labels: Code Quality
