### ISSUE TITLE
avro schema and tables - float to double conversion

### ISSUE THREAD

**Issue by tkopacki-nokia** [confluentinc/ksql#834] opened 2018-03-02 08:27 UTC
Hi,
I have a schema with couple attributes as float. when I create a stream from a topic that is using such schema it's working fine. 'describe stream' shows that float fields were casted to double.
When I try to create a table from such topic and select * from it ksql throws this error:

`
ksql> select * from instances;
Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=dummytopic12, partition=0, offset=715
Caused by: org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: Error serializing Avro message

Caused by: java.lang.Float cannot be cast to java.lang.Double
Query terminated
`

**Comment by apurvam** [comment] 2018-03-08 07:28
Could you share your entire context. What as the original `CREATE STREAM` which described the schema of the stream? What was the `CREATE TABLE AS` command that created a table out of that stream?

**Comment by tkopacki-nokia** [comment] 2018-03-12 07:32
Hi,
in my avro schema I have fields defined like this:

`{ "name": "xxx", "doc": "xxx", "type": "float" },`

to define stream I use this:
`create stream config with (kafka_topic='dummytopic', value_format='AVRO');`

at this point `describe config` shows that all floats were casted to double and I can select data from that stream. When I try to create a table from the same topic:
`create table instances(...) with (kafka_topic='dummytopic', key='uri', value_format='AVRO');`
I can't select anything because of that error I pasted above.

**Comment by rmoff** [comment] 2018-06-21 15:28
@tkopacki-nokia is it possible to share your full schema, and an anonymised message of data, so  that we can try to reproduce? Also have you tried it with the latest build (5.0.0-SNAPSHOT)?

**Comment by tkopacki** [comment] 2018-06-22 06:08
I'm afraid I don't have these data anymore since we moved on. We couldn't use KSQL at all because lack of nested objects support.

**Comment by rmoff** [comment] 2018-06-22 08:09
@tkopacki nested object support will be there in 5.0, which is just a few weeks away. Stay tuned! I'm closing this ticket for now, please do re-open it if you re-encounter this issue.

**Closed by rmoff** 2018-06-22 08:09 UTC
Labels: awaiting info
