### ISSUE TITLE
push queries - non-persistent can't be terminated via cli

### ISSUE THREAD

**Issue by mbonet** [confluentinc/ksql#7457] opened 2021-04-30 13:04 UTC
**Describe the bug**
Non-persistent Push Queries can't be terminated while executing the standard command (TERMINATE), those are the running queries:
![image](https://user-images.githubusercontent.com/907212/116698614-db212a00-a9c4-11eb-8515-c6e8eb7dc4a3.png)

Then we execute and it's not found
![image](https://user-images.githubusercontent.com/907212/116698720-fab85280-a9c4-11eb-8f76-fd601366f872.png)

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL: 0.15
2. Sample source data.
3. Any SQL statements you ran:
Any query that has been created via KSQL push query and needs to be terminated

**Expected behavior**
We would expect that the query is found and ends.

**Actual behaviour**
A clear and concise description of what actually happens, including:
![image](https://user-images.githubusercontent.com/907212/116698945-479c2900-a9c5-11eb-9e22-7845f16f0ed5.png)

**Additional context**

**Comment by vvcephei** [comment] 2021-04-30 16:02
Routing to the query engine team because this is a feature request regarding transient queries.

**Comment by agavra** [comment] 2021-04-30 16:35
this is a known duplicate of #5868 - closing it out here, but feel free to +1 the other issue!

**Closed by agavra** 2021-04-30 16:35 UTC
Labels: bug, needs-triage, query-engine
