### ISSUE TITLE
KSQL support stream/stream INNER JOIN with more than 1 joining condition

### ISSUE THREAD

**Issue by Debadyuti** [confluentinc/ksql#6037] opened 2020-08-17 18:59 UTC
**Describe the bug**
Currently, KSQL is not supporting stream/stream INNER JOIN with more than 1 joining condition. This is giving error message.

**To Reproduce**
SELECT *
FROM `testtopic1_stream1`
INNER JOIN `CODE_RELATIONS` 
WITHIN 7 DAYS
ON ((`testtopic1_stream1`.`messageInformation` -> `sender`) = (`CODE_RELATIONS`.`SOURCE_CODE1`)
AND (`testtopic1_stream1`.`claim` -> `lineOfBusinessCode`) = (`CODE_RELATIONS`.`CODE_VALUE1`))
EMIT CHANGES;

**Expected behavior**
KSQL should allow joining multiple conditions like regular SQL.

**Actual behaviour**
{"@type":"generic_error","error_code":50000,"message":"io.confluent.ksql.execution.expression.tree.LogicalBinaryExpression cannot be cast to io.confluent.ksql.execution.expression.tree.ComparisonExpression","stackTrace":["io.confluent.ksql.analyzer.Analyzer$Visitor.visitJoin(Analyzer.java:337)","io.confluent.ksql.analyzer.Analyzer$Visitor.visitJoin(Analyzer.java:159)","io.confluent.ksql.parser.tree.Join.accept(Join.java:97)","io.confluent.ksql.parser.tree.AstVisitor.process(AstVisitor.java:33)","io.confluent.ksql.analyzer.Analyzer$Visitor.visitQuery(Analyzer.java:288)","io.confluent.ksql.analyzer.Analyzer$Visitor.visitQuery(Analyzer.java:159)" .....

**Additional context**
Michael Drogalis suggested opening an issue in the Community Slack channel.

**Comment by mjsax** [comment] 2021-05-16 16:39
Closing as duplicate of #2344

**Closed by mjsax** 2021-05-16 16:39 UTC
Labels: enhancement, join-functions
