### ISSUE TITLE
Upgrading ksqldb-server docker image does not run with same configuration

### ISSUE THREAD

**Issue by grutts** [confluentinc/ksql#8519] opened 2021-12-15 12:41 UTC
**Describe the bug**
We are upgrading KsqlDB from 0.14.0 to 0.22.0, using the ksqldb-server docker image built by Confluent. 

KsqlDB does not start using the new version. Instead we see the following error. Note that we do not define any environment variables related to log4j - we're just using the default configuration.

```
2021-12-15 12:33:47log4j:ERROR Could not find value for key log4j.appender.clients
2021-12-15 12:33:47log4j:ERROR Could not instantiate appender named "clients".
2021-12-15 12:33:47log4j:ERROR Could not find value for key log4j.appender.connect
2021-12-15 12:33:47log4j:ERROR Could not instantiate appender named "connect".
2021-12-15 12:33:45OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2021-12-15 12:33:45===> Launching ksqlDB Server...
2021-12-15 12:33:43===> Configuring ksqlDB...
```

I would expect the current configuration to work with the new version, because the release notes do not mention any breaking changes related to this.

**Comment by agavra** [comment] 2021-12-17 19:36
may be related to #8540

**Comment by agavra** [comment] 2022-01-07 19:33
I'll close this as a duplicate of #8540. Please update there if you have more information.

**Closed by agavra** 2022-01-07 19:33 UTC
Labels: bug
