### ISSUE TITLE
Tombstone message cannot be inserted into the topic with Avro format 

### ISSUE THREAD

**Issue by vkorna** [confluentinc/ksql#9048] opened 2022-04-22 09:07 UTC
**Describe the bug**
I want to insert a tombstone message into the topic with Avro value format but it looks like, the message is serialized in the wrong way. Instead of null it sends null wrapped into an object into the topic. 

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL - 0.24.0.
2. Create a stream: `CREATE STREAM test_s (id string key, val STRUCT<value STRING>) WITH (kafka_topic='test_s', value_format='AVRO', partitions=1);`
3. Insert a tombstone into the stream: `INSERT INTO test_s (id, val) VALUES ('1', CAST(null as STRUCT<value STRING>));`
4. Check the messages in the topic: `PRINT test_s FROM BEGINNING;`

**Expected behavior**
Tombstone message (NULL) should be sent to the topic.

**Actual behaviour**
NULL is wrapped into an object is sent to the topic:
1. CLI output:
```
ksql> PRINT test_s FROM BEGINNING;
Key format: JSON or KAFKA_STRING
Value format: AVRO or KAFKA_STRING
rowtime: 2022/04/22 08:56:28.957 Z, key: 1, value: {"VAL": null}, partition: 0
```

**Comment by michalstutzmann** [comment] 2022-04-22 10:37
I think this is not possible. You can only insert tombstones if the `VALUE_FORMAT` is `KAFKA`.
More info: https://rmoff.net/2020/11/03/kafka-connect-ksqldb-and-kafka-tombstone-messages/

**Comment by vkorna** [comment] 2022-04-25 09:10
I've noticed that it works if set property `wrap_single_value = false`

```
CREATE STREAM test_avro_v2 (id string key, val STRUCT<v STRING, w STRING>) WITH (wrap_single_value = false, kafka_topic='test_avro_v2', value_format='AVRO', partitions=1);

insert into test_avro_v2 (id, val) values ('1', cast(null as STRUCT<v STRING, w STRING>));

# Result
ksql> print test_avro_v2 from beginning;
Key format: JSON or KAFKA_STRING
Value format: ¯\_(ツ)_/¯ - no data processed
rowtime: 2022/04/22 09:50:21.563 Z, key: 1, value: <null>, partition: 0

**Comment by agavra** [comment] 2022-04-28 16:40
Closing this as a duplicate of https://github.com/confluentinc/ksql/issues/7073 - any other workaround for introducing tombstones is not intentional ;)

**Closed by agavra** 2022-04-28 16:40 UTC
Labels: bug, needs-triage
