### ISSUE TITLE
Unhandled ksql exception causing a fatal error 

### ISSUE THREAD

**Issue by xavsan** [confluentinc/ksql#9628] opened 2022-10-05 20:48 UTC
**Describe the bug**
During a normal run of my ksql system, I came up on a fatal kafka error that went unhandled by ksql. This is the message from the log: ``` Transiting to fatal error state due to org.apache.kafka.common.KafkaException: Unexpected error in InitProducerIdResponse; The server experienced an unexpected error when processing the request. (org.apache.kafka.clients.producer.internals.TransactionManager:398) ```

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL is 0.28.2
2. Start a simple ksql system with 3 servers. Then create a stream and add some slightly latency.

**Expected behavior**
I expect ksql to be handle any and all kafka errors, and there should probably never be a fatal error occurring. 

**Actual behaviour**
Here are the logs leading up to the fatal error:

``` 
[  411086] [    76.670320] [service_zookeeper]                 [I] [2022-09-23 15:25:34,496] WARN Unexpected exception (org.apache.zookeeper.server.NIOServerCnxn)
[  411086] [    76.670320] [service_zookeeper]                 [I] EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /10.20.20.15:36990, session = 0x100000045930002
[  411086] [    76.670320] [service_zookeeper]                 [I] at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
[  411086] [    76.670320] [service_zookeeper]                 [I] at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
[  411086] [    76.670320] [service_zookeeper]                 [I] at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
[  411086] [    76.670320] [service_zookeeper]                 [I] at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
[  411086] [    76.670320] [service_zookeeper]                 [I] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[  411086] [    76.670320] [service_zookeeper]                 [I] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[  411086] [    76.670320] [service_zookeeper]                 [I] at java.base/java.lang.Thread.run(Thread.java:829)
[  411112] [    77.597532] [service_kafka]                     [I] [2022-09-23 15:25:35,424] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn)
[  411112] [    77.733590] [service_kafka]                     [I] [2022-09-23 15:25:35,560] INFO Socket connection established, initiating session, client: /10.20.20.15:37134, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn)
[  411125] [    77.866926] [service_kafka]                     [I] [2022-09-23 15:25:35,693] INFO Session establishment complete on server zookeeper/10.20.20.10:2181, session id = 0x100000045930002, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[  411125] [    77.992385] [service_kafka]                     [I] [2022-09-23 15:25:35,818] INFO [Transaction State Manager 1]: Finished loading 0 transaction metadata from __transaction_state-44 in 16326 milliseconds, of which 2468 milliseconds was spent in the scheduler. (kafka.coordinator.transaction.TransactionStateManager)
[  411125] [    77.992423] [service_kafka]                     [I] [2022-09-23 15:25:35,819] INFO [Transaction State Manager 1]: Completed loading transaction metadata from __transaction_state-44 for coordinator epoch 0 (kafka.coordinator.transaction.TransactionStateManager)
[  411164] [    80.254174] [service_kafka-2]                   [I] [2022-09-23 15:25:38,080] INFO [GroupCoordinator 2]: Member sr-1-ec96281a-bc28-4324-9719-32a55e60577f in group schema-registry has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[  411164] [    80.255097] [service_kafka-2]                   [I] [2022-09-23 15:25:38,081] INFO [GroupCoordinator 2]: Preparing to rebalance group schema-registry in state PreparingRebalance with old generation 1 (__consumer_offsets-29) (reason: removing member sr-1-ec96281a-bc28-4324-9719-32a55e60577f on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[  411164] [    80.255368] [service_kafka-2]                   [I] [2022-09-23 15:25:38,081] INFO [GroupCoordinator 2]: Group schema-registry with generation 2 is now empty (__consumer_offsets-29) (kafka.coordinator.group.GroupCoordinator)
[  411164] [    82.239113] [service_schema-registry]           [I] [2022-09-23 15:25:40,065] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Group coordinator kafka-2:9090 (id: 2147483645 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response.isDisconnected: false. Rediscovery will be attempted. (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411164] [    82.239263] [service_schema-registry]           [I] [2022-09-23 15:25:40,065] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Requesting disconnect from last known coordinator kafka-2:9090 (id: 2147483645 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411164] [    82.239465] [service_schema-registry]           [I] [2022-09-23 15:25:40,066] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Client requested disconnect from node 2147483645 (org.apache.kafka.clients.NetworkClient)
[  411164] [    82.240097] [service_schema-registry]           [I] [2022-09-23 15:25:40,066] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Cancelled in-flight HEARTBEAT request with correlation id 44 due to node 2147483645 being disconnected (elapsed time since creation: 9041ms, elapsed time since send: 9041ms, request timeout: 305000ms) (org.apache.kafka.clients.NetworkClient)
[  411164] [    82.240134] [service_schema-registry]           [I] [2022-09-23 15:25:40,066] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Cancelled in-flight HEARTBEAT request with correlation id 45 due to node 2147483645 being disconnected (elapsed time since creation: 6028ms, elapsed time since send: 6028ms, request timeout: 305000ms) (org.apache.kafka.clients.NetworkClient)
[  411164] [    82.240230] [service_schema-registry]           [I] [2022-09-23 15:25:40,066] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Cancelled in-flight HEARTBEAT request with correlation id 46 due to node 2147483645 being disconnected (elapsed time since creation: 3013ms, elapsed time since send: 3013ms, request timeout: 305000ms) (org.apache.kafka.clients.NetworkClient)
[  411164] [    82.356734] [service_schema-registry]           [I] [2022-09-23 15:25:40,183] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Discovered group coordinator kafka-2:9090 (id: 2147483645 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411164] [    82.360214] [service_schema-registry]           [I] [2022-09-23 15:25:40,186] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Discovered group coordinator kafka-2:9090 (id: 2147483645 rack: null) (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    82.906380] [service_schema-registry]           [I] [2022-09-23 15:25:40,732] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Attempt to heartbeat with Generation{generationId=1, memberId='sr-1-ec96281a-bc28-4324-9719-32a55e60577f', protocol='v0'} and group instance id Optional.empty failed due to UNKNOWN_MEMBER_ID, resetting generation (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    82.906474] [service_schema-registry]           [I] [2022-09-23 15:25:40,733] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Resetting generation and member id due to: encountered UNKNOWN_MEMBER_ID from HEARTBEAT response (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    82.906514] [service_schema-registry]           [I] [2022-09-23 15:25:40,733] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Request joining group due to: encountered UNKNOWN_MEMBER_ID from HEARTBEAT response (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    82.906560] [service_schema-registry]           [I] [2022-09-23 15:25:40,733] INFO Rebalance started (io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector)
[  411177] [    82.906605] [service_schema-registry]           [I] [2022-09-23 15:25:40,733] INFO [Schema registry clientId=sr-1, groupId=schema-registry] (Re-)joining group (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    82.953304] [service_kafka-2]                   [I] [2022-09-23 15:25:40,779] INFO [GroupCoordinator 2]: Dynamic member with unknown member id joins group schema-registry in Empty state. Created a new member id sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[  411177] [    83.009054] [service_schema-registry]           [I] [2022-09-23 15:25:40,835] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Request joining group due to: need to re-join with the given member-id: sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679 (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    83.009098] [service_schema-registry]           [I] [2022-09-23 15:25:40,835] INFO [Schema registry clientId=sr-1, groupId=schema-registry] (Re-)joining group (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411177] [    83.094173] [service_kafka-2]                   [I] [2022-09-23 15:25:40,920] INFO [GroupCoordinator 2]: Preparing to rebalance group schema-registry in state PreparingRebalance with old generation 2 (__consumer_offsets-29) (reason: Adding new member sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679 with group instance id None; client reason: rebalance failed due to 'The group member needs to have a valid member id before actually entering a consumer group.' (MemberIdRequiredException)) (kafka.coordinator.group.GroupCoordinator)
[  411243] [    85.255894] [service_kafka-2]                   [I] [2022-09-23 15:25:43,082] WARN [GroupCoordinator 2]: Failed to write empty metadata for group schema-registry: The group is rebalancing, so a rejoin is needed. (kafka.coordinator.group.GroupCoordinator)
[  411271] [    86.094874] [service_kafka-2]                   [I] [2022-09-23 15:25:43,921] INFO [GroupCoordinator 2]: Stabilized group schema-registry generation 3 (__consumer_offsets-29) with 1 members (kafka.coordinator.group.GroupCoordinator)
[  411271] [    86.131047] [service_schema-registry]           [I] [2022-09-23 15:25:43,957] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Successfully joined group with generation Generation{generationId=3, memberId='sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679', protocol='v0'} (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411271] [    86.207709] [service_kafka-2]                   [I] [2022-09-23 15:25:44,034] INFO [GroupCoordinator 2]: Assignment received from leader sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679 for group schema-registry for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[  411285] [    86.455374] [service_schema-registry]           [I] [2022-09-23 15:25:44,281] INFO [Schema registry clientId=sr-1, groupId=schema-registry] Successfully synced group in generation Generation{generationId=3, memberId='sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679', protocol='v0'} (io.confluent.kafka.schemaregistry.leaderelector.kafka.SchemaRegistryCoordinator)
[  411285] [    86.455432] [service_schema-registry]           [I] [2022-09-23 15:25:44,281] INFO Finished rebalance with leader election result: Assignment{version=1, error=0, leader='sr-1-cb7ad7e5-767f-42ac-9da8-4169d6121679', leaderIdentity=version=1,host=schema-registry,port=8081,scheme=http,leaderEligibility=true} (io.confluent.kafka.schemaregistry.leaderelector.kafka.KafkaGroupLeaderElector)
[  411299] [    87.523679] [service_schema-registry]           [I] [2022-09-23 15:25:45,350] INFO Wait to catch up until the offset at 2 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[  411299] [    87.589890] [service_schema-registry]           [I] [2022-09-23 15:25:45,416] INFO Reached offset at 2 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
[  411411] [    91.674313] [service_primary-ksqldb-server]     [I] [2022-09-23 15:25:49,500] INFO reporting node-level saturation 0.0 (io.confluent.ksql.utilization.PersistentQuerySaturationMetrics:158)
[  411411] [    91.675285] [service_additional-ksqldb-server]  [I] [2022-09-23 15:25:49,501] INFO reporting node-level saturation 0.0 (io.confluent.ksql.utilization.PersistentQuerySaturationMetrics:158)
[  411439] [    92.366331] [service_additional-ksqldb-server2] [I] [2022-09-23 15:25:50,192] INFO reporting node-level saturation 0.0 (io.confluent.ksql.utilization.PersistentQuerySaturationMetrics:158)
[  411439] [    94.901184] [service_kafka-2]                   [I] [2022-09-23 15:25:52,727] WARN Client session timed out, have not heard from server in 12000ms for session id 0x100000045930004 (org.apache.zookeeper.ClientCnxn)
[  411439] [    94.901689] [service_kafka-2]                   [I] [2022-09-23 15:25:52,727] WARN Session 0x100000045930004 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
[  411439] [    94.901689] [service_kafka-2]                   [I] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 12000ms for session id 0x100000045930004
[  411439] [    94.901689] [service_kafka-2]                   [I] at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[  411454] [    96.084995] [service_kafka]                     [I] [2022-09-23 15:25:53,911] WARN Client session timed out, have not heard from server in 12025ms for session id 0x100000045930002 (org.apache.zookeeper.ClientCnxn)
[  411454] [    96.085040] [service_kafka]                     [I] [2022-09-23 15:25:53,911] WARN Session 0x100000045930002 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
[  411454] [    96.085040] [service_kafka]                     [I] org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 12025ms for session id 0x100000045930002
[  411454] [    96.085040] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[  411454] [    96.105073] [service_kafka-2]                   [I] [2022-09-23 15:25:53,931] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn)
[  411454] [    96.185239] [service_kafka]                     [I] [2022-09-23 15:25:54,011] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[  411454] [    96.185332] [service_kafka]                     [I] [2022-09-23 15:25:54,011] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[  411469] [    97.449360] [service_kafka]                     [I] [2022-09-23 15:25:55,275] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn)
[  411514] [   103.441572] [service_kafka-2]                   [I] [2022-09-23 15:26:01,268] INFO Socket connection established, initiating session, client: /10.20.20.40:59596, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn)
[  411514] [   103.633611] [service_kafka-2]                   [I] [2022-09-23 15:26:01,460] INFO Session establishment complete on server zookeeper/10.20.20.10:2181, session id = 0x100000045930004, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.229506] [service_zookeeper]                 [I] [2022-09-23 15:26:02,056] INFO Expiring session 0x100000045930002, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[  411514] [   104.681589] [service_kafka]                     [I] [2022-09-23 15:26:02,508] INFO Socket connection established, initiating session, client: /10.20.20.15:37142, server: zookeeper/10.20.20.10:2181 (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.713317] [service_zookeeper]                 [I] [2022-09-23 15:26:02,539] INFO Invalid session 0x100000045930002 for client /10.20.20.15:37142, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[  411514] [   104.777692] [service_kafka]                     [I] [2022-09-23 15:26:02,604] WARN Unable to reconnect to ZooKeeper service, session 0x100000045930002 has expired (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.777836] [service_kafka]                     [I] [2022-09-23 15:26:02,604] WARN Session 0x100000045930002 for sever zookeeper/10.20.20.10:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.777836] [service_kafka]                     [I] org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x100000045930002 has expired
[  411514] [   104.777836] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
[  411514] [   104.777836] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
[  411514] [   104.777836] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
[  411514] [   104.777836] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
[  411514] [   104.777836] [service_kafka]                     [I] at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[  411514] [   104.778145] [service_kafka]                     [I] [2022-09-23 15:26:02,604] INFO EventThread shut down for session: 0x100000045930002 (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.778441] [service_kafka]                     [I] [2022-09-23 15:26:02,605] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[  411514] [   104.879490] [service_kafka]                     [I] [2022-09-23 15:26:02,706] DEBUG [Controller id=1] Resigning (kafka.controller.KafkaController)
[  411514] [   104.880101] [service_kafka]                     [I] [2022-09-23 15:26:02,706] DEBUG [Controller id=1] Unregister BrokerModifications handler for Set(1, 2, 3) (kafka.controller.KafkaController)
[  411514] [   104.880224] [service_kafka]                     [I] [2022-09-23 15:26:02,706] INFO [ZooKeeperClient Kafka server] Initializing a new session to zookeeper:2181. (kafka.zookeeper.ZooKeeperClient)
[  411514] [   104.880268] [service_kafka]                     [I] [2022-09-23 15:26:02,706] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@70ab2d48 (org.apache.zookeeper.ZooKeeper)
[  411514] [   104.880300] [service_kafka]                     [I] [2022-09-23 15:26:02,706] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[  411514] [   104.880357] [service_kafka]                     [I] [2022-09-23 15:26:02,706] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.880719] [service_kafka]                     [I] [2022-09-23 15:26:02,707] INFO [PartitionStateMachine controllerId=1] Stopped partition state machine (kafka.controller.ZkPartitionStateMachine)
[  411514] [   104.882084] [service_kafka]                     [I] [2022-09-23 15:26:02,708] INFO [ReplicaStateMachine controllerId=1] Stopped replica state machine (kafka.controller.ZkReplicaStateMachine)
[  411514] [   104.882312] [service_kafka]                     [I] [2022-09-23 15:26:02,708] INFO [RequestSendThread controllerId=1] Shutting down (kafka.controller.RequestSendThread)
[  411514] [   104.882447] [service_kafka]                     [I] [2022-09-23 15:26:02,709] INFO [RequestSendThread controllerId=1] Stopped (kafka.controller.RequestSendThread)
[  411514] [   104.882600] [service_kafka]                     [I] [2022-09-23 15:26:02,709] INFO [RequestSendThread controllerId=1] Shutdown completed (kafka.controller.RequestSendThread)
[  411514] [   104.883207] [service_kafka]                     [I] [2022-09-23 15:26:02,706] WARN [RPC ProducerId Manager 1]: Had an unknown error from the controller, giving up. (kafka.coordinator.transaction.RPCProducerIdManager)
[  411514] [   104.883559] [service_kafka]                     [I] [2022-09-23 15:26:02,710] ERROR [KafkaApi-1] Unexpected error handling request RequestHeader(apiKey=INIT_PRODUCER_ID, apiVersion=4, clientId=producer-default_, correlationId=24) -- InitProducerIdRequestData(transactionalId='default_', transactionTimeoutMs=60000, producerId=-1, producerEpoch=-1) with context RequestContext(header=RequestHeader(apiKey=INIT_PRODUCER_ID, apiVersion=4, clientId=producer-default_, correlationId=24), connectionId='10.20.20.15:9092-10.20.20.25:43190-12', clientAddress=/10.20.20.25, principal=User:ANONYMOUS, listenerName=ListenerName(INTERNAL), securityProtocol=PLAINTEXT, clientInformation=ClientInformation(softwareName=apache-kafka-java, softwareVersion=7.3.0-cc-docker-ksql.111-33-ccs), fromPrivilegedListener=true, principalSerde=Optional[org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder@f54ba62]) (kafka.server.KafkaApis)
[  411514] [   104.883559] [service_kafka]                     [I] org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.
[  411514] [   104.886228] [service_kafka]                     [I] [2022-09-23 15:26:02,712] INFO Opening socket connection to server zookeeper/10.20.20.10:2181. (org.apache.zookeeper.ClientCnxn)
[  411514] [   104.888108] [service_kafka]                     [I] [2022-09-23 15:26:02,714] INFO [RequestSendThread controllerId=1] Shutting down (kafka.controller.RequestSendThread)
[  411514] [   104.888194] [service_kafka]                     [I] [2022-09-23 15:26:02,714] INFO [RequestSendThread controllerId=1] Stopped (kafka.controller.RequestSendThread)
[  411514] [   104.888246] [service_kafka]                     [I] [2022-09-23 15:26:02,714] INFO [RequestSendThread controllerId=1] Shutdown completed (kafka.controller.RequestSendThread)
[  411514] [   104.890336] [service_kafka]                     [I] [2022-09-23 15:26:02,716] INFO [RequestSendThread controllerId=1] Shutting down (kafka.controller.RequestSendThread)
[  411514] [   104.890669] [service_kafka]                     [I] [2022-09-23 15:26:02,717] INFO [RequestSendThread controllerId=1] Stopped (kafka.controller.RequestSendThread)
[  411514] [   104.890719] [service_kafka]                     [I] [2022-09-23 15:26:02,717] INFO [RequestSendThread controllerId=1] Shutdown completed (kafka.controller.RequestSendThread)
[  411514] [   104.892912] [service_kafka]                     [I] [2022-09-23 15:26:02,719] INFO [Controller id=1] Resigned (kafka.controller.KafkaController)
[  411514] [   104.893106] [service_kafka]                     [I] [2022-09-23 15:26:02,719] INFO Creating /brokers/ids/1 (is it secure? false) (kafka.zk.KafkaZkClient)
[  411514] [   104.979065] [service_primary-ksqldb-server]     [I] [2022-09-23 15:26:02,805] INFO [Producer clientId=producer-default_, transactionalId=default_] Transiting to fatal error state due to org.apache.kafka.common.KafkaException: Unexpected error in InitProducerIdResponse; The server experienced an unexpected error when processing the request. (org.apache.kafka.clients.producer.internals.TransactionManager:398)
[  411514] [   104.980197] [service_primary-ksqldb-server]     [I] [2022-09-23 15:26:02,805] INFO Processed unsuccessfully: KsqlRequest{ksql='CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE) WITH (kafka_topic='locations', value_format='json', partitions=3);', configOverrides={}, requestProperties={}, sessionVariables={}, commandSequenceNumber=Optional.empty}, reason:  (io.confluent.ksql.rest.server.resources.KsqlResource:347)
[  411514] [   104.980197] [service_primary-ksqldb-server]     [I] io.confluent.ksql.util.KsqlServerException: Could not write the statement 'CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE) WITH (kafka_topic='locations', value_format='json', partitions=3);' into the command topic: Unexpected error in InitProducerIdResponse; The server experienced an unexpected error when processing the request.
[  411514] [   104.980197] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.computation.DistributingExecutor.execute(DistributingExecutor.java:204)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.execution.RequestHandler.lambda$executeStatement$0(RequestHandler.java:123)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.execution.RequestHandler.executeStatement(RequestHandler.java:127)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.execution.RequestHandler.execute(RequestHandler.java:93)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.resources.KsqlResource.handleKsqlStatements(KsqlResource.java:320)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeKsqlRequest$2(KsqlServerEndpoints.java:183)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOldApiEndpointOnWorker$23(KsqlServerEndpoints.java:341)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.confluent.ksql.rest.server.KsqlServerEndpoints.lambda$executeOnWorker$22(KsqlServerEndpoints.java:327)
[  411514] [   104.980198] [service_primary-ksqldb-server]     [I] at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at java.base/java.lang.Thread.run(Thread.java:829)


[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] Caused by: org.apache.kafka.common.KafkaException: Unexpected error in InitProducerIdResponse; The server experienced an unexpected error when processing the request.
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.producer.internals.TransactionManager$InitProducerIdHandler.handleResponse(TransactionManager.java:1303)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:1207)
[  411514] [   104.980199] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:583)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:575)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:426)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
[  411514] [   104.980200] [service_primary-ksqldb-server]     [I] ... 1 more

```

**Comment by suhas-satish** [comment] 2022-10-19 18:12
@cprasad1 , any update on this ?

**Comment by cprasad1** [comment] 2022-10-20 23:51
@suhas-satish the root cause: There is an exception/error happening in ksql, which brings streams into an error state. The fix is that in ksql, streams should not enter that state so that ksql can try to recover from the exception. The kafka-streams state error is a terminal state that should only be reached due to the handler returning a code that puts streams in that state. Ksql’s handler should never return that code so the application should not ever reach error state. [This commit](https://github.com/apache/kafka/commit/188b2bf2802c2bc5900a286a9ef023daaeb08c21) is the revert of the problematic commit. Unfortunately, [that commit is not in the version of Kafka streams in ksql 0.28.2](https://github.com/confluentinc/ksql/blob/5fbc6e8a4409c3a6742ba9e7007cd51d309eb07c/pom.xml#L32). This will be fixed in 0.29 as the revert of the problematic commit will be picked up by then.

**Comment by cprasad1** [comment] 2022-10-21 00:12
including https://github.com/apache/kafka/commit/188b2bf2802c2bc5900a286a9ef023daaeb08c21 in 0.28 will hotfix it

**Comment by suhas-satish** [comment] 2022-10-25 01:12
cc: @vpapavas just to double check we are including the missing commit in ksql 0.29 release.

**Closed** 2022-11-15 17:30 UTC
Labels: bug, P0, streaming-engine
