### ISSUE TITLE
Codefy CLI / Server compatibility

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#4020] opened 2019-12-02 23:09 UTC
We should check CLI / Server compatibility when connecting.  If an old CLI connects to a newer server that has incompatible changes, or vice-versa, then we should abort the connect and display an error message to upgrade / downgrade as appropriate.

**Comment by vcrfxia** [comment] 2020-12-16 21:31
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/3860

**Closed by vcrfxia** 2020-12-16 21:31 UTC
Labels: enhancement, user-experience
