### ISSUE TITLE
`ksql> Failed to prepare statement: EN_WIKIPEDIA_GT_1_STREAM does not exist.`

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksql#3363] opened 2019-09-17 00:48 UTC
Two users have reported an error running `cp-demo` at https://github.com/confluentinc/cp-demo (most users do not report this issue, so it's an interesting/intermittent timing issue).

```
Run KSQL queries (~10 seconds):
Aug 30, 2019 1:59:13 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
KSQL, Copyright 2017-2018 Confluent Inc.

CLI v5.3.0, Server v5.3.0 located at http://ksql-server:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> Failed to prepare statement: EN_WIKIPEDIA_GT_1_STREAM does not exist.
ksql> Exiting KSQL.
```

Per the users who have reported this issue:

1. There are no errors beyond the one shown above
2. If user re-executes the command manually (the 3rd), it passes

Note that I personally cannot reproduce this issue.  I've seen reports only from other users including @remiforest and @daniellavoie

**Comment by ybyzek** [comment] 2019-11-20 12:51
I’m now hitting this issue occasionally as well, could someone please help look into this?

**Comment by rspurgeon** [comment] 2019-11-20 15:35
@ybyzek i'm investigating this

**Comment by rspurgeon** [comment] 2019-11-20 16:27
I was able to reproduce this issue using Control Center and KSQL independent of the `cp-demo` automation.  I modified `cp-demo` to stop short of the ksql script execution, and then attempted to run the series of KSQL commands in Control Center.

The script looks like this:
```
CREATE STREAM wikipedia (CREATEDAT bigint, WIKIPAGE string, CHANNEL string, USERNAME string, COMMITMESSAGE string, BYTECHANGE integer, DIFFURL string, ISNEW boolean, ISMINOR boolean, ISBOT boolean, ISUNPATROLLED boolean) WITH (kafka_topic='wikipedia.parsed', value_format='AVRO');
CREATE STREAM wikipedianobot WITH (PARTITIONS=2,REPLICAS=2) AS SELECT * FROM wikipedia WHERE isbot <> true;
CREATE STREAM wikipediabot WITH (PARTITIONS=2,REPLICAS=2) AS SELECT * FROM wikipedia WHERE isbot = true;
CREATE TABLE en_wikipedia_gt_1 WITH (PARTITIONS=2,REPLICAS=2) AS SELECT username, wikipage, count(*) AS COUNT FROM wikipedia WINDOW TUMBLING (size 300 second) WHERE channel = '#en.wikipedia' GROUP BY username, wikipage HAVING count(*) > 1; 
CREATE STREAM en_wikipedia_gt_1_stream (USERNAME string, WIKIPAGE string, COUNT bigint) WITH (kafka_topic='EN_WIKIPEDIA_GT_1', value_format='AVRO');
CREATE STREAM en_wikipedia_gt_1_counts WITH (PARTITIONS=2,REPLICAS=2) AS SELECT * FROM en_wikipedia_gt_1_stream where ROWTIME is not null;
```

The final `CREATE STREAM` is the one that fails, and is the only `CREATE` derived from a previously create stream in the script itself.

After a short period, I copied the final line out and ran it independent of the rest of the script and the final `CREATE STREAM` succeeded.

**Comment by ybyzek** [comment] 2019-11-20 17:17
@big-andy-coates update: this KSQL issue is now a blocker to merging https://github.com/confluentinc/cp-demo/pull/133 into cp-demo.

**Comment by rspurgeon** [comment] 2019-11-20 17:35
I was able to circumvent this issue in `cp-demo` by adding a 'dummy command' to the KSQL script prior to the create stream from the previously created stream, as:

```
...
CREATE STREAM en_wikipedia_gt_1_stream (USERNAME string, WIKIPAGE string, COUNT bigint) WITH (kafka_topic='EN_WIKIPEDIA_GT_1', value_format='AVRO');
DROP STREAM IF EXISTS FOO;
CREATE STREAM en_wikipedia_gt_1_counts WITH (PARTITIONS=2,REPLICAS=2) AS SELECT * FROM en_wikipedia_gt_1_stream where ROWTIME is not null;
```

`DROP STREAM IF EXISTS FOO;` existing just to delay the final CREATE...

**Comment by ybyzek** [comment] 2019-11-21 14:21
From @big-andy-coates 

```
I've debugged the Ksql server when running multiple statements in C3 and it sends all the statements across in a single request.  This is the correct behaviour for C3 as then it doesn't need to worry about sequence numbers etc, leaving the KSQL server to ensure previous commands have been executed for processing the next.
The same multi-line requests can be achieved in the CLI by putting them all on the one line, or by using the cli's RUN SCRIPT functionality, where the CLI will load the content of the script and pass the lot over to the server in a single request.
So, it sounds like there is a bug in the way KSQL is handling multi-statement requests.
```

**Comment by apurvam** [comment] 2019-11-21 21:49
Assigning to @big-andy-coates since he has been looking at this.

**Comment by big-andy-coates** [comment] 2019-11-22 11:35
Issue exists in 5.4.x branch.  Confirmed its also in 5.3.x. However, it's fixed in master.

The issue related to how the KSQL server is processing multi-statement requests. There is a bug that means that a subsequent command may be 'prepared' before the previous command has been executed on the command runner thread.

Master has changes that mean the `prepare` call doesn't validate that sources exist, (which is correct behavior).  In 5.4.x and before the `prepare` call checks the metastore for any referenced sources and throws an exception if they are not known.

**Closed** 2019-11-23 07:23 UTC
Labels: bug
