### ISSUE TITLE
KSQL server is eating memory upto the total physical allocated

### ISSUE THREAD

**Issue by AgoloKarimTawfik** [confluentinc/ksql#3968] opened 2019-11-24 20:51 UTC
I am using ksql on k8s using helm-chart, using the below image tag
```
image: confluentinc/cp-ksql-server
imageTag: 5.3.1
```
with the below resources configs
```
    resources:
      limits:
        cpu: 6
        memory: 22Gi
      requests:
        cpu: 6
        memory: 22Gi
    heapOptions: "-Xms18g -Xmx18g"
```
After getting the server up, I started to create streams (400) with the below query.

```
create stream filtered_ksql ( article struct< _id VARCHAR, title VARCHAR, text VARCHAR, action VARCHAR, url VARCHAR, feed_id VARCHAR, mode VARCHAR, score VARCHAR, published_at VARCHAR, retrieved_at VARCHAR, original_id VARCHAR, sources ARRAY< STRUCT< _id VARCHAR, name VARCHAR, url VARCHAR, format VARCHAR, publisher VARCHAR>>> ) with  (KAFKA_TOPIC='realtime-filtered-documents', partitions=1, value_format='JSON');

CREATE STREAM KSQL_PROCESSED_ARTICLES WITH 
(REPLICAS = 1, PARTITIONS = 1, KAFKA_TOPIC = 'KSQL_PROCESSED_ARTICLES') 
AS SELECT
  TEXT_PROCESSOR(FILTERED_KSQL.ARTICLE) "ARTICLE"
FROM FILTERED_KSQL FILTERED_KSQL
```

the UDF (`TEXT_PROCESSOR`) is a scalar udf function that takes article, calls API service and return the processed version of it with few extra fields (no caching happening on the UDF), the input article size is ~4KB and the output version is around ~7KB.

after the 400 streams got created, I started to see the memory on grafana to be just increasing without any kind of freeing it up as below [.](url)
![Screen Shot 2019-11-24 at 10 57 35 PM](https://user-images.githubusercontent.com/28862935/69501486-1dac2080-0f0e-11ea-88ba-f8c8f926fe59.png)

I checked [this from the docs for the ksql to tune the memory buffer](https://docs.confluent.io/current/ksql/docs/installation/server-config/config-reference.html#ksql-streams-cache-max-bytes-buffering) and [this from the Streams config](https://docs.confluent.io/current/streams/developer-guide/config-streams.html#optional-configuration-parameters), and come up with updating the `ksql.streams.buffered.records.per.partition` to be 10 instead of 1000, however I can't see any impact on the memory usage.

Not sure if this is memory leak issue or there is something I need to tune in my KSQL server props.
It is unclear to me why is KSQL using such memory given that there is no aggs or joins at all, all the queries are just a transformations.

EDIT:

1- Is it RocksDB the reason, do I need to configure it better (e.g. the block size, and use sort of bounded memory config like the one mentioned [here](https://docs.confluent.io/current/streams/developer-guide/memory-mgmt.html#rocksdb))?
2- Shall I consider compressing the message, will that help?
3- I deleted all the 400 queries and streams, and the memory still maxed out.

**Comment by big-andy-coates** [comment] 2020-01-10 11:16
Hey @AgoloKarimTawfik, after our chats on the community slack, I hope you don't mind me closing this as a duplicate of https://github.com/confluentinc/ksql/issues/4168?

**Closed by big-andy-coates** 2020-01-10 11:16 UTC

**Comment by AgoloKarimTawfik** [comment] 2020-01-10 13:31
@big-andy-coates thanks for the clarification

**Comment by vinitpatni** [comment] 2022-04-02 13:37
> Hey @AgoloKarimTawfik, after our chats on the community slack, I hope you don't mind me closing this as a duplicate of #4168?

@big-andy-coates Is the KSQL Cluster inability to better consume resources as mentioned in the #4168 causing this memory issues?
