### ISSUE TITLE
Support expressions in 'GROUP BY'

### ISSUE THREAD

**Issue by Jianyi-Ren** [confluentinc/ksql#1679] opened 2018-08-01 19:15 UTC
I have an incoming JSON stream 'MAIN_EVENT_STREAM' 
```
ksql> describe main_event_stream;
 ROWTIME  | BIGINT           (system)
 ROWKEY   | VARCHAR(STRING)  (system)
 FOO      | MAP[VARCHAR(STRING),VARCHAR(STRING)]
```

with the object foo looks like
```
{"foo": {
    "bar": {
           "propertyName1":"val1",
           "propertyName2":"val2",
           "propertyName3":"valX",
            ......
     }
}
```
I would like to create an aggregation using:

```
CREATE STREAM mystream \
	WITH (PARTITIONS=5, VALUE_FORMAT='JSON') AS \
	SELECT 1 AS FOO, * FROM MAIN_EVENT_STREAM \
	WHERE EXTRACTJSONFIELD(foo['bar'], '$.propertyName1')='val1' \
      AND EXTRACTJSONFIELD(foo['bar'], '$.propertyName2')='val2';
```

```
CREATE TABLE sample_aggregation \
	WITH (PARTITIONS=5, VALUE_FORMAT='JSON', TIMESTAMP=EXTRACTJSONFIELD(metadata['collectorTimestamp'], '$')) AS \
	SELECT FOO, COUNT(*) \
    FROM mystream \
    WINDOW HOPPING (SIZE 1440 MINUTE, ADVANCE BY 86400 SECONDS) \
    GROUP BY EXTRACTJSONFIELD(foo['bar'], '$.propertyName3');
```

And I got the error
```Couldn't find field with name=EXTRACTJSONFIELD(mystream.foo['bar'], '$.propertyName3') in schema. fields=[org.apache.kafka.connect.data.Field@de45aea7, org.apache.kafka.connect.data.Field@90b957e7]```

Does it mean EXTRACTJSONFIELD can only be used in SELECT but not after GROUP BY?

many thanks,
Jianyi

**Comment by apurvam** [comment] 2018-08-02 00:26
It looks like the data has a nested field `bar`, which is a `Map<String, String>`. You probably need to declare `main_event_stream` as `CREATE STREAM main_even_stream (foo STRUCT<bar, MAP<varchar, varchar>>) WITH (..)`.

Then instead of `EXTRACTJSONFIELD`, you can reference the fields like `foo->bar['propertyName1']`

This should work in KSQL 5.0.0.

**Comment by rodesai** [comment] 2018-08-02 17:30
This still won't work. In 5.0 you still cannot dereference a struct field inside a GROUP BY. To do this you need to extract the field into another stream first:

```
CREATE STREAM mystream \
	WITH (PARTITIONS=5, VALUE_FORMAT='JSON') AS \
	SELECT 1 AS FOO, FOO->BAR['propertyName1'] AS BAR, * FROM MAIN_EVENT_STREAM \
	WHERE EXTRACTJSONFIELD(foo['bar'], '$.propertyName1')='val1' \
      AND EXTRACTJSONFIELD(foo['bar'], '$.propertyName2')='val2';
CREATE TABLE sample_aggregation \
	WITH (PARTITIONS=5, VALUE_FORMAT='JSON', TIMESTAMP=EXTRACTJSONFIELD(metadata['collectorTimestamp'], '$')) AS \
	SELECT bar, COUNT(*) \
    FROM mystream \
    WINDOW HOPPING (SIZE 1440 MINUTE, ADVANCE BY 86400 SECONDS) \
    GROUP BY bar;
```

**Comment by rodesai** [comment] 2018-08-02 17:39
Let's use this bug to track being able to use expressions in GROUP BY

**Comment by Jianyi-Ren** [comment] 2018-08-02 18:10
> You also cannot use an expression as the value for the TIMESTAMP property. 

Thanks for pointing that out. That's also ture. I noticed later that  if we want to use a data property as the timestamp instead of the build-in keyword viewtime, we need to extract the timestamp string and create an extra column in the stream.

That being said, it would be nice to Support expressions in 'WITH', especially after the timestamp keyword, so that the user can use a timestamp info within their data directly.

**Comment by big-andy-coates** [comment] 2018-10-22 14:17
Looks to be a duplicate of #1849.

**Closed** 2018-10-30 01:32 UTC
Labels: enhancement, user-experience
