### ISSUE TITLE
ALTER TABLE statement

### ISSUE THREAD

**Issue by rcillo** [confluentinc/ksql#1725] opened 2018-08-10 09:47 UTC
One of the biggest barrier for adoption of KSQL at my organization is the inability to alter a table's schema when using JSON as a format.

We have internally implemented similar rules as those from AVRO in order to guarantee that the model evolves in a compatible way (namely, forward compatible way) and we believe that those changes should be reflected in the KSQL tables.

I would like to know what the maintainers of KSQL and the community think about introducing a ALTER TABLE, or ALTER STREAM statement that would allow changing the schema (the list of field types that follow a CREATE statement) in a non retroactive way, e.g. only messages processed after the ALTER statement contain the new fields added.

**Comment by himanshugahlaut** [comment] 2018-08-10 09:53
This is a request to Confluent KSQL team. Could we have a meeting between Zalando team and Confluent KSQL team to discuss the various bottlenecks which we are facing in adopting KSQL? We would be more than happy to contribute back into KSQL as well if we can work together to match our internal timelines. I would be glad to schedule a meeting.

**Comment by bithavoc** [comment] 2019-01-29 00:13
What's the walkaround at the moment, Drop and Re-create?

**Comment by PrernaSethia** [comment] 2019-09-25 11:02
@miguno Any update on this ?

**Comment by big-andy-coates** [comment] 2020-08-12 17:59
Closing as duplicate of https://github.com/confluentinc/ksql/issues/2440

**Closed by big-andy-coates** 2020-08-12 17:59 UTC
Labels: enhancement
