### ISSUE TITLE
Adding field to stream table join breaks compatibility

### ISSUE THREAD

**Issue by jhovell** [confluentinc/ksql#8273] opened 2021-10-20 20:48 UTC
**Describe the bug**
Seems this is at least known about as a functional test specifically verifies this unsupported behavior:

https://github.com/confluentinc/ksql/blob/v6.2.2-45/ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql#L135

This is a significant issue as it means there is basically no way to evolve a schema as pretty much any change will break compatibility in schema registry.

Note we were not even aware of the `CREATE OR REPLACE` syntax and ran into this issue simply updating our schema with the added field. Normally a new added field would not cause issues, however the schema registry subject based on the internal `Join-repartition` topic created internally by KSQL as part of the join cannot be registered to schema registry. Inspecting the subject, KSQL has added metadata columns such as `ROWTIME` at the end of the protobuf schema, and as such cannot evolve the schema properly and gets a 409/conflict from schema registry attempting to register the schema. We speculate that if instead KSQL adds metadata columns at the beginning would allow schema with added fields to be registered to schema registry in a backward compatible way.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 

6.2.1

2. Sample source data.
N/A

3. Any SQL statements you ran

Original KSQL queries with just field a used
```sql
CREATE TABLE my_table (
  `key` VARCHAR PRIMARY KEY
) WITH (
  kafka_topic='table',
  value_format='PROTOBUF'
);

CREATE STREAM my_stream (
  `a` VARCHAR
) WITH (
  kafka_topic='stream',
  value_format='PROTOBUF'
);

CREATE STREAM my_join_stream
WITH (
  kafka_topic='join_stream',
  value_format='PROTOBUF'
) AS SELECT
  `a`,
  my_table.`key` as `my_table_key`,
FROM my_stream
INNER JOIN my_table ON my_stream.`a` = my_table.`key`;
```

Here is the second version of the KSQL query file with a new field b in the stream and join select statement
```sql
CREATE TABLE my_table (
  `key` VARCHAR PRIMARY KEY
) WITH (
  kafka_topic='table',
  value_format='PROTOBUF'
);

CREATE STREAM my_stream (
  `a` VARCHAR,
  `b` VARCHAR
) WITH (
  kafka_topic='stream',
  value_format='PROTOBUF'
);

CREATE STREAM my_join_stream
WITH (
  kafka_topic='join_stream',
  value_format='PROTOBUF'
) AS SELECT
  `a`,
  my_table.`key` as `my_table_key`,
  `b`
FROM my_stream
INNER JOIN my_table ON my_stream.`a` = my_table.`key`;
```

**Expected behavior**
We would expect KSQL could register the new schema with added field in a compatible way. It is difficult for us to reason about the content of these intermediate/internal topics but in general we might expect in the case that KSQL encounters data in the old schema format without an added field it would either write to the join topic using an older schema without the added field, or use the new version but with the added field set to a default value. While this second case isn't ideal as it could lead to misinterpreting the data, the present behavior gives us no ability to migrate our schemas which is far worse.

**Actual behaviour**
1. CLI output
N/A
2. Error messages
See below
3. KSQL logs
 
When data is sent in we see a 409 from KSQL on the new join repartition schema it is attempting to register.
```
[2021-10-08 14:13:03,201] ERROR Unhandled exception caught in streams thread _confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-95fb5472-ffc7-40fa-b64c-488c30bbedf1-StreamThread-2. (UNKNOWN) (io.confluent.ksql.util.QueryMetadata)
org.apache.kafka.streams.errors.StreamsException: Error encountered sending record to topic _confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition for task 1_0 due to:
org.apache.kafka.common.errors.SerializationException: Error serializing message to topic: _confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition. Failed to access Avro data from topic _confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition : Schema being registered is incompatible with an earlier schema for subject "_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition-value"; error code: 409
```

**Additional context**

Here is the initial join repartition schema created by ksql, in this simplified case the `ROWTIME` field is the only appended metadata field:
```bash
curl localhost:8081/subjects | jq -r
```
```json
[
  "table-value",
  "_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition-value",
  "stream-value",
  "_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-KafkaTopic_Right-Reduce-changelog-value",
  "join_stream-value"
]
```
```bash
curl localhost:8081/subjects/_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition-value/versions/1 | jq -r
```
```json
{
  "subject": "_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition-value",
  "version": 1,
  "id": 5,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n  string MY_STREAM_a = 1;\n  int64 MY_STREAM_ROWTIME = 2;\n}\n"
}
```

If you delete the conflicting original schema we can see KSQL is attempting to register this, which appends MY_STREAM_b in the middle, shifting the fields and breaking backwards compatibility

```json
{
  "subject": "_confluent-ksql-my-appquery_CSAS_MY_JOIN_STREAM_0-Join-repartition-value",
  "version": 1,
  "id": 5,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n  string MY_STREAM_a = 1;\n  string MY_STREAM_b = 2;\n  int64 MY_STREAM_ROWTIME = 3;\n}\n"
}
```

If useful, here are the schemas for the input topics

```bash
curl localhost:8081/subjects/stream-value/versions/1 | jq -r
```
```json
{
  "subject": "stream-value",
  "version": 1,
  "id": 1,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage StreamValue {\n  string a = 1;\n  string b = 2;\n}\n"
}
```
```bash
curl localhost:8081/subjects/table-value/versions/1 | jq -r
```
```json
{
  "subject": "table-value",
  "version": 1,
  "id": 2,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage Table {\n  string key = 1;\n}\n"
}
```

Here is the first schema version of the join stream

```bash
curl localhost:8081/subjects/join_stream-value/versions/1 | jq -r
```
```json
{
  "subject": "join_stream-value",
  "version": 1,
  "id": 3,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n  string my_table_key = 1;\n}\n"
}
```

And the second version of the join stream after adding the field to the KSQL commands (this is compatible)
```bash
curl localhost:8081/subjects/join_stream-value/versions/2 | jq -r
```
```json
{
  "subject": "join_stream-value",
  "version": 2,
  "id": 6,
  "schemaType": "PROTOBUF",
  "schema": "syntax = \"proto3\";\n\nmessage ConnectDefault1 {\n  string my_table_key = 1;\n  string b = 2;\n}\n"
}
```

**Comment by spena** [comment] 2021-11-09 19:20
@jhovell I'm going to close this as schema changes in a persistent query are not supported yet. Also, as we discussed offline in the community slack, seems the issue was caused by a direct schema change in the SR subject for the internal re-partition topic that caused the incompatibility with KSQL.

**Closed by spena** 2021-11-09 19:20 UTC
Labels: bug, query-upgrades, streaming-engine
