### ISSUE TITLE
Case not working with explode column

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#5782] opened 2020-07-08 01:25 UTC
**Describe the bug**
Case when throws an exception when used with `explode`.
```
create stream arraytest (val array<int>) with (kafka_topic='arraytest', value_format='json', partitions=1);

create stream s3 as select case when val[4] > 3 then explode(val) end as test from arraytest;
io.confluent.ksql.execution.expression.tree.SearchedCaseExpression cannot be cast to io.confluent.ksql.execution.expression.tree.UnqualifiedColumnReferenceExp
```

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL.
Current master
2. Sample source data.
```
insert into arraytest (val) values (array[1,2,3,4,5]);
```
3. Any SQL statements you ran

**Expected behavior**

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
2. Error messages
io.confluent.ksql.execution.expression.tree.SearchedCaseExpression cannot be cast to io.confluent.ksql.execution.expression.tree.UnqualifiedColumnReferenceExp
3. KSQL logs

**Additional context**

**Comment by purplefox** [comment] 2020-07-13 08:39
This is by design, so I've removed the bug label.

Table functions are designed to work on directly on the select clause only, they can't be used as operands to expressions whether that expression is a UDF, case statement or anything else.

Expressions in ksqlDB are designed to return a scalar value not a vector of values. In order to support expressions that can return a vector of values would most likely require a significant and deep refactoring of the expression implementation in the core of the engine.

**Comment by spena** [comment] 2021-11-03 21:52
Explode works now with case clauses. I tested in the current master branch, which is 0.24
```
ksql> select * from arraytest;
+---------------------------------------------------------------------------------------------------------------------------------------+
|VAL                                                                                                                                    |
+---------------------------------------------------------------------------------------------------------------------------------------+
|[1, 2, 3, 4, 5]                                                                                                                        |
Query terminated


ksql> create stream s3 as select case when val[4] > 3 then explode(val) end as test from arraytest;

 Message                         
---------------------------------
 Created query with ID CSAS_S3_3 
---------------------------------

ksql> select * from s3;
+---------------------------------------------------------------------------------------------------------------------------------------+
|TEST                                                                                                                                   |
+---------------------------------------------------------------------------------------------------------------------------------------+
|1                                                                                                                                      |
|2                                                                                                                                      |
|3                                                                                                                                      |
|4                                                                                                                                      |
|5                                                                                                                                      |
Query terminated
```

There's another issue with explode, though. If the case condition is false, then explode returns all null values.
```
ksql> select case when val[1] > 3 then explode(val) end as test from arraytest;
+---------------------------------------------------------------------------------------------------------------------------------------+
|TEST                                                                                                                                   |
+---------------------------------------------------------------------------------------------------------------------------------------+
|null                                                                                                                                   |
|null                                                                                                                                   |
|null                                                                                                                                   |
|null                                                                                                                                   |
|null                                                                                                                                   |
Query terminated
```

I'll close this and follow-up on the null issue in https://github.com/confluentinc/ksql/issues/8065

**Closed by spena** 2021-11-03 21:52 UTC
Labels: enhancement, P1
