### ISSUE TITLE
Better support for data without timestamps

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#646] opened 2018-01-21 19:49 UTC
Topic contents (from Elasticsearch's filebeats tool):

```
{"ROWTIME":-1,"ROWKEY":"null","@timestamp":"2018-01-20T21:48:42.069Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.1.2","topic":"logs"},"message":"2018-01-20 21:48:40+00 asgard02 deleted[582]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=12339=0x3033 expectedThread=20483=0x5003","prospector":{"type":"log"},"beat":{"name":"asgard02.local","hostname":"asgard02.local","version":"6.1.2"},"source":"/var/log/install.log","offset":44244986}
{"ROWTIME":-1,"ROWKEY":"null","@timestamp":"2018-01-20T21:48:42.069Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.1.2","topic":"logs"},"source":"/var/log/install.log","offset":44245154,"message":"2018-01-20 21:48:40+00 asgard02 deleted[582]: diskmanagement: [DMManager(PrivateMethods) clientConforms:error:]: currentThread=12339=0x3033 expectedThread=20483=0x5003","prospector":{"type":"log"},"beat":{"name":"asgard02.local","hostname":"asgard02.local","version":"6.1.2"}}
^CTopic printing ceased
```

Create a stream :
```
ksql> create stream logs (source varchar, message varchar, prospector varchar) with (kafka_topic='logs', value_format='json');

 Message
----------------
 Stream created
----------------
```

Error:
```
ksql> select * from logs limit 5;
Input record ConsumerRecord(topic = logs, partition = 0, offset = 387621, CreateTime = -1, serialized key size = -1, serialized value size = 339, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ '/var/log/system.log' | 'Jan 20 21:51:32 --- last message repeated 2 times ---' | '{"type":"log"}' ]) has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data.
Query terminated
```

1. Why is the timestamp failure a hard error? Seems KSQL could be more forgiving here and only throw this error if a timestamp-related function (e.g. aggreggation) is called

A valid use case here would be simply wanting to filter the stream, or repartition it etc.

**Comment by dguy** [comment] 2018-01-23 23:23
This is coming from streams. Timestamps are needed in-order to process the data in a "correct" way, i.e., to do joins etc. If the data doesn't have a time stamp in the `ConsumerRecord`, which should rarely be the case, then we'd need to set the `WallclockTimestampExctractor` - in streams we can do this on a stream by stream basis, so it seems we should also be able to set this via the `with` clause when creating a stream or table

**Comment by big-andy-coates** [comment] 2018-04-11 09:58
Is this not caused by messages being written to either an older version of Kafka (pre 0.10) or the topic having an old log format, which means there is no timestamp on the record?  For all new Kafka installs / log formats isn't the record timestamp always present? (i.e. always either set by the producer or the broker).

If this is the case, then there may be a case to close this issue as it's going to have little benefit going forward.  (There may still be a case of provide a way of the user dictating the use of wall-clock time, but that should be a separate issue),.

**Closed** 2018-04-13 10:03 UTC

**Comment by parth22594** [comment] 2018-12-06 12:09
how to set `WallclockTimestampExctractor ` with `with` clause while creating the stream or table ?

**Comment by applesss** [comment] 2019-04-15 02:03
how to set WallclockTimestampExctractor with with clause while creating the stream or table
