### ISSUE TITLE
KSQL multi-table join by 2 different keys which are not the partition key

### ISSUE THREAD

**Issue by Psykepro** [confluentinc/ksql#7269] opened 2021-03-22 16:11 UTC
Is it possible to join 3 tables by using 2 different keys from the first table to join the other 2 tables? Because from what I see it is not possible as the joins are only supported by partition key and I can't partition the table by 2 keys.

kdqlDB Server version: v6.0.2

I tried like that:
```
CREATE TABLE TABLE_TRANSACTIONS_ENRICHED AS
    SELECT
        a.AGR_SERIAL, a.AGR_START_DATE, a.AGR_END_DATE,
        t.TRN_SERIAL, t.TRN_DEBIT_VALUE, t.TRN_CREDIT_VALUE, t.TRN_TRANSACTION_COMMENT, t.TRN_PAYING_IN_REFERENCE, t.TRN_DATE_TIME, t.TRN_EFFECTIVE_DATE, t.__OP,
        tt.TRT_DESCRIPTION
  FROM TABLE_TRANSACTIONS as t
    LEFT JOIN TABLE_TRANSACTION_TYPES as tt ON t.TRN_TYPE = tt.TRT_SERIAL
    LEFT JOIN TABLE_AGREEMENTS as a ON t.TRN_AGREEMENT = a.AGR_SERIAL
```

Where:
TABLE_TRANSACTIONS - Partitioned by TRN_SERIAL
TABLE_TRANSACTION_TYPES - Partitioned by TRT_SERIAL
TABLE_AGREEMENTS - Partitioned by AGR_SERIAL

But got the following error because TABLE_TRANSACTIONS isn't partitioned by TRN_TYPE:
`Cannot repartition a TABLE source. If this is a join, make sure that the criteria uses the TABLE's key column TRN_SERIAL instead of TRN_TYPE`

Please help this is the last thing I need to finish everything

**Comment by agavra** [comment] 2021-03-22 16:41
Hello @Psykepro - this is currently not possible. I'll close this as a duplicate of https://github.com/confluentinc/ksql/issues/4424 - you can try this suggestion https://github.com/confluentinc/ksql/issues/4424#issuecomment-593147215 in the meantime.

**Closed by agavra** 2021-03-22 16:41 UTC
Labels: needs-triage, question
