### ISSUE TITLE
Handling of exceptions in SelectValueMapper should be improved.

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#393] opened 2017-10-18 09:24 UTC
Currently if we get an exception while trying to extract a value from a column we just log it, record a null value for the column and move on, however this behaviour doesn't seem correct.

It would seem that there needs to be some config to control this behaviour, i.e., in the event of corrupt data, maybe you wan't to stop the world. Maybe you just want to ignore it. That said, with schemas and strong typing, there shouldn't be corrupt data at this point, so it could be a bug in the code which really should stop the world.

**Comment by miguno** [comment] 2017-10-30 12:42
Is this still the case @dguy?

**Comment by dguy** [comment] 2017-10-30 12:44
@miguno, yes it is

**Comment by big-andy-coates** [comment] 2020-11-18 14:03
Closing as:
 - it's 3 years old
 - we now have the processing logger for capturing such errors, (though this is still just logging)
 - as dguy mentioned, this is generally caused by bugs in the code / function.

**Closed by big-andy-coates** 2020-11-18 14:03 UTC
Labels: enhancement
