### ISSUE TITLE
Better error message on unknown join criteria.

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#839] opened 2018-03-02 16:47 UTC
While creating a new stream with a join I miss spelt the join criteria. The error message could be more helpful, e.g. running cmd:

```
CSAS ... ON unknown_stream.userid = users_original.userid;
```

Resulting in error:

```
Invalid join criteria (UNKNOWN.USERID = USERS_ORIGINAL.USERID). Key for PAGEVIEWS_ORIGINAL is not set correctly.
```

Could it not instead/as-well call out that 'UNKNOWN' is indeed unknown? In my case the error was not as obvious and spotting the spelling mistake took a while.

**Comment by big-andy-coates** [comment] 2019-09-13 10:13
Hey @purplefox, another quick task - I think this is in the area you've been looking into...

**Comment by purplefox** [comment] 2019-09-18 06:04
I couldn't reproduce this. I tried a few variations but couldn't get the error message as reported above.
Here's my output:
```
ksql> CREATE STREAM S1 (ID bigint) WITH (kafka_topic='test1', value_format='JSON');
CREATE STREAM S1 (ID bigint) WITH (kafka_topic='test1', value_format='JSON')
 Message        

 Stream created 

ksql> CREATE STREAM S2 (ID bigint) WITH (kafka_topic='test2', value_format='JSON');
CREATE STREAM S2 (ID bigint) WITH (kafka_topic='test2', value_format='JSON')
 Message        

 Stream created 

ksql> create stream foo as select * from s1 join s2 on s11.id=s2.id;
Failed to prepare statement: 'S11' is not a valid stream/table name or alias.
ksql> create stream foo as select * from s1 join s2 on s1.blah=s2.id;
Line: 1, Col: 57 : Invalid join criteria (S1.BLAH = S2.ID). Column S1.BLAH does not exist.
ksql> create stream foo as select * from s11 join s2 on s1.id=s2.id;
Failed to prepare statement: S11 does not exist.
```

**Comment by purplefox** [comment] 2019-09-19 10:16
Closing as cannot reproduce. Most likely it's been fixed by a recent change.

**Closed by purplefox** 2019-09-19 10:16 UTC
Labels: bug, user-experience
