### ISSUE TITLE
Add a LASTK aggregation function to KSQL

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#1299] opened 2018-05-11 22:39 UTC
Some users have asked for a LASTK aggregation function that returns the last K seen values of a certain column. For example:

```sql
CREATE STREAM visitors (pageid string, userid string) ...
CREATE TABLE last3visitors AS SELECT pageid, LASTK(userid, 3) FROM visitors;
```

Which for the followings data in visitors:

```
1, 1
2, 5
1, 3
1, 4
1, 2
```

Would output:

```
1, [1]
2, [5]
1, [3, 1]
1, [4, 3, 1]
1, [2, 4, 3]
```

**Comment by apurvam** [comment] 2018-05-11 22:45
Isn't this a dup of #1128?

**Comment by agavra** [comment] 2019-10-16 21:56
Closing as duplicate of #1128.

**Closed by agavra** 2019-10-16 21:56 UTC
