### ISSUE TITLE
JSON elements in CAPS

### ISSUE THREAD

**Issue by joshualouis911** [confluentinc/ksql#3195] opened 2019-08-12 10:14 UTC
We have used persistence stream using KSQL. The events are stored in JSON and we got strict message structure and format. The JSON attributes have to follow snake case  e.g. "first_name". The KSQL stream output is of ALLCAPS e.g. "FIRST_NAME".  Is there any way to retain the format in KSQL.

**Comment by rajbhino** [comment] 2019-08-13 14:31
Same problem for me as well and looking for answer from Confluent Support. Enclosing in double quotes as recommended does not yield values and shows as null when SELECT is done on them. Also Partition BY clause does not resolve field name enclosed in double quotes.
Column "column name from result set" does not exist in the result schema. Error in Partition By clause.

**Comment by joshualouis911** [comment] 2019-08-30 12:55
We had created one more stream to convert the CAPS to snake case. But this creates an additional persistent stream which is like duplicating the same logs. Is there any milestone for fixing this issue

**Comment by big-andy-coates** [comment] 2019-10-11 17:33
Hi @rajbhino and @joshualouis911 

What you need is quoted identifiers, which will allow you to control the case of the field names in the output. 

I believe this will now work on master, (See https://github.com/confluentinc/ksql/issues/1039), so will be available in the upcoming 5.4. release.

Hence, closing this issue as a duplicate of #1039

**Closed by big-andy-coates** 2019-10-11 17:33 UTC
