### ISSUE TITLE
Add ORDER BY to Select queries

### ISSUE THREAD

**Issue by Mall0c** [confluentinc/ksql#8038] opened 2021-08-23 10:16 UTC
I think the suggestion is pretty clear. It would be great if one could order the result set by one or more columns. I haven't found anything that does that so I suppose it hasn't been implemented yet.

**Comment by agavra** [comment] 2021-08-23 15:38
Thanks @Mall0c for the suggestion - I'll close this as a duplicate of  #1572 and #528, this work is unplanned at the moment

**Closed** 2021-08-23 15:38 UTC
Labels: enhancement
