### ISSUE TITLE
INSERT INTO throws incompatible schema for a stream on top of a table with a composite key

### ISSUE THREAD

**Issue by znxftw** [confluentinc/ksql#9171] opened 2022-06-03 12:22 UTC
**Describe the bug**
If you create a table via KSQL with a certain topic and create a stream on top of that same topic, the topic registered in schema registry has `schema.name` = table name. When you try to insert a record into the stream, the insert query tries to register the same schema with `schema.name` = stream name which causes the query to fail for an incompatible schema.

**To Reproduce**
(ksql 0.25.1)

```sql
CREATE TABLE T (A INT PRIMARY KEY, B INT PRIMARY KEY, C BOOLEAN)
WITH( KAFKA_TOPIC = 'T', KEY_FORMAT = 'AVRO', VALUE_FORMAT = 'AVRO', PARTITIONS = 1 );
CREATE STREAM T_STREAM(A INT KEY, B INT KEY, C BOOLEAN)
WITH( KAFKA_TOPIC = 'T', KEY_FORMAT = 'AVRO', VALUE_FORMAT = 'AVRO' );

CREATE STREAM SOURCE_STREAM(A INT  KEY, B INT  KEY, C BOOLEAN)
WITH( KAFKA_TOPIC = 'SOURCE_TOPIC', KEY_FORMAT = 'AVRO', VALUE_FORMAT = 'AVRO', PARTITIONS = 1 );
INSERT INTO SOURCE_STREAM VALUES( 1, 1, true);

INSERT INTO T_STREAM SELECT * FROM SOURCE_STREAM EMIT CHANGES;
```

**Expected behavior**
The data gets inserted successfully

**Actual behaviour**
No data goes into the stream, if you explain the final query you will see :
```
Caused by: org.apache.kafka.common.errors.SerializationException: Error registering Avro schema{"type":"record","name":"TStreamKey","namespace":"io.confluent.ksql.avro_schemas","fields":[{"name":"A","type":["null","int"],"default":null},{"name":"B","type":["null","int"],"default":null}]}

Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema being registered is incompatible with an earlier schema for subject "T-key"; error code: 409
```

**Additional context**
Comparing the key schemas,

Schema Registry has 
```
{"type":"record","name":"TKey","namespace":"io.confluent.ksql.avro_schemas","fields":[{"name":"A","type":["null","int"],"default":null},{"name":"B","type":["null","int"],"default":null}],"connect.name":"io.confluent.ksql.avro_schemas.TKey"}
```

whereas the insert query expected

```
{"type":"record","name":"TStreamKey","namespace":"io.confluent.ksql.avro_schemas","fields":[{"name":"A","type":["null","int"],"default":null},{"name":"B","type":["null","int"],"default":null}]}
```
the only thing differing is `name` (also `connect_name`, but that gets ignored according to #8839) which gets taken from the first table / stream that registered the schema.

This happens only for key schema, not for the value schema. The value schema has `schema.name` as `KsqlDataSourceSchema` so no schema is attempted to be registered by the insert query.

Some extra notes : 
- If you create the stream first, this works perfectly fine because the schema that gets registered (by the stream) has the same name as the schema that the inserts try to push. 
- This only works when the key is composite / struct. If it's a simple datatype, the extra metadata like name does not get stored in SR.

**Comment by suhas-satish** [comment] 2022-06-07 23:33
This is a duplicate of or somewhat related to https://github.com/confluentinc/ksql/issues/6091 with some extra notes. Have to consider both issues together while working on the other.

**Comment by suhas-satish** [comment] 2022-06-13 20:37
cc: @aliehsaeedii , @jnh5y

**Comment by aliehsaeedii** [comment] 2022-08-09 13:34
Please update the ksqlDB server to the latest version.

**Comment by suhas-satish** [comment] 2022-08-10 21:05
@aliehsaeedii , is this not reproducible  on the latest version? what version do you recommend the user to upgrade to?

**Comment by aliehsaeedii** [comment] 2022-08-16 12:41
@znxftw If you upgrade to the version 0.27.2, the scenario you addressed is completely executed with no problem.

@suhas-satish Thanks for the good tip.

**Comment by suhas-satish** [comment] 2022-08-16 15:28
Will close this issue since its not reproducible. We can re-open later if we get reproducible stacktrace with associated data

**Closed by suhas-satish** 2022-08-16 15:28 UTC
Labels: bug, P0, streaming-engine
