### ISSUE TITLE
ksqlDB throws unhelpful error "type"

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#6566] opened 2020-11-03 18:13 UTC
ksqlDB 0.12

```sql
ksql> CREATE STREAM ORDERS_DELETED
>  WITH (KAFKA_TOPIC='orders_processed', VALUE_FORMAT='KAFKA') AS
>  SELECT ORDER_ID, NULL FROM ORDERS_SRC
>   WHERE CANCELLED_IND = TRUE;
type
ksql>
```

I think the problem is selecting the `NULL`, but regardless of its validity the error message should be better.

**Comment by rmoff** [comment] 2020-11-03 20:48
(FWIW to include a `NULL` in a CSAS like this you need to `CAST` it, e.g. `CAST(NULL AS VARCHAR)`)

**Comment by jzaralim** [comment] 2020-11-11 00:12
Closing since this is a duplicate of #5016

**Closed by jzaralim** 2020-11-11 00:12 UTC
Labels: P0, fix-it-week, user-experience
