### ISSUE TITLE
Table join Table

### ISSUE THREAD

**Issue by sangli00** [confluentinc/ksql#2303] opened 2018-12-25 02:54 UTC
eg:

```
create table test as select columns from tab1 inner join tab2 on tab1.col1 = tab2.col1 and tab1.col2 > 10;
```
but ,cannot create this statement.

```
ksql> create table tran_test1 as select t2.total,t1.host from test1 t1 inner  join join_table t2 on t1.host = t2.host and test1.total >1;
io.confluent.ksql.parser.tree.LogicalBinaryExpression cannot be cast to io.confluent.ksql.parser.tree.ComparisonExpression
ksql>
```

**Comment by miguno** [comment] 2019-01-11 09:35
I suppose the problem is the lack of white space between `>` and `1`:

```
test1.total >1
```

Try the second statement with:

```
test1.total > 1
```

**Comment by mjsax** [comment] 2021-02-04 20:57
The issue seems to be that our join predicate only allows a single equi-predicate.  The second conditions should be expressed in the `WHERE clause`

```sql
CRATE TABLE test AS
  SELECT columns
  FROM tab1 INNER JOIN ON tab1.col1 = tab2.col1
  WHERE tab1.col2 > 10;
```

**Comment by mjsax** [comment] 2021-02-04 20:58
Closing this ticket. Feel free to reopen if it does not answer your question.

**Closed by mjsax** 2021-02-04 20:58 UTC
Labels: awaiting-info, question
