### ISSUE TITLE
Support multi-way joins between two objects (1:N)

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [confluentinc/ksql#1532] opened 2018-07-04 09:51 UTC
KSQL version: 5.0.x
I am confused whether KSQL can left join two one-to-many tables.When I try it，the result is not what I want. 'Many' table can't join with 'one' table.
![image](https://user-images.githubusercontent.com/20380664/42269434-b5fe4348-7fb0-11e8-8e17-86512d9d0686.png)

I had considered stream-table left join, but I am also confused that whether ktable can triggle join operation when there is a update on ktable. I plan to splicing two mysql one-to-many tables into a flat table which is then export to elasticsearch. Can I use KSQL to implemet it?If it can, how should I do?
Any suggestions will be appreciated！

**Comment by apurvam** [comment] 2018-07-05 17:43
Which version of KSQL is this? table-table joins were added recently, so unless you are running a recent master build, this would not work.

**Comment by ZhiXingHeYiApple** [comment] 2018-07-06 02:07
@apurvam KSQL version: 5.0.x
As describe #1417 ,This version of the KSQL had merge the new-joins. Can it deal with the 1:N joins?If not, can I use kafka streams API to implement it?

**Comment by apurvam** [comment] 2018-08-08 18:08
Right now, KSQL doesn't support multi-way joins for any of stream-stream, stream-table, table-table joins.

We can use this issue to track the enhancement request.

**Comment by miguno** [comment] 2018-10-31 17:06
Related to https://github.com/confluentinc/ksql/issues/1891.

**Comment by miguno** [comment] 2018-12-03 07:56
+1 from an offline discussion with a user

**Comment by jeffbeagley** [comment] 2019-01-14 15:04
KSQL acts as a solid bridge in solving a lot of previous ETL issues, however its here to help mitigate batch jobs running from a relational database. Crazy to think it can't support multi joins especially in a RDBMS. We have excuses requiring sometimes 5-10 joins depending on the information. I know this can be solved within views before hand, but imagine finally being able to join data regardless or origin.

**Comment by rmoff** [comment] 2019-02-08 15:04
Modifying title to differentiate it from #1891.

**Comment by csurepeddi** [comment] 2019-09-07 16:06
I was wondering if this issue has been fixed? If not is there is a timeline on this? thank you

**Comment by big-andy-coates** [comment] 2020-03-25 18:51
From reading this, this looks like its about joining from one table to a non-primary-key field on another table.  Is that correct?

For example,

```sql
CREATE TABLE T1 (ID INT PRIMARY KEY, NAME STRING);
CREATE TABLE T2 (ID INT PRIMARY KEY, FK_ID INT, V0 STRING);

SELECT * FROM T1 JOIN T2 ON T1.ID = T2.FK_ID;
```

Is this what you're trying to achieve?  If so, then you're needing this feature: https://github.com/confluentinc/ksql/issues/4424

**Comment by rmoff** [comment] 2020-04-02 13:18
is this a dup of https://github.com/confluentinc/ksql/issues/1559 and/or https://github.com/confluentinc/ksql/issues/4424 ?

**Comment by mjsax** [comment] 2021-02-04 20:51
Given the description

> I am confused whether KSQL can left join two one-to-many tables.

is seem to be a duplicate of https://github.com/confluentinc/ksql/issues/4424.

Closing this for now. @ZhiXingHeYiApple if you disagree, feel free to reopen.

**Closed by mjsax** 2021-02-04 20:51 UTC
Labels: enhancement, join-functions
