### ISSUE TITLE
ksql-rest-app doc

### ISSUE THREAD

**Issue by JozeFe** [confluentinc/ksql#1067] opened 2018-03-27 15:00 UTC
Please where can I found any documentation for KSQL REST API, 
eg. endpoints, response formats, quick start

Thank you.

**Comment by cricket007** [comment] 2018-03-27 16:30
Related to #304

**Comment by big-andy-coates** [comment] 2018-03-28 08:05
Hi @JozeFe , I'm closing this as it's a duplicate of #304.  REST API docs are coming... ;)

**Closed by big-andy-coates** 2018-03-28 08:05 UTC
Labels: duplicate

**Comment by JozeFe** [comment] 2018-03-28 11:39
@big-andy-coates Thank you for fast reply. :)
