### ISSUE TITLE
INSERT INTO : Failed to insert values into stream/table Caused by: org.apache.kafka.common.KafkaException: Producer is closed forcefully.

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#3141] opened 2019-07-29 15:36 UTC
```
ksql> SHOW TABLES;

 Table Name | Kafka Topic | Format | Windowed
----------------------------------------------
 FOO        | FOO         | AVRO   | false
----------------------------------------------
ksql> SHOW STREAMS;

 Stream Name         | Kafka Topic         | Format
----------------------------------------------------
 MOVIE_TICKET_SALES2 | movie-ticket-sales2 | AVRO
 RATINGS             | ratings             | AVRO
 MOVIE_TICKET_SALES  | movie-ticket-sales  | AVRO
----------------------------------------------------
ksql> SHOW TOPICS;

 Kafka Topic         | Registered | Partitions | Partition Replicas | Consumers | ConsumerGroups
-------------------------------------------------------------------------------------------------
 _confluent-metrics  | false      | 12         | 1                  | 0         | 0
 _schemas            | false      | 1          | 1                  | 0         | 0
 FOO                 | true       | 1          | 1                  | 0         | 0
 movie-ticket-sales  | true       | 1          | 1                  | 0         | 0
 movie-ticket-sales2 | true       | 1          | 1                  | 0         | 0
 ratings             | true       | 1          | 1                  | 0         | 0
-------------------------------------------------------------------------------------------------
```

Insert into one of the streams works fine: 

```
ksql> INSERT INTO MOVIE_TICKET_SALES2 (title, sale_ts, ticket_total_value) VALUES ('Die Hard','2019-07-18T10:01:36Z',24);

ksql> print 'movie-ticket-sales2' from beginning;
Format:AVRO
7/29/19 3:29:17 PM UTC, null, {"TITLE": "Die Hard", "SALE_TS": "2019-07-18T10:01:36Z", "TICKET_TOTAL_VALUE": 24}
```

Insert into the other stream and table fails: 

```
ksql> INSERT INTO FOO (COL1) VALUES (42);
Failed to insert values into stream/table: FOO
Caused by: org.apache.kafka.common.KafkaException: Producer is closed
        forcefully.
Caused by: Producer is closed forcefully.

ksql> INSERT INTO MOVIE_TICKET_SALES (title, sale_ts, ticket_total_value) VALUES ('Die Hard','2019-07-18T10:01:36Z',24);
Failed to insert values into stream/table: MOVIE_TICKET_SALES
Caused by: org.apache.kafka.common.KafkaException: Producer is closed
        forcefully.
Caused by: Producer is closed forcefully.
```

DESCRIBE for each object: 

```
ksql> describe extended foo;

Name                 : FOO
Type                 : TABLE
Key field            :
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : AVRO
Kafka topic          : FOO (partitions: 1, replication: 1)

 Field   | Type
-------------------------------------
 ROWTIME | BIGINT           (system)
 ROWKEY  | VARCHAR(STRING)  (system)
 COL1    | INTEGER
-------------------------------------

Local runtime statistics
------------------------


(Statistics of the local KSQL server interaction with the Kafka topic FOO)
ksql>

ksql> describe extended MOVIE_TICKET_SALES;

Name                 : MOVIE_TICKET_SALES
Type                 : STREAM
Key field            :
Key format           : STRING
Timestamp field      : SALE_TS
Value format         : AVRO
Kafka topic          : movie-ticket-sales (partitions: 1, replication: 1)

 Field              | Type
------------------------------------------------
 ROWTIME            | BIGINT           (system)
 ROWKEY             | VARCHAR(STRING)  (system)
 TITLE              | VARCHAR(STRING)
 SALE_TS            | VARCHAR(STRING)
 TICKET_TOTAL_VALUE | INTEGER
------------------------------------------------

Local runtime statistics
------------------------


(Statistics of the local KSQL server interaction with the Kafka topic movie-ticket-sales)
ksql> describe extended MOVIE_TICKET_SALES2;

Name                 : MOVIE_TICKET_SALES2
Type                 : STREAM
Key field            :
Key format           : STRING
Timestamp field      : SALE_TS
Value format         : AVRO
Kafka topic          : movie-ticket-sales2 (partitions: 1, replication: 1)

 Field              | Type
------------------------------------------------
 ROWTIME            | BIGINT           (system)
 ROWKEY             | VARCHAR(STRING)  (system)
 TITLE              | VARCHAR(STRING)
 SALE_TS            | VARCHAR(STRING)
 TICKET_TOTAL_VALUE | INTEGER
------------------------------------------------

Local runtime statistics
------------------------


(Statistics of the local KSQL server interaction with the Kafka topic movie-ticket-sales2)
```

**Comment by agavra** [comment] 2019-07-29 15:39
Seems like duplicate of: https://github.com/confluentinc/ksql/issues/3021

I haven't been able to figure that one out yet...

**Comment by rmoff** [comment] 2019-07-29 15:44
FWIW `MOVIE_TICKET_SALES` was previously a `TABLE`, which I `DROP`d and then re`CREATE`d as a `STREAM`. Seems odd that if this is an issue around `TABLE` and not specifying a KEY that it should impact a `STREAM` in this way.

**Comment by purplefox** [comment] 2019-09-19 10:13
Duplicate of https://github.com/confluentinc/ksql/issues/3021

Closing as cannot reproduce.

**Closed by purplefox** 2019-09-19 10:13 UTC
Labels: bug

**Comment by big-andy-coates** [comment] 2019-10-17 09:23
Fixed by https://github.com/confluentinc/ksql/pull/3605
