### ISSUE TITLE
When KSQL service restarts an existing JOIN stream does not work as expected

### ISSUE THREAD

**Issue by robertrbruno** [confluentinc/ksql#1265] opened 2018-05-02 21:24 UTC
When KSQL service restarts existing JOIN streams are resumed, but seems like it resumes the left stream and the right table of the JOIN with existing group offsets.

This makes sense for the stream but not the table at least in my use case.  It seems like the table should reset to the beginning on restart.  If I manually delete the group offsets for the JOIN stream all works as expected.

Perhaps there could be parameters in the JOIN that let you change the offsets of reset to earliest (for the table), latest (for the stream) and if left blank it would just use the existing offsets?

**Comment by rodesai** [comment] 2018-05-02 21:30
@robertrbruno the data in your table at earlier offsets should be restored from the table state store changelog topic. So your results should still be correct after a result. Are you seeing bad query output?

**Comment by robertrbruno** [comment] 2018-05-03 14:11
Here is the behavior I am seeing. 

- Have a join running between a stream and a table.  The table in this example is static in that I am not adding new values to it.  I see numerous successful joins.

- I restart ksql server (both hard restarts and graceful) and I no longer getting any successful joins.

I do see the following in the logs but not sure if that has to do anything with this.

"No custom setting defined for topic '_confluent-ksql-default_query_CSAS_JOINNAME-KSTREAM-MAPVALUES-0000000010-repartion' using original config 'latest' for offset reset (org.apache.kafka.streams.processor.internals,StreamThread:886)

If I manually delete the group id associated with the query after restart things work correctly.

**Comment by robertrbruno** [comment] 2018-05-03 20:52
Ran more testing.  I apparently was not giving ksql enough time to reinitialize.  If i waited a few minutes things do resume correctly.  Sorry for the false alarm.

**Comment by apurvam** [comment] 2018-05-03 22:05
great. thanks for the update. Closing this out.

**Comment by robertrbruno** [comment] 2018-05-04 20:10
Sorry but I do think this may need to be reopened.

I did more testing today and getting inconsistent results.

I have a join of the following nature:

CREATE STREAM JOINSTREAM AS \
  SELECT * \
      FROM SOURCESTREAM source
      LEFT JOIN MYTABLE mytab ON source.source_value = mytab.my_value \
      WHERE mytab.my_value IS NOT NULL;

When I subscribe to JOINSTREAM I will see only results where there was actually a matching value in MYTABLE. This works fine until I kill the pod that has the ksql server in it (running this in kubernetes).  So I am not just restarting the server but killing the entire enviornment/memory of the ksql server.  Kafka though is on other pods which are not being reset for this test.

When the ksql pod comes back up, the stream still is listed when I do list streams;  But no longer get MYTABLE matches when I should be.  I know this to be true because I tried creating a second identical stream at this point with a different name and the second stream was displaying matches.

As a further test, I inserted a value into the table after the ksql restart and saw matches resume for that value on the first stream that was created prior to the ksql restart.

To further complicate matters after some time passed I created yet another stream that was identical to my earlier attempts and that stream is surviving pod kills.

I did an explain on the query for the first attempt and the later attempt and the only difference I see is the first attempt does not have any local runtime statistics while the later one does.

Do you have any thoughts on what could be causing this?  I'll keep the two streams running for now if there are other commands I can run to introspect further why the first stream is no longer working.

**Comment by robertrbruno** [comment] 2018-05-04 20:35
One other question.  When you drop a stream, I noticed the topic is not destroyed as well.  If you want to recreate a stream with the same name as a stream you have dropped what must be cleaned up first?  There is a chance for the first stream I may have recreated that stream a few times.  I want to make sure I cleaned that stream up properly.

**Comment by robertrbruno** [comment] 2018-05-04 20:58
One more data point.  It seems that if I create a new stream and restart the ksql pod all is good.  But if at any point I drop the stream, as well as manually delete the stream topic and consumer group the stream does not survive a ksql restart.  Is there more that needs to be cleaned up when one wants to recreate a stream with a stream that has been dropped in ksql?

**Comment by apurvam** [comment] 2018-05-04 23:54
Thanks for the updates @robertrbruno, they are very thorough. No, the topic is not deleted when you drop a stream. That functionality is being added, see #1277 .

So, if I understand correctly this is the current state of your observations: 

1. You have a stream and table, which are being joined.
2. Your setup is running in kubernetes.
3. If you drop the stream, and then kill the ksql pod, and then restart the pod, and recreate the stream, the join doesn't work on the recreated pod. The specific symptom is that there are no output records in the join. 
4. IF you create a new stream, kill the pod, and restart the stream, the join continues to work. 

Is this accurate? Did you also terminate the join query when you dropped the stream? If you didn't then it wouldn't work. Luckily in the 5.0.0-beta1 version, we have referential integrity which will require you to terminate the join query before dropping the stream. See #652 .

**Comment by robertrbruno** [comment] 2018-05-07 20:34
Yes accurate, and sure enough I did not drop the query.  It assumed falsely it was a cascading delete.  And ksql never complained when I created the new join.   

Are you thinking about having a drop stream with a cascade delete that would delete say the topics, group offsets, and query all in one?  Would be nice not to think about the underlying structure.

Thanks for the help!

**Comment by apurvam** [comment] 2018-05-07 20:36
Yes, see #1217

**Comment by apurvam** [comment] 2018-05-07 20:37
Though that will not terminate any dependent queries. With other changes, we will prevent DROP on streams and tables which have dependent queries, and also give you a list of queries which have to be terminated.

With #1217, we also add the ability to delete the underlying sink topic when you drop a stream or table.

With both those changes, you should not be able to get into the condition you find yourself in :)

**Comment by robertrbruno** [comment] 2018-05-07 20:41
Will https://github.com/confluentinc/ksql/issues/1217 also delete the consumer group that ksql seems to be using under the hood?

**Comment by apurvam** [comment] 2018-05-07 20:54
Unfortunately not. I don't think there is a way to remove consumer groups in Kafka. The best that can be done is to reset the offsets of the group id in question to the beginning of the topic. This feature is being tracked in #1009

**Comment by robertrbruno** [comment] 2018-05-07 20:58
I have been removing them with the CLI tool ./kafka-consumer-groups --delete.  Not sure if that is the same as you are saying.

**Comment by apurvam** [comment] 2018-05-07 21:03
The problem is that we want perform these operations programmatically. Right now, the admin client operations which enable you to delete consumer groups are only in the legacy Scala API which we don't want to depend on.

Support for consumer group operations are going to be added to the Java admin client API, which we use. Once available,  we can 'cascade' a `DROP` to also delete the consumer group eventually. The work on the Java API is being tracked here https://cwiki.apache.org/confluence/display/KAFKA/KIP-222+-+Add+Consumer+Group+operations+to+Admin+API

**Comment by robertrbruno** [comment] 2018-05-07 21:05
Thanks for the details.  I'll watch that as well.  Do you recommend for the time being to completely clean things up by deleting the consumer group?  I was worried if I created a stream with the same name the existing consumer group would cause issues.

**Comment by apurvam** [comment] 2018-05-07 21:13
The consumer group is associated with queries, not the actual stream or table. So it should be deleted when the query is terminated. I have filed an issue to track this https://github.com/confluentinc/ksql/issues/1283

**Comment by robertrbruno** [comment] 2018-05-07 21:14
Thanks again!

**Comment by apurvam** [comment] 2018-05-07 21:15
No problem! I am going to close this for now, since all the follow up feature items are being tracked separately.

**Closed by apurvam** 2018-05-07 21:15 UTC
