### ISSUE TITLE
LATEST_BY_OFFSET should support all datatypes

### ISSUE THREAD

**Issue by axaluss** [confluentinc/ksql#6610] opened 2020-11-13 19:10 UTC
**Is your feature request related to a problem? Please describe.**
LATEST_BY_OFFSET should support all datatypes. Atm it only supports primitive datatypes. 

**Describe the solution you'd like**
LATEST_BY_OFFSET should support all datatypes.
Primitive types
Decimal type
Array type
Map type
Struct type
Custom types

**Comment by big-andy-coates** [comment] 2020-11-18 10:32
duplicate of https://github.com/confluentinc/ksql/issues/5437

**Closed by big-andy-coates** 2020-11-18 10:32 UTC
Labels: P1, enhancement, user-defined-functions
