### ISSUE TITLE
`CREATE STREAM AS SELECT` fails with "Column ... cannot be resolved"

### ISSUE THREAD

**Issue by aslakhellesoy** [confluentinc/ksql#4419] opened 2020-02-01 01:01 UTC
**Describe the bug**

I'm unable to turn a working `SELECT` statement into a stream.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL.
5.4.0
2. Sample source data.

I have the following stream:

```sql
CREATE STREAM test_case( \
  `id` VARCHAR, \
  `pickle_id` VARCHAR, \
  `test_steps` ARRAY< \
    STRUCT< \
      `id` VARCHAR, \
      `pickle_step_id` VARCHAR, \
      `step_definition_ids` ARRAY<VARCHAR>, \
      `hook_id` VARCHAR \
    > \
  > \
) \
WITH (KAFKA_TOPIC='test_case', VALUE_FORMAT='JSON');
```

KSQL describe:

```
ksql> describe test_case;

Name                 : TEST_CASE
 Field      | Type
-----------------------------------------------------------------------------------------------------------------------------------------------------
 ROWTIME    | BIGINT           (system)
 ROWKEY     | VARCHAR(STRING)  (system)
 id         | VARCHAR(STRING)
 pickle_id  | VARCHAR(STRING)
 test_steps | ARRAY<STRUCT<id VARCHAR(STRING), pickle_step_id VARCHAR(STRING), step_definition_ids ARRAY<VARCHAR(STRING)>, hook_id VARCHAR(STRING)>>
```

3. Any SQL statements you ran

Querying works fine:

```sql
SELECT 
  `id`,
  `pickle_id`,
  EXPLODE(`test_steps`)->`id` as test_step_id,
  EXPLODE(`test_steps`)->`pickle_step_id` as pickle_step_id
FROM test_case
EMIT CHANGES;
```

However, I get an error when I try to create a new stream from that query:

```sql
CREATE STREAM `exploded_test_steps`
AS SELECT 
  `id`,
  `pickle_id`,
  EXPLODE(`test_steps`)->`id` as test_step_id,
  EXPLODE(`test_steps`)->`pickle_step_id` as pickle_step_id
FROM test_case
EMIT CHANGES;
``` 

**Expected behavior**

I would have expected the stream to be created without error.

**Actual behaviour**
A clear and concise description of what actually happens, including:
1. CLI output
2. Error messages

```
io.confluent.ksql.util.KsqlStatementException: Column 'TEST_CASE.ID' cannot be resolved.
```

3. KSQL logs

**Additional context**

**Comment by JeroenMinnaert** [comment] 2020-03-31 19:56
I had a similar issue when looking at `EXTRACTJSONFIELD`. Worked  for me when I declared the properties of the stream in upper case so:

```CREATE STREAM test_case( \
  `ID` VARCHAR, \
  `PICKLE_ID` VARCHAR, \
  `TEST_STEPS` ARRAY< \
    STRUCT< \
      `ID` VARCHAR, \
      `PICKLE_STEP_ID` VARCHAR, \
      `STEP_DEFINITION_IDS` ARRAY<VARCHAR>, \
      `HOOK_ID` VARCHAR \
    > \
  > \
) \
WITH (KAFKA_TOPIC='test_case', VALUE_FORMAT='JSON');```

**Comment by agavra** [comment] 2020-04-22 17:50
I think this is a duplicate of #5032 where we had a bug with lowercase quoting - can you try this on 5.5 or 0.8.1 and let me know if it works? If it doesn't feel free to re-open this ticket.

**Closed by agavra** 2020-04-22 17:50 UTC
Labels: bug
