### ISSUE TITLE
KSQL 5.4.0-beta1 - PRINT <topic> represents DECIMAL as bytes

### ISSUE THREAD

**Issue by robinroos** [confluentinc/ksql#3884] opened 2019-11-18 13:25 UTC
Not sure if this is a bug or is intentional.

I have a topic fx-spot-market with AVRO schema for Key and for Value.

`PRINT fx-spot-market;` sets up a query on the topic.

When records are streamed, DECIMAL fields are represented as:

`"fieldname": {"bytes": "JY\n\u000"}`

Here is the message I am sending (shown from the Java Consumer so I know the message is round-tripping just fine):

```
2019-11-18 13:19:21.331  INFO 13735 --- [ntainer#0-1-C-1] u.c.s.aggregator.service.MarketConsumer  : ### -> Consumed message -> {"Pair": "EURUSD", "bid": 1.255500000, "offer": 1.256000000}
```

See KSQL output below.

```
$ docker run --net=host -it confluentinc/cp-ksql-cli:5.4.0-beta1 http://0.0.0.0:8088
                  
                  ===========================================
                  =        _  __ _____  ____  _             =
                  =       | |/ // ____|/ __ \| |            =
                  =       | ' /| (___ | |  | | |            =
                  =       |  <  \___ \| |  | | |            =
                  =       | . \ ____) | |__| | |____        =
                  =       |_|\_\_____/ \___\_\______|       =
                  =                                         =
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017-2019 Confluent Inc.

CLI v5.4.0-beta1, Server v5.4.0-beta1 located at http://0.0.0.0:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> PRINT 'fx-spot-market';
Format:AVRO
11/18/19 1:19:21 PM UTC, 
                         EURUSD, {"Pair": "EURUSD", "bid": {"bytes": "JÕhà"}, "offer": {"bytes": "JÝ\n\u0000"}}
^CTopic printing ceased
ksql>

```

**Comment by robinroos** [comment] 2019-11-18 13:26
Attaching Avro schema for Key and Value of Topic fx-spot-market.

[schema-fx-spot-market-key-v1-_gP4eI3mS6O7TR9K4mgjRQ.txt](https://github.com/confluentinc/ksql/files/3858772/schema-fx-spot-market-key-v1-_gP4eI3mS6O7TR9K4mgjRQ.txt)
[schema-fx-spot-market-value-v1-_gP4eI3mS6O7TR9K4mgjRQ.txt](https://github.com/confluentinc/ksql/files/3858773/schema-fx-spot-market-value-v1-_gP4eI3mS6O7TR9K4mgjRQ.txt)

**Comment by agavra** [comment] 2019-11-18 16:31
Thanks for reporting this @robinroos! This is expected in AVRO, see the spec for the Decimal type: https://avro.apache.org/docs/1.8.1/spec.html#Decimal

This also happens with JSON, and is a known issue, because we use the Kafka Connect serialization format, but this will be fixed in the next release of KSQL (see https://github.com/confluentinc/ksql/pull/3588 and [KIP-481](https://cwiki.apache.org/confluence/display/KAFKA/KIP-481%3A+SerDe+Improvements+for+Connect+Decimal+type+in+JSON)). Instead it will be represented in its numeric form.

**Comment by agavra** [comment] 2020-01-07 19:15
Closing issue as this is expected behavior (see above). Feel free to reopen if you disagree.

**Closed by agavra** 2020-01-07 19:15 UTC
Labels: bug, needs-triage
