### ISSUE TITLE
When creating a stream, the value is always arriving null, if the field contains oneof keyword in the schema registry

### ISSUE THREAD

**Issue by lianbaghdasaryan** [confluentinc/ksql#9194] opened 2022-06-12 20:07 UTC
**Describe the bug**
I'm creating a stream from the topic, whose registered schema is a protobuf. In the schema I have a field (named "eventData"), which contains oneof keyword.
After creating the stream, I receive all the values, except of the eventData field.

**To Reproduce**
KSQL version:  0.21.0

This is the schema of the topic:

```
message ClientActivity {
  uint64 client_id = 1;
  EventData event_data = 2;
  google.protobuf.Timestamp event_time = 3;

  message EventData {
    oneof EventType {
      Login login = 1;
      Logout logout = 2;
    }
  }

  message Login{
    string ip_address = 1;
    string geo_country = 2;
    /* SMS, Email, Password */
    string method = 3;
  }

  message Logout{
    string ip_address = 1;
    string geo_country = 2;
  }
}
```

And the stream creation query is this:

```
CREATE STREAM "client-activity-stream" (
client_id BIGINT,
event_data STRUCT<
login STRUCT<ip_address STRING, geo_country STRING, method STRING>,
logout STRUCT<ip_address STRING, geo_country STRING>>,
event_time TIMESTAMP)
WITH (KAFKA_TOPIC='client.activity', KEY_FORMAT='KAFKA',  VALUE_FORMAT='PROTOBUF');
```

Sample message published in client-activity-stream

```
{
  "CLIENT_ID": 45,
  "EVENT_DATA": {
    "LOGIN": null,
    "LOGOUT": null
  },
  "EVENT_TIME": "2022-05-30T08:03:53.968",
}
```

**Expected behavior**
The messages of this stream should contain all the fields values : client_id, login or logout, event_time.

**Actual behaviour**
The stream shows only values for client_id and event_time. Login and logout values are null, but actually one of them is non null in my original topic messages. I don't receive any error messages. And couldn't find any errors in the logs.

**Additional context**
I guess the problem is oneof keyword in my proto file.

**Comment by suhas-satish** [comment] 2022-06-14 16:28
@spena , can you test this out in the latest ksqlDB versions?

**Comment by spena** [comment] 2022-06-17 20:08
This issue is similar to this other https://github.com/confluentinc/ksql/issues/9169

The problem is that KSQL + SR API creates a raw protobuf schema a little different than the one found in SR. At the moment of serializing the record, the SR API attempts to register the schema on SR to verify its compatibility. Both schemas are different so the INSERT fails.

This is the schema that KSQL + SR API generates:
```syntax = "proto3";

message ClientActivity {
  uint64 CLIENT_ID = 1;
  EventData EVENT_DATA = 2;
  string EVENT_TIME = 3;

  message EventData {
    oneof EventType {
      Login LOGIN = 1 [deprecated = false];
      Logout LOGOUT = 2 [deprecated = false];
    }
  
    message Login {
      string IP_ADDRESS = 1;
      string GEO_COUNTRY = 2;
      string METHOD = 3;
    }
    message Logout {
      string IP_ADDRESS = 1;
      string GEO_COUNTRY = 2;
    }
  }
}
```

This is the original schema from SR:
```
syntax = "proto3";

message ClientActivity {
  uint64 CLIENT_ID = 1;
  EventData EVENT_DATA = 2;
  string EVENT_TIME = 3;

  message EventData {
    oneof EventType {
      Login LOGIN = 1;
      Logout LOGOUT = 2;
    }
  }
  
  message Login {
    string IP_ADDRESS = 1;
    string GEO_COUNTRY = 2;
    string METHOD = 3;
  }
  
  message Logout {
    string IP_ADDRESS = 1;
    string GEO_COUNTRY = 2;
  }
}
```

If you have a good eye, you'll notice that the messages `Login` and `Logout` are moved inside the `EventData` which causes the incompatibility.

Another issue from @lianbaghdasaryan is the `EventData` field does not have the oneOf struct. KSQL sees the `oneof` as another struct. So the correct schema definition in KSQL would be:
```
ksql> create stream test(
   CLIENT_ID BIGINT, 
  EVENT_DATE STRUCT<
     ONEOF_0 STRUCT<
         LOGIN STRUCT<IP_ADDRESS STRING, GEO_COUNTRY STRING, METHOD STRING>, 
         LOGOUT STRUCT<IP_ADDRESS STRING, GEO_COUNTRY STRING>
     >
   >, 
  EVENT_TIME TIMESTAMP
) with (kafka_topic='test', value_format='protobuf');
```

The INSERT won't work even with the above schema definition because the incompatibility issue I mentioned previously.

**Comment by spena** [comment] 2022-06-17 20:10
For whoever starts working on this fix. Start with a breakpoint in the `KsqlConnectSerializer.serialize()`.
```
  @Override
  public byte[] serialize(final String topic, final T data) {
    if (data == null) {
      return null;
    }

    try {
      final Object connectRow = translator.toConnectRow(data);
      return converter.fromConnectData(topic, schema, connectRow);
    } catch (final Exception e) {
      throw new SerializationException(
          "Error serializing message to topic: " + topic + ". " + e.getMessage(), e);
    }
  }
```

The `toConnectRow(data)` will throw an exception due to some incorrect names that are tricky to figure out when definition a schema. And when all looks good on the names, then the `fromConnectData(...)` throws an exception because the SR schema is not compatible with the new one.

**Comment by lianbaghdasaryan** [comment] 2022-06-23 11:02
Just for your information, with EVENTTYPE_0  it worked.

CREATE STREAM "client-activity-stream" (
client_id BIGINT,
event_data STRUCT<**EVENTTYPE_0** STRUCT<
login STRUCT<ip_address STRING, geo_country STRING, method STRING>,
logout STRUCT<ip_address STRING, geo_country STRING>>>,
event_time TIMESTAMP)
WITH (KAFKA_TOPIC='client.activity', KEY_FORMAT='KAFKA',  VALUE_FORMAT='PROTOBUF');

**Comment by spena** [comment] 2022-07-28 19:43
I misunderstood this issue and seems it's resolve by the latest comment here (https://github.com/confluentinc/ksql/issues/9194#issuecomment-1164271249) which uses the right STRUCT to deserialize the messages. I'll close this ticket as there's nothing to fix for the CREATE statement.

**Closed by spena** 2022-07-28 19:43 UTC
Labels: bug, P0, streaming-engine
