### ISSUE TITLE
PRINT fails to interpret message, throws com.fasterxml.jackson.databind.node.TextNode error

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#1601] opened 2018-07-19 22:08 UTC
Test data:  (admittedly corrupt, but that's not the point here)

```
kafka-console-producer \
      --broker-list localhost:9092 \
      --topic river_levels3 <<EOF
"northing" : 315350 ,
    "notation" : "3680"
EOF
```

KSQL chokes: 

```
ksql> print 'river_levels3' from beginning;
com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
```

Desired behaviour: Fall back to treating the data as `STRING`

**Comment by agavra** [comment] 2019-10-17 17:26
No longer seems to be an issue in more recent versions of KSQL:
```
ksql> PRINT 'river_levels3' FROM BEGINNING;
Format:STRING
10/17/19 10:25:03 AM PDT , NULL , "northing" : 315350 ,
10/17/19 10:25:03 AM PDT , NULL ,     "notation" : "3680"
^CTopic printing ceased
```
Closing this out, but feel free to re-open if this isn't the expected behavior.

**Closed by agavra** 2019-10-17 17:26 UTC
Labels: bug, user-experience
