### ISSUE TITLE
AVRO Format support in KSQL test runner

### ISSUE THREAD

**Issue by chaitaliSaini** [confluentinc/ksql#8641] opened 2022-01-22 11:01 UTC
Does KSQL test runner support keys in AVRO format. I had the following query in my script:

`
CREATE STREAM stream_name (
    col1 VARCHAR,
    col2 BIGINT,
    ....)
    WITH (KAFKA_TOPIC='topic_name', KEY_FORMAT='AVRO', VALUE_FORMAT='AVRO');
`

But when this query gets executed in KSQL test runner, I get the following error, :
```
 >>>>> Test failed: Schema for message keys on topic 'topic_name' does not exist in the Schema Registry.
Subject: topic_name-key
Possible causes include:
- The topic itself does not exist
        -> Use SHOW TOPICS; to check
- Messages on the topic are not serialized using a format Schema Registry supports
        -> Use PRINT 'topic_name' FROM BEGINNING; to verify
- Messages on the topic have not been serialized using a Confluent Schema Registry supported serializer
        -> See https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html
- The schema is registered on a different instance of the Schema Registry
        -> Use the REST API to list available subjects  https://docs.confluent.io/current/schema-registry/docs/api.html#get--subjects
- You do not have permissions to access the Schema Registry.
        -> See https://docs.confluent.io/current/schema-registry/docs/security.html

```

**Comment by OneCricketeer** [comment] 2022-01-25 17:57
I don't think the problem is ksql supporting or not.

Use the registry rest api to look for the subject mentioned in the error

**Comment by chaitaliSaini** [comment] 2022-01-26 11:56
From what we could understand, ksql test runner does not use the schema registry. In the documentation as well, it is mentioned that ksql test runner does not use a real kafka cluster(https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app/#kafka-cluster). Still, we did try to create the schema for topic_name-key in the registry, but even then got the above error.

**Comment by OneCricketeer** [comment] 2022-01-27 19:47
Ah, I understand what you're trying to do now. I was reading the error too literally... That being said, I assume you'd get the same error with the keys being strings, and the values being avro. 

A registry should be needed because the `KafkaAvroDeserializer` class would be used under the hood, even if it is a mocked instance of one.

**Comment by Gerrrr** [comment] 2022-02-02 10:25
@chaitaliSaini Can you please share a reproducible example? 

I tested an example from https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app with a standalone ksqlDB 0.23.1 and it seems to work.

**Comment by OneCricketeer** [comment] 2022-02-02 14:33
> it seems to work.

That page doesn't use Avro

**Comment by Gerrrr** [comment] 2022-02-02 14:44
> That page doesn't use Avro

I replaced `JSON` with `AVRO` in `value_format` and `key_format`, so that the `statements.sql` looks like this:

```sql
CREATE STREAM orders (ORDERID INT KEY, ORDERUNITS double) WITH (kafka_topic='test_topic', value_format='AVRO', key_format='AVRO');
CREATE STREAM S1 AS SELECT ORDERID, ORDERUNITS, CASE WHEN orderunits < 2.0 THEN 'small' WHEN orderunits < 4.0 THEN 'medium' ELSE 'large' END AS case_result FROM orders EMIT CHANGES;
```

Apologies for not mentioning this explicitly.

**Comment by Gerrrr** [comment] 2022-03-23 12:16
I am going to close this issue. Feel free to re-open it if you find a case where the test runner does not work with Avro.

**Closed by Gerrrr** 2022-03-23 12:16 UTC
Labels: question, ksql-test-runner, streaming-engine
