### ISSUE TITLE
Option to Avro Serialize Message Key when WITH (KEY_FORMAT='Avro')

### ISSUE THREAD

**Issue by deuscapturus** [confluentinc/ksql#5997] opened 2020-08-12 19:26 UTC
**Is your feature request related to a problem? Please describe.**

We have other systems that cannot consume messages from topics created by KSQL because they are expecting the message key to be Avro serialized.

**Describe the solution you'd like**

Add KEY_FORMAT='Avro' option in WITH clause.

**Describe alternatives you've considered**

We have considered re-plublishing the topic with a kafka-to-kafka connector.  But no such connector seems to exist.

**Additional context**
Possibly related to https://github.com/confluentinc/ksql/issues/824

**Comment by big-andy-coates** [comment] 2020-09-30 13:03
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/6226

**Closed by big-andy-coates** 2020-09-30 13:03 UTC
Labels: duplicate, enhancement
