### ISSUE TITLE
Downgrade from ksql 5.4.1 to 5.3.1 results in org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "useOffsetAsQueryID"

### ISSUE THREAD

**Issue by kaushiksrinivas** [confluentinc/ksql#5274] opened 2020-05-05 18:49 UTC
**Describe the bug**
Testing ksql in the k8s environment.
Upto release 5.3.1, upgrades and rollbacks to older versions were tested to be smooth.
Recently upgraded the ksql to 5.4.1 release. Upgrade from 5.3.1 to 5.4.1 works well.
Functional tests done after upgrade, things are OK at this point.

But, when rollback to previous version 5.3.1 using helm rollback results in the ksql pods landing to crash loop back off stage.
Below is the stack trace observed in the pod after failure,
`UTC", "log":{"message":"main - io.confluent.ksql.rest.server.KsqlServerMain - Failed to start KSQL"}}
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition _confluent-ksql-devopsksql_command_topic-0 at offset 5. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "useOffsetAsQueryID" (class io.confluent.ksql.rest.server.computation.Command), not marked as ignorable (3 known properties: "originalProperties", "streamsProperties", "statement"])
at [Source: (byte[])"{"statement":"CREATE STREAM stream1 (sr varchar, title varchar, year bigint, genres varchar) WITH (kafka_topic='movie', value_format='JSON');","useOffsetAsQueryID":true,"streamsProperties":{},"originalProperties":{"ksql.extension.dir":"ext","ksql.streams.cache.max.bytes.buffering":"10000000","ksql.security.extension.class":null,"ksql.transient.prefix":"transient_","ksql.persistence.wrap.single.values":"true","ksql.named.internal.topics":"on","ksql.windowed.session.key.legacy":"false","ksql.strea"[truncated 1802 bytes]; line: 1, column: 2303] (through reference chain: io.confluent.ksql.rest.server.computation.Command["useOffsetAsQueryID"])
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "useOffsetAsQueryID" (class io.confluent.ksql.rest.server.computation.Command), not marked as ignorable (3 known properties: "originalProperties", "streamsProperties", "statement"])
at [Source: (byte[])"{"statement":"CREATE STREAM stream1 (sr varchar, title varchar, year bigint, genres varchar) WITH (kafka_topic='movie', value_format='JSON');","useOffsetAsQueryID":true,"streamsProperties":{},"originalProperties":{"ksql.extension.dir":"ext","ksql.streams.cache.max.bytes.buffering":"10000000","ksql.security.extension.class":null,"ksql.transient.prefix":"transient_","ksql.persistence.wrap.single.values":"true","ksql.named.internal.topics":"on","ksql.windowed.session.key.legacy":"false","ksql.strea"[truncated 1802 bytes]; line: 1, column: 2303] (through reference chain: io.confluent.ksql.rest.server.computation.Command["useOffsetAsQueryID"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1543)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3091)
        at io.confluent.kafka.serializers.KafkaJsonDeserializer.deserialize(KafkaJsonDeserializer.java:75)
        at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1264)
        at org.apache.kafka.clients.consumer.internals.Fetcher.access$3600(Fetcher.java:124)
        at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1488)
        at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1600(Fetcher.java:1328)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:641)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:602)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1263)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1225)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1201)
        at io.confluent.ksql.rest.server.CommandTopic.getRestoreCommands(CommandTopic.java:132)
        at io.confluent.ksql.rest.server.computation.CommandStore.getRestoreCommands(CommandStore.java:159)
        at io.confluent.ksql.rest.server.computation.CommandRunner.processPriorCommands(CommandRunner.java:124)
        at io.confluent.ksql.rest.server.KsqlRestApplication.initialize(KsqlRestApplication.java:305)
        at io.confluent.ksql.rest.server.KsqlRestApplication.startKsql(KsqlRestApplication.java:217)
        at io.confluent.ksql.rest.server.KsqlRestApplication.start(KsqlRestApplication.java:204)
        at io.confluent.ksql.rest.server.KsqlServerMain.tryStartApp(KsqlServerMain.java:74)
        at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:60)
`

Observations:
-If install ksql 5.3.1 and upgrade to 5.4.1 and immediately rollback to 5.3.1 things are OK. That is without creation of any streams things are working OK.
-Once a stream is created in 5.4.1 and even though the stream is deleted before rollback the same error reported above is being faced. i.e. the stream created information is still persisted even after the stream is deleted. i.e 'stream1' in the above test is deleted just before the rollback.

This is observed only during the rollback from 5.4.1 to 5.3.1. 
Just rebooting the ksql pod in 5.4.1 after create&delete events are still working OK.
 

**To Reproduce**
Steps to reproduce the behavior, include:
Install ksql 5.3.1
upgrade to 5.4.1 version
Downgrade to 5.3.1 back. with a stream created in 5.4.1.

**Expected behavior**
downgrade should be successful.

**Actual behaviour**
downgrade results in exceptions. stack trace attached above.

**Additional context**

**Comment by kaushiksrinivas** [comment] 2020-05-05 18:51
@agavra @rodesai 
Any notable/breakable changes which would cause this downgrade from 5.4.1 to 5.3.1 fail ?

Thanks in advance.

**Comment by kaushiksrinivas** [comment] 2020-05-05 19:00
Also created https://github.com/confluentinc/ksql/issues/5275 for tracking the issue where the stream information is still persisted even after the stream is deleted.

**Comment by agavra** [comment] 2020-06-24 16:58
Closing out as duplicate of #5275 - we are not planning on supporting downgrades until a later point in time

**Closed by agavra** 2020-06-24 16:58 UTC
Labels: bug, needs-triage
