### ISSUE TITLE
`group by` clause does not support udf like `timestamptostring`

### ISSUE THREAD

**Issue by kccheung** [confluentinc/ksql#474] opened 2017-11-21 02:11 UTC
Please check the question:

https://stackoverflow.com/questions/47386695/ksql-create-table-and-filter-todays-data-based-on-timestamp/47386835#47386835

`SELECT TIMESTAMPTOSTRING(TS, 'yyyy-MM-dd'), sum(COUNT_VAL) FROM mystream GROUP BY TIMESTAMPTOSTRING(TS, 'yyyy-MM-dd');` is not possible yet. Have to create an intermediate stream by applying the UDF first and then doing the aggregation.

**Comment by apurvam** [comment] 2018-02-14 00:55
This is a duplicate of #519 . we will track the work on this there, so will close this out for now.

**Closed by apurvam** 2018-02-14 00:55 UTC
