### ISSUE TITLE
GROUP BY should work with Scalar functions

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#519] opened 2017-12-12 00:30 UTC
The following query should work:
```sql
SELECT
  TIMESTAMPTOSTRING(ROWTIME, 'yyyy'),
  sum(1)
FROM clickstream
WINDOW TUMBLING (SIZE 5 SECONDS)
GROUP BY TIMESTAMPTOSTRING(ROWTIME, 'yyyy');
```

Currently, it fails with:
```
null
Query terminated
```

**Comment by hjafarpour** [comment] 2017-12-12 06:41
@tomlinsonr currently, `GROUP BY` only accepts column names.

**Comment by miguno** [comment] 2017-12-13 09:31
I got additional feedback offline:

> The use case here is that we want to see the event count in say, the last 30 seconds. Grouping by any column means we will then need to re-aggregate to get the total count. Plus for the user, it is not clear which column they need to re-aggregate on.
>
> Please permit aggregates without group bys, or permit group by on a literal string (which also doesn't work, or I could not figure out how to get working)

**Comment by tomlinsonr** [comment] 2017-12-13 18:31
To clarify, we would like group by to work with scalar functions as well, essentially we are asking this question in the context of a BI tool permitting business users to perform ad-hoc analysis on kafka streams and tables.

**Comment by tomlinsonr** [comment] 2018-01-31 15:14
Any update on this one guys? This is a very common use case in BI. User will create a derived field (e.g. foo = TIMESTAMPTOSTRING(ROWTIME, 'yyyy') on the fly. They will then use this is an analytic SQL statement that will GROUP BY foo. We want to enable this without materializing the function in a stream / table first.

@miguno - any way to get this moving?

**Comment by bluemonk3y** [comment] 2018-01-31 15:37
@apurvam @hjafarpour

**Comment by tomlinsonr** [comment] 2018-03-21 14:21
Time to bump this again.... cannot move forward with our KSQL project without this enhancement. This will also be the case for any BI company building on KSQL.

Can I please get a call on if this is a priority and associated timeline?

**Comment by big-andy-coates** [comment] 2018-10-22 14:20
Working on a a fix...  duplicate of #1849?

**Closed** 2018-10-30 01:32 UTC
Labels: enhancement

**Comment by big-andy-coates** [comment] 2018-11-21 12:08
Fixed. You can now group by scalar functions. You can also, optionally, use the _exact_ same clause in the select statement. So these are now supported:

```sql
-- with the group by in the select statement:
SELECT
  TIMESTAMPTOSTRING(ROWTIME, 'yyyy'),
  sum(1)
FROM clickstream
WINDOW TUMBLING (SIZE 5 SECONDS)
GROUP BY TIMESTAMPTOSTRING(ROWTIME, 'yyyy');

-- without the group by in the select statement:
SELECT
  COUNT(*)
FROM clickstream
WINDOW TUMBLING (SIZE 5 SECONDS)
GROUP BY TIMESTAMPTOSTRING(ROWTIME, 'yyyy');
```
