### ISSUE TITLE
Foreign key join with Schema Registry enabled key format on the right-side table may miss results

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#8528] opened 2021-12-16 02:30 UTC
**Describe the bug**

When performing a foreign key join, if the table on the right side (the primary key table) uses a Schema-Registry-enabled key format (e.g., Avro or Protobuf) with a custom schema, i.e., not a schema produced by ksqlDB, then the foreign key join may miss results. This can happen because when the foreign key is extracted from the left table, it is serialized using ksql's schema, which may have a different Schema Registry schema ID than the custom schema used for the right table's key. If this is the case, then the serialized bytes will not match even if the values are logically the same, causing missed join results.

**To Reproduce**

On any version of ksqlDB since foreign key joins were introduced, issue an FK join with custom Avro schema for the right table's key, and data to match on the left side.

**Expected behavior**

Join results are present.

**Actual behaviour**

Join results may be missing.

**Additional context**

We don't have the analogous problem with SR-enabled key formats for non-FK-joins since ksql has logic to detect the join key format and automatically repartition to ensure matching schema IDs if an SR-enabled key format is detected. We also have test coverage to ensure this.

For FK joins, we don’t have any logic to determine key formats since we don’t perform any copartitioning checks for FK joins, since FK join sources don’t need to be copartitioned. When introducing the feature, we missed the edge case where the right key format is SR-enabled and a non-ksql schema is being used. We have [FK join test coverage](https://github.com/confluentinc/ksql/blob/97fa117ec33d42e145518568cf4a441f0bd8cb33/ksqldb-functional-tests/src/test/resources/query-validation-tests/fk-join.json#L639) for Avro keys on the left source only, which is why this edge case was missed. 

To fix this bug, ksql should handle the case where an SR-enabled key format is used on the RHS of an FK join by automatically repartitioning to use the ksql schema, as we do for non-FK-joins.

**Comment by mjsax** [comment] 2022-03-08 17:44
Kafka Streams by default uses the right table key-serializer to write into the subscription topic, and the left table key-serializer to write into the response topic. This ensure co-partitioning of the subscription data with the right table, and co-partitioning of the response data with the left table.

If AVRO is used, we need to ensure that the schema-id use is the same (ie, when the right table key schema is re-registered for the subscription topic it might use the same schema-id as the right table key). Similar for the response topic.

If the schema-id would change, co-partitioning might break.

**Comment by Gerrrr** [comment] 2022-03-16 19:24
As a status update, I found 2 ways to make make foreign key joins miss entries.

The first way is very much inspired by @vcrfxia 's comment - on the RHS we use a table with custom AVRO schema.

Key:

```json
{
  "type": "record",
  "namespace": "com.example",
  "name": "CustomerId",
  "version": "2",
  "fields": [
    { "name": "id", "type": "long", "doc": "Customer ID" }
  ]
}
```

Value:

```json
{
     "type": "record",
     "namespace": "com.example",
     "name": "Customer",
     "version": "2",
     "fields": [
       { "name": "first_name", "type": "string", "doc": "First Name of Customer" },
       { "name": "last_name", "type": "string", "doc": "Last Name of Customer" },
       { "name": "age", "type": "int", "doc": "Age at the time of registration" },
       { "name": "height", "type": "float", "doc": "Height at the time of registration in cm" },
       { "name": "weight", "type": "float", "doc": "Weight at the time of registration in kg" },
       { "name": "phone_number", "type": ["null", "string"], "default": null, "doc": "optional phone number"},
       { "name": "email", "type": "string", "default": "missing@example.com", "doc": "email address"}
     ]
}
```

After registering the schema, we create tables, insert records, and then create a FK join:

```sql
CREATE TABLE bar (id BIGINT PRIMARY KEY, name VARCHAR, fk STRUCT<id BIGINT>) WITH (kafka_topic='bar', format='AVRO', partitions=128);
CREATE TABLE customerAvro WITH (kafka_topic='customer-avro', format='AVRO');
CREATE TABLE output AS SELECT * FROM bar INNER JOIN customerAvro ON customerAvro.rowkey = bar.fk;
```

The output will miss records. As Victoria suggested, this bug can be solved by repartitioning RHS of the FK join if the schema format uses schema registry. However, there is the second issue - FK join misses records if the table on the LHS has a compound primary key. Moreover, it reproduces even with the JSON type:

```sql
CREATE TABLE bar (id BIGINT PRIMARY KEY, name VARCHAR PRIMARY KEY, fk BIGINT) WITH (kafka_topic='bar', format='JSON', partitions=128);
CREATE TABLE foo (rowkey BIGINT PRIMARY KEY, my_field3 VARCHAR) with (KAFKA_TOPIC='foo', FORMAT='JSON', partitions=128);
CREATE TABLE output AS SELECT * FROM bar INNER JOIN foo5 on foo5.rowkey = bar5.fk;
```

 At this point I am trying to understand what is the root cause. Given that the fix-by-repartition for the first bug introduces significant performance hit, I would prefer to delay opening a patch with it in case I find a way to fix both issues at the same time without repartition.

/cc @mjsax

**Comment by suhas-satish** [comment] 2022-04-01 22:36
@Gerrrr , is the PR for this merged? If so, can this be closed?

**Comment by Gerrrr** [comment] 2022-04-03 10:42
No, 2 PRs that solve this issue are still in review - https://github.com/confluentinc/ksql/pull/8926 and https://github.com/apache/kafka/pull/11945.

**Comment by mjsax** [comment] 2022-04-19 15:39
The AK PR is merged -- Just discussed with @Gerrrr that we should keep this ticket open until we add an end-to-end test to ksqlDB to verifies that both PRs together fix this issue.

**Comment by mjsax** [comment] 2022-05-14 00:22
System tests added via https://github.com/apache/kafka/pull/12122.

**Closed by mjsax** 2022-05-14 00:22 UTC
Labels: bug, P0, streaming-engine
