### ISSUE TITLE
Unable to describe latest_by_offset function

### ISSUE THREAD

**Issue by ayushkhandelwal317** [confluentinc/ksql#9129] opened 2022-05-18 17:31 UTC
**KSQLDB Image**: confluentinc/ksqldb-server:0.23.1
Getting error while describing latest_by_offset. I am able to describe all other in-built functions

**To Reproduce**
Steps to reproduce the behavior, follow steps:
1. Launch KSQLDB Server
2. Connect to KSQLDB server via KSQL CLI
3. Use Command - `desribe function LATEST_BY_OFFSET;`

**Expected behavior**
Should return detailed information about latest_by_offset like method signature, function type etc.

**Actual behaviour**
Currently describe function for latest_by_offset is throwing error.
*Input:*
`ksql> describe function LATEST_BY_OFFSET;`
*Output:*
`Failed to invoke UDAF factory method
Caused by: wrong number of arguments`

**Comment by jnh5y** [comment] 2022-05-20 21:53
Thanks for reporting this issue!  It is a duplicate of https://github.com/confluentinc/ksql/issues/7183.

As some good news, the docs for `LATEST_BY_OFFSET` are here: https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/aggregate-functions/#latest_by_offset

**Comment by suhas-satish** [comment] 2022-05-24 16:29
closing as a duplicate

**Closed** 2022-05-24 16:29 UTC
Labels: bug, needs-triage, streaming-engine
