### ISSUE TITLE
Implement asynchronous/multi-threaded handling of pull queries

### ISSUE THREAD

**Issue by vinothchandar** [confluentinc/ksql#3649] opened 2019-10-22 22:35 UTC

**Comment by apurvam** [comment] 2019-10-23 05:42
related to #3548

**Comment by big-andy-coates** [comment] 2019-10-23 16:20
Pull queries are handled by the rest api's request threads, so I believe it is already multi-threaded.

We should confirm, but can then close this issue.

**Comment by vinothchandar** [comment] 2019-10-23 16:38
I think still `proxyTo` is current synchronously blocking for the remote read to return. Thats another angle to consider. We should not ideally blocking these request threads. 

lets confirm. @vpapavas  is going to drive this actually.

**Comment by big-andy-coates** [comment] 2019-10-23 16:57
Yep, the `proxyTo` call is definitely blocking. I think we're looking at a fairly sizable refactor of the rest api for it to be anything but.  Certainly not something possible to fix any time soon.

**Comment by vinothchandar** [comment] 2019-10-23 18:06
There are few threads in play. My guess is still work queues up. 

<img width="1079" alt="Screen Shot 2019-10-23 at 10 57 56 AM" src="https://user-images.githubusercontent.com/1179324/67420785-1f3b9f00-f584-11e9-9611-6779303ba856.png">

<img width="557" alt="Screen Shot 2019-10-23 at 10 57 29 AM" src="https://user-images.githubusercontent.com/1179324/67420786-1f3b9f00-f584-11e9-8a42-2d5faf561d7c.png">

On release,  yeah we may not get time to crack this before that. Nonetheless, if we can reduce the baseline to under 1ms or something, it should alleviate this. I will continue to dig on the how the threading model works and if there are opportunities there.

**Comment by big-andy-coates** [comment] 2019-11-25 18:57
Closing this as a duplicate of #3816

**Closed by big-andy-coates** 2019-11-25 18:57 UTC
Labels: enhancement
