### ISSUE TITLE
Json deserializer issue in stream when String contains non-ascii/binary 

### ISSUE THREAD

**Issue by DataBrenes** [confluentinc/ksql#5070] opened 2020-04-15 17:24 UTC
**Describe the bug**
***KsqlVersion*** : ```5.3.1```
JSON data with VARCHAR(STRING) value "ï½�ã��ï½�ï½�ï½�ï½" produces error:

``` 
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value

(through reference chain: io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["columns"]->java.util.ArrayList[10])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
        value
```
The resulting error terminates the query and nothing is logged to KSQL_PROCESSING_LOG. 

**To Reproduce**
Steps to reproduce the behavior, include:

|CREATE STREAM |
| ----- | 
```
create stream ksqlerror (
     Type VARCHAR, 
     PostID INTEGER, 
     MatchedTerms ARRAY<STRING>,  
     PostTitle VARCHAR, 
     PostBody VARCHAR, 
     PostRating DOUBLE, 
     PatientCase BOOLEAN, 
     CommentNum VARCHAR, 
     Comment VARCHAR, 
     HelpfulCount VARCHAR, 
     DateTime VARCHAR, 
     Date VARCHAR, 
     AuthorID VARCHAR, 
     Specialty VARCHAR, 
     Country VARCHAR, 
     Zipcode INTEGER
     )     
     WITH 
     (
        KAFKA_TOPIC='ksqlerror',
        VALUE_FORMAT='JSON'
);
```
|Sampe Json| 
|-----|
```
{"Type": "Comment", "PostID": 12345, "MatchedTerms": [], "PostTitle": null, "PostBody": null, "PostRating": null, "PatientCase": null, "CommentNum": 123, "Comment": "\u00ef\u00bd\u0089\u00e3\u0080\u0080\u00ef\u00bd\u0088\u00ef\u00bd\u0081\u00ef\u00bd\u0096\u00ef\u00bd\u0085\u00e3\u0080\u0080\u00ef\u00bd\u008e\u00ef\u00bd\u008f\u00e3\u0080\u0080\u00ef\u00bd\u0089\u00ef\u00bd\u0084\u00ef\u00bd\u0085\u00ef\u00bd\u0081\u00e3\u0080\u0080\u00ef\u00bd\u0097\u00ef\u00bd\u0088\u00ef\u00bd\u0099\u00e3\u0080\u0080\u00ef\u00bd\u008f\u00ef\u00bd\u0092\u00e3\u0080\u0080\u00ef\u00bd\u0088\u00ef\u00bd\u008f\u00ef\u00bd\u0097\u00e3\u0080\u0080\u00ef\u00bd\u008d\u00ef\u00bd\u0099\u00e3\u0080\u0080\u00ef\u00bd\u0083\u00ef\u00bd\u008f\u00ef\u00bd\u008d\u00ef\u00bd\u0090\u00ef\u00bd\u0095\u00ef\u00bd\u0094\u00ef\u00bd\u0085\u00ef\u00bd\u0092\u00e3\u0080\u0080\u00ef\u00bd\u0083\u00ef\u00bd\u0088\u00ef\u00bd\u0081\u00ef\u00bd\u008e\u00ef\u00bd\u0087\u00ef\u00bd\u0085\u00ef\u00bd\u0084\u00e3\u0080\u0080\u00ef\u00bd\u0094\u00ef\u00bd\u0088\u00ef\u00bd\u0085\u00e3\u0080\u0080\u00ef\u00bd\u0086\u00ef\u00bd\u008f\u00ef\u00bd\u008e\u00ef\u00bd\u0094\u00ef\u00bc\u008e", "HelpfulCount": 0, "DateTime": "2000-01-01T09:00:00Z", "Date": "2000-01-01", "AuthorID": "dfafdasfadfas78fdf", "Specialty": "Fake", "Country": "AB", "Zipcode": "12345"}
```

| Command| 
| ---- | 
| ``` /kafka-console-producer.sh --broker-list <ip>:9092 --topic "ksqlerror" --property value.serializer=custom.class.serialization.JsonSerializer < failed_example.json ``` |

| Result | 
| ----- | 
```
ksql> select * from KSQLERROR;
Query terminated
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
 at [Source: (String)"{"row":{"columns":[104949399309,null,"Comment",12345,[],null,null,null,null,"123","ï½�ã��ï½�ï½�ï½�ï½"; line: 1, column: 84] (through reference chain: io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["columns"]->java.util.ArrayList[10])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
        value
 at [Source:
        (String)"{"row":{"columns":[104949399309,null,"Comment",12345,[],null,null,null
        ,null,"123","ï½�ã��ï½�ï½�ï½�ï½"; line: 1, column: 84] (through reference chain:
        io.confluent.ksql.rest.entity.StreamedRow["row"]->io.confluent.ksql.GenericRow["
        columns"]->java.util.ArrayList[10])
Caused by: Unexpected end-of-input: was expecting closing quote for a string
        value
 at [Source:
        (String)"{"row":{"columns":[1586969740091,null,"Comment",12345,[],null,null,null
        ,null,"123","ï½�ã��ï½�ï½�ï½�ï½"; line: 1, column: 203]
ksql>
```

**Expected behavior**
The expectation is that the values would map as string representation. 
And if failure, the above error would show in the KSQL_PROCESSING_LOG.

**Actual behaviour**
Query terminates, record fails, and nothing is pushed to KSQL_PROCESSING_LOG like other de-serializer errors.

**Comment by DataBrenes** [comment] 2020-04-24 12:52
We are using Apache Nifi for our data pipelines. Incorporating a ReplaceText processor for the \u0085 appears to have resolved this issue.

**Comment by stevenpyzhang** [comment] 2020-04-27 20:45
This looks to be fixed on master. I follow the instructions above
```
ksql> select * from KSQLERROR emit changes limit 1;

+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
|ROWTIME|ROWKEY |TYPE   |POSTID |MATCHED|POSTTIT|POSTBOD|POSTRAT|PATIENT|COMMENT|COMMENT|HELPFUL|DATETIM|DATE   |AUTHORI|SPECIAL|COUNTRY|ZIPCODE|
|       |       |       |       |TERMS  |LE     |Y      |ING    |CASE   |NUM    |       |COUNT  |E      |       |D      |TY     |       |       |
+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
|1588020|null   |Comment|12345  |[]     |null   |null   |null   |null   |123    |ï½ãï|0      |2000-01|2000-01|dfafdas|Fake   |AB     |12345  |
|335857 |       |       |       |       |       |       |       |       |       |½ï½ï½|       |-01T09:|-01    |fadfas7|       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ã|       |00:00Z |       |8fdf   |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½ã|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ãï½ï|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |½ï½ã|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ãï½ï|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |½ï½ã|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ãï½ï|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |½ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½ã|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½ï|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |½ãï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ãï½ï|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |½ï½ï½|       |       |       |       |       |       |       |
|       |       |       |       |       |       |       |       |       |       |ï¼   |       |       |       |       |       |       |       |
Limit Reached
Query terminated
```

**Comment by apurvam** [comment] 2020-05-13 17:12
Closing Since it's not reproducible on master.

**Closed by apurvam** 2020-05-13 17:12 UTC
Labels: blocker, bug, needs-triage
