### ISSUE TITLE
custom serializers and deserializers support

### ISSUE THREAD

**Issue by rtrg** [confluentinc/ksql#5966] opened 2020-08-07 11:58 UTC
Is it possible to use custom serializers and deserializers with ksql apart from [supported ones](https://docs.ksqldb.io/en/latest/developer-guide/serialization/#serialization-formats)? similar to how kafka streams supports [custom serdes](https://kafka.apache.org/10/documentation/streams/developer-guide/datatypes#implementing-custom-serdes)

**Comment by agavra** [comment] 2020-08-07 15:56
Thanks for submitting the ticket @rtrg - this is something we have our eye on but not currently on the radar. Closing this ticket as a duplicate of https://github.com/confluentinc/ksql/issues/1057 - feel free to +1 that issue if this is something you'd like

**Closed by agavra** 2020-08-07 15:56 UTC
Labels: needs-triage, question
