### ISSUE TITLE
Materialized views are lost, when ksqldb restart

### ISSUE THREAD

**Issue by mogui** [confluentinc/ksql#7503] opened 2021-05-12 10:13 UTC
I need to have a queryable Table, so I create a Materialized view with `CREATE  TABLE AS SELECT`.
everything works fine, but if ksqldb is restarted, The table created this way persist but is no more queryable.

It is an intended thing? Am I missing something or doing something wrong?
What I saw is that to maintain the table a persistent query is issued and a consumer with a query id is started, when ksqldb is restarted this consumer no longer is active.

I am using ksqldb  docker container.

**Comment by mjsax** [comment] 2021-05-14 16:41
What version do you use? Would like to see if I can reproduce the issue. Atm, it sounds like a potential bug.

**Comment by mogui** [comment] 2021-05-17 07:23
Hi @mjsax I am using this tag `confluentinc/ksqldb-server:0.17.0`, and run it with this configuration.
I alsoconfigured the volume cause i thought that was the problem but the it doesn't resolve the issue.


```
ksqldb:
    image: confluentinc/ksqldb-server:0.17.0
    hostname: ksqldb
    container_name: ksqldb
    links:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_QUERY_PULL_TABLE_SCAN_ENABLED: "true"
      KSQL_KSQL_STREAMS_STATE_DIR: "/tmp/kafka-streams"
    volumes:
      - ./data/streams:/tmp/kafka-streams
```

**Comment by mikeplavsky** [comment] 2021-08-02 10:46
I have the same problem: the table isn't queryable after ksqldb is restarted. Using confluentinc/ksqldb-server:0.19. Also in logs after restarting ksqldb says: INFO Restarting 0 queries.

**Comment by colebaileygit** [comment] 2021-08-31 14:59
I seem to also face this issue, will have to test if removing `IF NOT EXISTS` helps but that also requires more careful query and migration planning in my setup. Thanks for the tip @mikeplavsky

**Comment by mikeplavsky** [comment] 2021-09-27 13:52
Got thus problem again for 0.21 but for `CREATE STREAM AS SELECT`. 

The observation is when everything is running there is a legitimate application.id in ksqldb logs: 

```
[2021-09-27 11:36:05,144] INFO StreamsConfig values:
        acceptable.recovery.lag = 10000
        application.id = _confluent-ksql-kafkaquery_....
``` 

But if ksqldb restarted and such command is executed through REST API: 
`CREATE SREAM IF NOT EXISTS AS SELECT` 

Then there is no `application.id` anymore in logs. 

Interestingly enough for `CREATE STREAM AS SELECT` the documentation does not mention IF NOT EXISTS at all. 
https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/create-stream-as-select/ REST API does not complain though.

**Comment by mjsax** [comment] 2022-01-25 07:50
Ticket #8173 is closed. Can you try out 0.23 release? (Closing for now -- feel free to reopen if the issue is still there.)

**Closed by mjsax** 2022-01-25 07:50 UTC
Labels: question
