### ISSUE TITLE
How to reduce the number of topic and support thousands of stream joins at the same time

### ISSUE THREAD

**Issue by wjphero** [confluentinc/ksql#1496] opened 2018-06-26 04:07 UTC
hi
         Our business need us to join thousands of streams or tables into hundreds of streams and some experts said reducing the num of kafka topic would improve kafka performance. According to my experience, in ksql system every new join will create two new topic, thousands of join will create thousands of topic, so many topics will reduce performance. So how to reduce the num of the topic in the KAFKA-KSQL Cluster?

**Comment by hjafarpour** [comment] 2018-07-06 21:08
@wjphero can you provide more context on your use case? What type of data do you have in your streams and tables and why do you need to have thousands of them?

**Comment by b-slim** [comment] 2018-10-01 17:21
in nutshell, i have one stream of events that need to be joined against dozen of dimension tables using different keys or multi-way join, also you might  have dozen of other stream stream joins as one atomic transformation. Current implementation of Ksql will lead to a huge write amplification by  copying the original stream for every join, plus if you want an exactly once semantic every join will be wrapped within one transaction block.  In an ideal world this one transformation can be done without dozen of copies or transaction blocks. The question is KSQL gearing to tackle this issue or not.

**Comment by miguno** [comment] 2018-10-02 18:45
@b-slim: To confirm, is this ticket here a duplicate of or subsumed by [KSQL should support multi-way joins #1532](https://github.com/confluentinc/ksql/issues/1532)?

**Comment by b-slim** [comment] 2018-10-02 19:06
@miguno the ticket you are mentioned will be encapsulated by this one.  KSQL should support multi-way joins #1532 will be step one. Step 2 is is more about the write amplification, IMO is not scalable to rekey the original topic for every join key/group key.

**Closed** 2019-08-13 11:24 UTC
Labels: question
