### ISSUE TITLE
KSQL How I pivot a array struck to a line?  

### ISSUE THREAD

**Issue by Gabriel-Pellegrini** [confluentinc/ksql#2373] opened 2019-01-21 12:10 UTC
Hello, I'm Gabriel, and I'm trying to pivot a stream data from an array struct  data.
I've the following schema from my stream.

```
ksql> describe FEATURES;

Name                 : FEATURES
 Field     | Type                                                       
------------------------------------------------------------------------
 ROWTIME   | BIGINT           (system)                                  
 ROWKEY    | VARCHAR(STRING)  (system)                                  
 FEATUREID | VARCHAR(STRING)                                            
 LABELS    | ARRAY<STRUCT<LABEL VARCHAR(STRING), LANG VARCHAR(STRING)>> 
-----------------------------------------------------------------------
```
When I query the stream it's working fine
```
 ksql> Select * from features;
1548075987551 | "1" | 09344 | [{LABEL=Contains wood, LANG=en}, {LABEL=Contem madeira, LANG=pt}]
 ```

But I need to get the data split into separated lines, as the following:
``` 
ksql> select labels[0]->label,labels[0]->lang from features;
Contains wood | en  
ksql> select labels[1]->label,labels[1]->lang from features;
Contem madeira | pt
 ```

Is there a way to query all information in a separated line without specifying the array index?
for example
```
line 1 = featureId| label1 | lang1 
line 2 = featureId | label2 | lang2 ....
```

Thanks for any help.

**Comment by Manishfalcon** [comment] 2019-02-11 18:19
Can anyone interested to address to question.

**Comment by Manishfalcon** [comment] 2019-02-11 18:21
@gabriel - you found any solution related to above question?

**Comment by Gabriel-Pellegrini** [comment] 2019-02-15 11:53
Hello @Manishfalcon, I did not find a solution to this problem yet, It's seems that KSQL is not able to do that alone as you can see on these links.
#527 
[Slack](https://confluentcommunity.slack.com/archives/C48AHTCUQ/p1548086390219900).

**Comment by big-andy-coates** [comment] 2019-03-21 15:46
Hi @Gabriel-Pellegrini, yeah you are right - you need UDTF support in KSQL, which we don't have as yet.  Can you add a +1 vote to #1830 please?

**Comment by Gabriel-Pellegrini** [comment] 2019-03-21 18:44
Hello @big-andy-coates, It's done, I hope we can find a way to implement it soon. 
It'll help us a lot.

**Comment by Gabriel-Pellegrini** [comment] 2019-03-21 18:46
Hello @big-andy-coates, It's done, I hope we can find a way to implement it soon.
It'll help us a lot.

**Comment by big-andy-coates** [comment] 2019-09-24 13:11
We're looking into this!  Closing this issue as a duplicate of https://github.com/confluentinc/ksql/issues/527

**Closed by big-andy-coates** 2019-09-24 13:11 UTC
