### ISSUE TITLE
Deserialisation of AVRO record containing empty decimal value fails

### ISSUE THREAD

**Issue by michalstutzmann** [confluentinc/ksql#9670] opened 2022-10-26 13:00 UTC
**Describe the bug**
Deserialisation of an AVRO record containing an empty decimal (bytes) value results in an error.

**To Reproduce**
ksqlDB version: 0.28.2

AVRO schema for the record's value:
```json
{
  "type": "record",
  "name": "Test",
  "namespace": "test",
  "fields": [
    {
      "name": "TEST_COLUMN_STRING",
      "type": "string"
    },
    {
      "name": "TEST_COLUMN_DECIMAL",
      "type": {
        "type": "bytes",
        "logicalType": "decimal"
      }
    }
  ]
}
```

Input:
```json
{
  "inputs": [
    {
      "topic": "test-input-topic",
      "timestamp": 0,
      "key": null,
      "value": {
        "TEST_COLUMN_STRING": "test",
        "TEST_COLUMN_DECIMAL": ""
      }
    }
  ]
}
```

SQL:

```sql
CREATE SOURCE STREAM TEST_INPUT_STREAM (
  TEST_COLUMN_STRING VARCHAR
)
WITH (
  KAFKA_TOPIC = 'test-input-topic',
  VALUE_FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
);

CREATE STREAM TEST_OUTPUT_STREAM WITH (
  KAFKA_TOPIC = 'test-output-topic',
  VALUE_FORMAT = 'AVRO',
  PARTITIONS = 1,
  REPLICAS = 1
)
AS
SELECT TEST_COLUMN_STRING
FROM TEST_INPUT_STREAM
EMIT CHANGES;
```

**Expected behavior**

Expected output:
```
{
  "outputs": [
    {
      "topic": "test-output-topic",
      "timestamp": 0,
      "key": null,
      "value": {
        "TEST_COLUMN_STRING": {
          "string": "test"
        }
      }
    }
  ]
}
```

**Actual behaviour**
Record not processed, the following error written to the log:
```
ERROR {"type":0,"deserializationError":{"target":"value","errorMessage":"Error deserializing message from topic: test-input-topic","recordB64":null,"cause":["Zero length BigInteger"],"topic":"test-input-topic"},"recordProcessingError":null,"productionError":null,"serializationError":null,"kafkaStreamsThreadError":null} (processing.CSAS_TEST_OUTPUT_STREAM_933.KsqlTopic.Source.deserializer)
```

EDIT: ksqlDB version 0.26.0 changed to 0.28.2

**Comment by suhas-satish** [comment] 2022-10-31 21:59
@michalstutzmann , lots of bug fixes have gone into avro, protobuf and json in ksqlDB 0.27 and ksqlDB 0.28. Can you try  on ksqlDB 0.28 if this issue is reproducible? Thanks. 

Also, are you running with schema registry enabled or disabled ?

**Comment by michalstutzmann** [comment] 2022-11-01 11:41
@suhas-satish now tested also on the latest version 0.28.2. Same error. 

We were running with Schema Registry enabled.

**Comment by michalstutzmann** [comment] 2022-11-09 18:31
@mjsax `TEST_COLUMN_DECIMAL` is the input schema definition; or maybe you meant the input `STREAM` column definition? Have tested that also with the same result.

Have performed also 2 additional tests:

1. Using `PRINT` statement, output is OK, the record is deserialised successfully:

SQL:
```sql
PRINT 'test-input-topic' FROM BEGINNING;
```

Output:
```json
{
  "record": "rowtime: 2022/11/09 18:21:53.152 Z, key: null, value: {\"TEST_COLUMN_STRING\": \"test\", \"TEST_COLUMN_DECIMAL\": \"\"}, partition: 0"
}
```

2. A separate Kafka Streams app that I currently use for preprocessing as a workaround (removal of the column in question). Also no issues.

I conclude from the above that the problem is not with the AVRO deserialisation but somewhere downstream from there.

**Comment by mjsax** [comment] 2022-11-18 06:16
Thanks for the details. I am not sure right now. The error message contains `"cause":["Zero length BigInteger"]` -- Given that you declare the type of the column as `byte / Decimal` I am confused.

When you did add `TEST_COLUMN_DECIMAL` to the schema definition of `TEST_INPUT_STREAM`, what data type did you declare? Can you maybe create the input stream without explicit schema definition and let ksqlDB inver the schema from the AVRO definition?

**Comment by michalstutzmann** [comment] 2022-11-22 13:57
The data type for the column was `DECIMAL(19, 0)`. Have created the stream as you suggested - the same error.

I think I might have tracked the error (without proper debugging) to here:  https://github.com/confluentinc/kafka/blob/v7.3.0/connect/api/src/main/java/org/apache/kafka/connect/data/Decimal.java#L79

```java
...
public static BigDecimal toLogical(Schema schema, byte[] value) {
        return new BigDecimal(new BigInteger(value), scale(schema));
}
...
```

```java
  ...
  public BigInteger(byte[] val, int off, int len) {
      if (val.length == 0) {
          throw new NumberFormatException("Zero length BigInteger");
      }
  ...
```

As you can see a `BigInteger` is created from (in our case) an empty byte array, resulting in the error we are getting. Is it a bug in Kafka Connect?

**Comment by mjsax** [comment] 2022-12-28 20:29
Seem it's indeed the root cause -- I am not sure if it's a bug, or your data is considered corrupted. Maybe @C0urante knows? In doubt, please follow up on the Kafka dev mailing list about it. I am closing this ticket now as it's nothing we can fix on our side. Of course, feel free to follow up on this ticket.

**Closed by mjsax** 2022-12-28 20:29 UTC
Labels: bug, streaming-engine

**Comment by mjsax** [comment] 2022-12-28 20:36
I did follow up with some Connect people, and they told me that it's not a bug in Connect, but your data is considered corrupted. -- `""` resulting in zero-length byte-array is just not valid binary data.
