### ISSUE TITLE
Disable automatic registration of Avro schemas

### ISSUE THREAD

**Issue by Ravirael** [confluentinc/ksql#5822] opened 2020-07-14 08:32 UTC
I'm running KSQLDB Server as a Docker container (image `confluentinc/ksqldb-server:0.10.0`) in headless mode and I'm using schema registry and Avro as a value format. 

KSQLDB Server automatically registers Avro schemas for its streams / table. I do not want that, it overrides my existing schemas. Can I somehow prevent that behavior?

In logs, I can see things like:
```
[2020-07-14 07:57:41,802] INFO AvroConverterConfig values: 
    auto.register.schemas = true
   ....

[2020-07-14 07:57:41,803] INFO KafkaAvroSerializerConfig values: 
    auto.register.schemas = true
    ...

[2020-07-14 07:57:41,803] INFO KafkaAvroDeserializerConfig values: 
    auto.register.schemas = true
    ...
```

I believe these are the config values I'd like to set to `false`.

**Comment by agavra** [comment] 2020-07-14 15:27
Hello @Ravirael - I believe what you're running into is #5553 which will be fixed in 0.10.1, which is coming out soon (hopefully within a few weeks). In the meantime as a workaround, I believe manually deleting the schema should not cause any problems. 

Also, to clarify, ksql will always register schemas for topics that it produces to - that's by design, but for simple `CREATE STREAM` and `CREATE TABLE` statements, this will no longer happen.

I'm going to close this out as a duplicate, but let me know if you have any other questions.

**Closed by agavra** 2020-07-14 15:27 UTC
Labels: needs-triage, question
