### ISSUE TITLE
Need to Return Multiple Aggregates in a Single SQL Statement

### ISSUE THREAD

**Issue by tomlinsonr** [confluentinc/ksql#1118] opened 2018-04-04 21:18 UTC
Need to generate a scatter/bubble chart in a BI tool. Need to run the following SQL:

```sql
SELECT SUM(foo), SUM(bar), xyz FROM table_name GROUP BY xyz
```

KSQL returns the error message:
```
Group by elements should match the SELECT expressions.
```

This is a very common BI query.

**Comment by agavra** [comment] 2019-10-16 18:36
This has been fixed in more recent versions of KSQL! Feel free to re-open if the problem is not addressed.
```
ksql> INSERT INTO s (foo, bar, xyz) VALUES (1, 2, 'a');
ksql> INSERT INTO s (foo, bar, xyz) VALUES (1, 2, 'a');
ksql> INSERT INTO s (foo, bar, xyz) VALUES (1, 2, 'a');
ksql> SELECT SUM(foo), SUM(bar), xyz FROM s GROUP BY XYZ EMIT CHANGES;
+------------------------------+------------------------------+------------------------------+
|KSQL_COL_0                    |KSQL_COL_1                    |XYZ                           |
+------------------------------+------------------------------+------------------------------+
|3                             |6                             |a                             |
```

**Closed by agavra** 2019-10-16 18:36 UTC
Labels: bug
