### ISSUE TITLE
Question > CREATE TABLE SELECT AS on single table produces tombstones records

### ISSUE THREAD

**Issue by Musikolo** [confluentinc/ksql#5908] opened 2020-07-30 00:39 UTC
Hi,

I've noticed that when I create the following table, I get tombstone records in my topic:

```sql
CREATE TABLE FEW_FIELDS_TABLE 
WITH (kafka_topic= 'my.input.topic', value_format= 'whatever') AS
SELECT field1, field2, field3
FROM ALL_FIELDS_TABLE
WHERE ROWTIME > 1594785600000 -- Midnight 7/15 EST
EMIT CHANGES;
```

More specifically, I've noticed that the tombstone records I get in my topic belong to the ones not meeting the filtering criteria. I'm aware of certain scenarios in which this is expected (#1382 & #3616), but I don't think it makes sense for this scenario in which we don't have any join or aggregation, just pulling data from a simple single table.

Questions:
- Is this a known behavior for this scenario (single table with no joins and aggregations)?
- Is there a simple way and get rid of tombstone records with a KSQL script?

Thank you!

**Comment by mikebin** [comment] 2020-08-04 16:12
Related: https://github.com/confluentinc/ksql/issues/3558

**Comment by stevenpyzhang** [comment] 2020-08-04 17:44
I've verified that this behavior still exists in master as of today. The issue linked @mikebin seems to be the root cause so I'll close this issue out for now in favor of tracking it there.

For a workaround for this, you could create another query that filters out the null values produced to the sink topic.
```
CREATE TABLE FEW_FIELDS_TABLE_FILTERED AS
SELECT field1, field2, field3
FROM FEW_FIELDS_TABLE
WHERE field1 IS NOT NULL
EMIT CHANGES;
```

**Closed by stevenpyzhang** 2020-08-04 17:44 UTC
Labels: needs-triage, question
