### ISSUE TITLE
Scalable push queries

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#5517] opened 2020-06-01 11:36 UTC
Push queries should scale.

An application tier should be able to subscribe to changes using syntax like:

```
SELECT * FROM THING WHERE ID=?;
```

Where each request has a different ID its interested in.

Currently, each request creates its own streams topology, which doesn't scale.  We need a more scalable solution that multiplexes such queries together.

One complexity to keep in mind is how when combine two such queries into the same query is _historic data_.   If `THING` is a stream, there stream may include historic values for a specific `ID`.  When a new query in the above form is started is would normally follow that it will see all historic data, followed by all new data.  This makes combining all such queries into a something that just consumes all data once more tricky.  We may want to consider syntax to allow such queries to say 'I only want to subscribe to new changes'.

**Comment by big-andy-coates** [comment] 2020-06-01 11:38
SO question around this: https://stackoverflow.com/questions/51999835/how-many-connections-subscriptions-can-handle-kafka-ksql/62131291#62131291

**Comment by agavra** [comment] 2021-02-03 21:00
Closing as duplicate of #5907

**Closed by agavra** 2021-02-03 21:00 UTC
