### ISSUE TITLE
Ksql Rest endpoint: KsqlResource should prepare statements once

### ISSUE THREAD

**Issue by vpapavas** [confluentinc/ksql#3709] opened 2019-10-31 23:32 UTC
**Is your feature request related to a problem? Please describe.**

Performance improvement: Currently, statements in a request are prepared twice, once in `RequestValidator.validate` and once in `RequestHandler.execute`. 

**Describe the solution you'd like**
Remove duplicate code and overhead

**Describe alternatives you've considered**

**Additional context**

**Comment by big-andy-coates** [comment] 2019-11-07 11:08
The above is by design. The reason we validate commands is to avoid posting loads of invalid commands to the command topic.

Once we break the dependency between the parsing and the metastore we may be able to parse the statements only once. However, 'prepare' requires the metastore, where the state can change.

this issue seems to relate specifically to pull queries. As per other discussion, we should move pull queries onto the /query endpoint.  Hence closing this issue.

**Closed by big-andy-coates** 2019-11-07 11:08 UTC
Labels: enhancement
