### ISSUE TITLE
Cannot select non-standard (lowercase) column names from stream

### ISSUE THREAD

**Issue by nmatare** [confluentinc/ksql#5159] opened 2020-04-23 23:00 UTC
**Describe the bug**
Cannot create a derivative (downstream) stream from a non-standard (not all uppercase) column name.

**To Reproduce**
```
CLI v5.4.1, Server v5.4.1 
```

First, create a stream named "BASE" containing a lower case column and put some dummy data into it. This is the upstream stream.
```
SET 'auto.offset.reset'='earliest';
CREATE STREAM BASE 
	(`lower_case` BIGINT)
	WITH (
		VALUE_FORMAT='AVRO',
		KAFKA_TOPIC='lower_case_topic',
		PARTITIONS=2,
		REPLICAS=1
	);
INSERT INTO BASE (`lower_case`) VALUES (123);
```

Observe expected behavior when we query the stream directly:
```
SELECT lower_case FROM BASE EMIT CHANGES;
>>> 'BASE.LOWER_CASE' cannot be resolved.

SELECT `lower_case` FROM BASE EMIT CHANGES;
>>> 123 

SELECT 'lower_case' FROM BASE EMIT CHANGES;
>>> lower_case 

SELECT "lower_case" FROM BASE EMIT CHANGES;
>>> 123
```

Now try creating a derivative stream, and querying from it with the same syntax:
```
CREATE STREAM DERIVATIVE1 AS SELECT
  `lower_case`
FROM BASE;
>>> Column 'BASE.LOWER_CASE' cannot be resolved.
```
```
CREATE STREAM DERIVATIVE2 AS SELECT
  'lower_case'
FROM BASE;
SELECT * FROM DERIVATIVE2 EMIT CHANGES;
>>> lower_case  # not what we want
```
```
CREATE STREAM DERIVATIVE3 AS SELECT
  "lower_case"
FROM BASE;
>>> Column 'BASE.LOWER_CASE' cannot be resolved.
```
```
CREATE STREAM DERIVATIVE4 AS SELECT
  'BASE.lower_case'
FROM BASE;
SELECT * FROM DERIVATIVE4 EMIT CHANGES;
>>> BASE.lower_case
```

So how to select non-standard column names when creating a derivative stream?

**Comment by agavra** [comment] 2020-04-24 00:35
I think this is a duplicate of #4419 which has been fixed in 5.5 (coming soon) and ksqlDB 0.8.0+ - it will also be fixed in 5.4.2, though not sure when that's coming out. Feel free to re-open this issue if you can reproduce it on any of those versions.

**Closed by agavra** 2020-04-24 00:35 UTC
Labels: bug, needs-triage
