### ISSUE TITLE
A compacted topic for the metastore

### ISSUE THREAD

**Issue by dguy** [confluentinc/ksql#742] opened 2018-02-15 09:33 UTC
In #479, as an interim solution, we have set the retention policy for the command topic to `Long.MAX_VALUE` so that we don't lose data when the delete policy kicks in and a ksql node has restarted or a new ksql node has joined. 
As a longer term solution we should look into backing the metastore with a compacted topic. The compacted topic would contain the current snapshot of the metastore, i.e., all the tables and streams etc that currently exist. Each message in the topic would also contain the offset of the record from the command topic that created the update to the metastore. 
At startup we could then restore the metastore from the compacted topic, get the offset from the last restoration message, and then seek to that offset in the command store to pick up from where we left off. We could then reduce the command topic retention back to something reasonable.

**Comment by big-andy-coates** [comment] 2020-11-18 14:04
duplicate of https://github.com/confluentinc/ksql/pull/4659

**Closed by big-andy-coates** 2020-11-18 14:04 UTC
Labels: enhancement
