### ISSUE TITLE
Need of CASE in the ksql query

### ISSUE THREAD

**Issue by rag594** [confluentinc/ksql#1125] opened 2018-04-06 05:57 UTC
Example: `COUNT(CASE when m1 > 10)`.

This is needed for aggregating multiple independent metrics.

**Comment by miguno** [comment] 2018-04-06 08:19
Duplicate of https://github.com/confluentinc/ksql/issues/620 ?

**Comment by rag594** [comment] 2018-04-07 14:43
Yes, sorry its a duplicate

**Closed** 2018-04-11 09:08 UTC
Labels: enhancement
