### ISSUE TITLE
Cannot get WINDOWSTART from Table

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#4000] opened 2019-11-29 17:47 UTC
ksqlDB 0.6

Windowed table: 

```
ksql> DESCRIBE EXTENDED RETWEET_5MIN;

Name                 : RETWEET_5MIN
Type                 : TABLE
Key field            : RETWEET
Key format           : STRING
Timestamp field      : Not set - using <ROWTIME>
Value format         : AVRO
Kafka topic          : RETWEET_5MIN (partitions: 1, replication: 1)

 Field       | Type
-----------------------------------------
 ROWTIME     | BIGINT           (system)
 ROWKEY      | VARCHAR(STRING)  (system)
 RETWEET     | BOOLEAN
 TWEET_COUNT | BIGINT
-----------------------------------------

Queries that write from this TABLE
-----------------------------------
CTAS_RETWEET_5MIN_3 : CREATE TABLE RETWEET_5MIN WITH (KAFKA_TOPIC='RETWEET_5MIN', PARTITIONS=1, REPLICAS=1) AS SELECT
  TWEETS_RAW.RETWEET RETWEET,
  COUNT(*) TWEET_COUNT
FROM TWEETS_RAW TWEETS_RAW
WINDOW TUMBLING ( SIZE 5 MINUTES )
GROUP BY TWEETS_RAW.RETWEET
EMIT CHANGES;

For query topology and execution plan please run: EXPLAIN <QueryId>

Local runtime statistics
------------------------
messages-per-sec:      0.77   total-messages:      1389     last-message: 2019-11-29T17:44:45.391Z

(Statistics of the local KSQL server interaction with the Kafka topic RETWEET_5MIN)
ksql>
```

I want to see the timestamp of each window. It's there in the key: 

```
ksql> SELECT ROWKEY FROM RETWEET_5MIN EMIT CHANGES LIMIT 5;
+-------------------------------------------------------------------------------------------------------------------------------------------+
|ROWKEY                                                                                                                                     |
+-------------------------------------------------------------------------------------------------------------------------------------------+
|false : Window{start=1575044100000 end=-}                                                                                                  |
|true : Window{start=1575044100000 end=-}                                                                                                   |
|false : Window{start=1575044400000 end=-}                                                                                                  |
|true : Window{start=1575044400000 end=-}                                                                                                   |
|false : Window{start=1575044700000 end=-}                                                                                                  |
Limit Reached
Query terminated
ksql>
```

But I cannot access it using `WINDOWSTART`

```
ksql> SELECT WINDOWSTART() FROM RETWEET_5MIN EMIT CHANGES;
Use of aggregate functions requires a GROUP BY clause. Aggregate function(s): WINDOWSTART
```

```
ksql> SELECT WINDOWSTART FROM RETWEET_5MIN EMIT CHANGES;
Column 'RETWEET_5MIN.WINDOWSTART' cannot be resolved.
```

Related? #3633

**Comment by rmoff** [comment] 2019-11-29 17:55
Confusingly, in a pull query, `WINDOWSTART` is available for use in the predicate, but not the SELECT

```
ksql> SELECT RETWEET FROM RETWEET_5MIN WHERE ROWKEY='true' AND WINDOWSTART > 1575044700000;
+-------------------------------------------------------------------------------------------------------------------------------------------+
|RETWEET                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------+
|true                                                                                                                                       |
|true                                                                                                                                       |
|true                                                                                                                                       |
|true                                                                                                                                       |
|true                                                                                                                                       |
|true                                                                                                                                       |
```

**Comment by big-andy-coates** [comment] 2019-12-02 19:56
Yep, this is a known issue.  Doing a `SELECT *` from the source will return `WINDOWSTART`, you just can't yet do `SELECT WINDOWSTART, ...`

Closing as duplicate of https://github.com/confluentinc/ksql/issues/3633

**Closed by big-andy-coates** 2019-12-02 19:56 UTC
Labels: enhancement
