### ISSUE TITLE
ksql-package NoClassDefFoundError 

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/ksql#1667] opened 2018-07-31 01:18 UTC
i run mvn package to build the project, but i get the exception when i run from ksql-package:
```bash
[larluo@larluo-nixos:~/work/git/my-repo/ksql]$ ksql-package/target/ksql-package-5.1.0-SNAPSHOT-package/bin/ksql ksql-package/target/ksql-package-5.1.0-SNAPSHOT-package/etc/ksql/ksql-server.properties
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/common/config/ConfigException
        at io.confluent.ksql.Ksql.main(Ksql.java:46)
Caused by: java.lang.ClassNotFoundException: io.confluent.common.config.ConfigException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

```

it's success when i run for whole project
```shell
[larluo@larluo-nixos:~/work/git/my-repo/ksql]$ bin/ksql-server-start ksql-package/target/ksql-package-5.1.0-SNAPSHOT-package/etc/ksql/ksql-server.properties
Jul 31, 2018 9:07:53 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.confluent.ksql.rest.server.resources.StatusResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.StatusResource will be ignored. 
Jul 31, 2018 9:07:53 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.confluent.ksql.rest.server.resources.KsqlResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.KsqlResource will be ignored. 
Jul 31, 2018 9:07:53 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.confluent.ksql.rest.server.resources.RootDocument registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.RootDocument will be ignored. 
Jul 31, 2018 9:07:53 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.confluent.ksql.rest.server.resources.ServerInfoResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.ServerInfoResource will be ignored. 
Jul 31, 2018 9:07:53 AM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource will be ignored. 
                  
                  ===========================================
                  =        _  __ _____  ____  _             =
                  =       | |/ // ____|/ __ \| |            =
                  =       | ' /| (___ | |  | | |            =
                  =       |  <  \___ \| |  | | |            =
                  =       | . \ ____) | |__| | |____        =
                  =       |_|\_\_____/ \___\_\______|       =
                  =                                         =
                  =  Streaming SQL Engine for Apache Kafka® =
                  ===========================================

Copyright 2017-2018 Confluent Inc.

Server 5.1.0-SNAPSHOT listening on http://localhost:8088

To access the KSQL CLI, run:
ksql http://localhost:8088
```

**Comment by big-data-media** [comment] 2018-07-31 15:46
same kind of error here

`(io.confluent.ksql.rest.server.KsqlRestConfig:175)
Exception in thread "main" java.lang.NoClassDefFoundError: javax/websocket/DeploymentException
	at io.confluent.ksql.rest.server.KsqlServerMain.createExecutable(KsqlServerMain.java:83)
	at io.confluent.ksql.rest.server.KsqlServerMain.main(KsqlServerMain.java:45)
Caused by: java.lang.ClassNotFoundException: javax.websocket.DeploymentException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
`

**Comment by apurvam** [comment] 2018-08-01 23:59
Do the docs for how to build and test locally not work? https://github.com/confluentinc/ksql/blob/master/CONTRIBUTING.md

Any reason to deviate from them?

**Comment by clojurians-org** [comment] 2018-08-02 02:16
i want to get tarball for deploy, the whole mvn package cost 800m size.

**Comment by apurvam** [comment] 2018-08-02 06:07
you can get the binary tarballs from confluent.io/download

**Comment by clojurians-org** [comment] 2018-08-02 06:43
yeah, i switch to conflucent.io as confluent 5.0 release.

i want try the new feature to evaluate the usage, but confluent is lagged a little. 
so i need a way to deploy beta version sometimes.

**Comment by apurvam** [comment] 2018-08-09 18:50
Right now we don't publish tarballs for nightly releases. Your only option is to build from source at the top level. Going to close this out.

**Closed by apurvam** 2018-08-09 18:50 UTC
