### ISSUE TITLE
Add datetime/timestamp type support

### ISSUE THREAD

**Issue by mikebin** [confluentinc/ksql#5299] opened 2020-05-06 22:51 UTC
It would be useful to add support for a datetime/timestamp type in ksqlDB which can be represented as a timestamp logical type (`timestamp-millis`) in Avro, similar to how ksqlDB `DECIMAL` can be represented as a logical decimal type in Avro.

Currently, a timestamp can be represented in ksqlDB as a `BIGINT`, but when using Avro, if the source field is of logical type `timestamp-millis`, the logical type information is lost when propagated to the sink through a query, and it also doesn't seem possible to construct a return type manually in a UDF which contains the logical type information.

**Comment by agavra** [comment] 2021-01-08 18:37
closing as duplicate of #4148

**Closed by agavra** 2021-01-08 18:38 UTC
Labels: enhancement
