### ISSUE TITLE
One Kafka message to hold a list of items

### ISSUE THREAD

**Issue by sternr** [confluentinc/ksql#1921] opened 2018-09-20 12:06 UTC
Not getting into the nitty details of why, but the bottom line is each of our Kafka messages is actually a list of json objects:

`[{id:"1", name:"a"}, {id:"2",name:"b"}]`

Is it possible to configure ksql so that each json in the list is a single row?

**Comment by big-andy-coates** [comment] 2018-09-20 15:08
Hi @sternr,

This is not currently possible with KSQL.  Currently each input row can only generate one output row. What we need for this sort of thing is UDTFs. It's on our radar, but no fixed timeframe as yet.

This is related to: #1830 and #527

**Comment by jaszka** [comment] 2019-02-07 09:26
+ 1

**Comment by big-andy-coates** [comment] 2019-09-24 13:10
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/527

**Closed by big-andy-coates** 2019-09-24 13:10 UTC
Labels: data-accessibility, enhancement
