### ISSUE TITLE
"Offset" Keyword when creating streams

### ISSUE THREAD

**Issue by naamancurtis** [confluentinc/ksql#7089] opened 2021-02-24 14:05 UTC
**Is your feature request related to a problem? Please describe.**
We have a kafka topic which contains many streams of data (each identified by their key). Each "mini stream" contains a periodic snapshot of a large data set, and subsequent small events at an increased frequency which contain a changeset compared to that snapshot. At any point in time, we would like to be able to jump to the latest "snapshot" for any given key and replay all of the events after that snapshot, then continue to consume new events as and when they occur. 

From my understanding of Kafka, Kafka Streams and KSQL-DB, the most ideal way to do this would be to "know" the OFFSET of the latest "snapshot" and consume from that point. However there isn't an immediately obvious (and easy) way to actually get the value of that OFFSET, especially if we'd rather this application soley use KSQL-DB instead of having to tap into the underlying kafka API.

**Describe the solution you'd like**
Add a pseudocolumn OFFSET (like ROWKEY), to the CREATE STREAM statement that lets you add the OFFSET of the  records as a value

```sql
CREATE STREAM MY_STREAM (
  id VARCHAR KEY,
  off OFFSET
) with (...);
```

From a stream like this, it would be possible to create a materialized table that allows us to quickly look up the OFFSET of the latest "snapshot" for each given key. Enabling us to write this functionality.

**Describe alternatives you've considered**
- We've tried using a `COLLECT_LIST` to group the latest "snapshot" + "changeset" together in a materialized table, and although this seems work, there is no nice way to seamlessly transition this Pull Query (of the latest snapshot + changeset) into a Push Query (of all of the new changesets that come in after the query is issued), there has to be a reasonable amount of reconciliation to make this work in a way where we can guarentee we don't drop changesets.

**Additional context**

**Comment by vcrfxia** [comment] 2021-03-02 20:28
Hi @naamancurtis , if I understand your request correctly, it is a duplicate of https://github.com/confluentinc/ksql/issues/976. Can you please confirm whether this is the case? If so, we can close this ticket and track the request in the other one instead. (Please upvote the other one as well!) Thanks.

**Closed** 2021-03-02 20:29 UTC
Labels: enhancement, streaming-engine
