### ISSUE TITLE
Potentially inconsistent behavior in table-table joins

### ISSUE THREAD

**Issue by mxbltn** [confluentinc/ksql#8938] opened 2022-03-28 11:34 UTC
Hi!

I am experimenting with table-table joins between a structured key and a simple (non-wrapped) key, and I am experiencing some inconsistent results.

A. Working: https://pastebin.com/7Kv3ASXB
B. Not working: https://pastebin.com/UTfun8ee

In the first scenario I create two source tables, one with a simple string key, one with a structured key with two string properties. Joining them on the condition of `simple_key = structured_key_a`, I get the expected results.

In the second scenario, I do the same thing, except the left table is constructed by regrouping a stream source. The resulting field schema is identical. The joined table however, does not produce any records.

Setting `partitions = 1` on all streams and tables, the second example works perfectly, so it clearly has something to do with partitioning. It’s not entirely clear to me however what differentiates scenario A from scenario B.

Description of left table:
* A. Working: https://pastebin.com/3qiJ2k3m
* B. Not working: https://pastebin.com/p4eeZyBi

**Comment by jnh5y** [comment] 2022-03-28 13:30
@mxbltn @Gerrrr I wonder if this issue is related to https://github.com/confluentinc/ksql/issues/8528 / https://github.com/confluentinc/ksql/pull/8926?

**Comment by Gerrrr** [comment] 2022-03-30 09:06
@mxbltn

This issue is a bug in FK join since it does not join on the entire composite primary key of `join_test_left`, but only on a single column. As the issue reproduces on 0.24 and does not reproduce on `master`, I think the bug we hit here is https://issues.apache.org/jira/browse/KAFKA-13261. 

Unfortunately, the only workaround I can offer right now is to avoid using the composite key in FK join until the fix is released. In your example, you use 2 varchar columns. Perhaps you can create a table that transforms them into a single PK column and use it to join?

As I mentioned above, the bugfix is already merged, so we just need to wait for the upcoming release for it to be available. I am going to close the issue. Feel free to re-open it or ping me on Slack if you have further questions.

**Comment by ayushkhandelwal317** [comment] 2022-07-14 13:11
Hi @Gerrrr ,

We tried the following code snippet in KSQLDB 0.26.0 with cp-kafka:7.2.0 (Kafka 3.2.0), but we were still getting inconsistent data when PARTITIONS > 1 

```sql
CREATE TABLE USER (
    ID INT PRIMARY KEY,
    NAME VARCHAR PRIMARY KEY,
    ADDRESS_ID INT
) with (KAFKA_TOPIC='USER', FORMAT='AVRO', PARTITIONS=4);

CREATE TABLE USER_RELATIVE (
    USER_ID INT PRIMARY KEY,
    NAME VARCHAR
) with (KAFKA_TOPIC='USER_RELATIVE', FORMAT='AVRO', PARTITIONS=4);

INSERT INTO USER VALUES (1, 'Name1', 101);
INSERT INTO USER VALUES (2, 'Name2', 102);
INSERT INTO USER VALUES (3, 'Name3', 103);
INSERT INTO USER VALUES (4, 'Name4', 104);

INSERT INTO USER_RELATIVE VALUES (1, 'Relative 1');
INSERT INTO USER_RELATIVE VALUES (2, 'Relative 2');
INSERT INTO USER_RELATIVE VALUES (3, 'Relative 3');
INSERT INTO USER_RELATIVE VALUES (4, 'Relative 4');

SELECT * FROM USER u
    INNER JOIN USER_RELATIVE ur on ur.user_id = u.id emit changes;
```

The expected result was : 
```
+---------------+---------------+---------------+---------------+---------------+
|U_ID           |U_NAME         |U_ADDRESS_ID   |UR_USER_ID     |UR_NAME        |
+---------------+---------------+---------------+---------------+---------------+
|1              |Name1          |101            |1              |Relative 1     |
|2              |Name2          |102            |2              |Relative 2     |
|3              |Name3          |103            |3              |Relative 3     |
|4              |Name4          |104            |4              |Relative 4     |
```

But what we actually got was : 
```
+---------------+---------------+---------------+---------------+---------------+
|U_ID           |U_NAME         |U_ADDRESS_ID   |UR_USER_ID     |UR_NAME        |
+---------------+---------------+---------------+---------------+---------------+
|4              |Name4          |104            |4              |Relative 4     |
|3              |Name3          |103            |3              |Relative 3     |
```

(the result above was inconsistent, it was giving different results on dropping and recreating the topics/tables - always less than the expected 4)

When we re-ran the exact same code with PARTITIONS=1, everything was working as expected consistently.
 CC : @znxftw

**Comment by vraravam** [comment] 2022-07-15 02:20
@Gerrrr - any idea on the timeline for 0.27?

**Comment by Gerrrr** [comment] 2022-07-15 08:38
@vraravam It will likely be available within the next couple of weeks. I can't share an exact date, unfortunately.

**Comment by Gerrrr** [comment] 2022-07-25 12:20
@vraravam @ayushkhandelwal317 ksqlDB [0.27.1](https://www.confluent.io/blog/announcing-ksqldb-0-27-1/) release with the fix for [KAFKA-13769](https://issues.apache.org/jira/browse/KAFKA-13769) is out!.

**Comment by ayushkhandelwal317** [comment] 2022-07-25 13:07
Thanks for the update @Gerrrr. Seems to be working fine now.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/33805661/180784362-38d647f5-68f5-47b9-904d-2477852498eb.png">

**Comment by Gerrrr** [comment] 2022-07-25 13:35
I'll close the issue for now. Feel free to reopen if you run into this bug again.

**Closed by Gerrrr** 2022-07-25 13:35 UTC
Labels: question, streaming-engine
