### ISSUE TITLE
Unfriendly UX when schema in struct returned by a UDF doesn't match annotation

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#3502] opened 2019-10-09 02:14 UTC
Consider the following UDF:

```
    @Udf(description = "returns geolocation for an IP address",
            schema = "STRUCT<ping VARCHAR, ping VARCHAR>")

    public Struct fancyfunction(@UdfParameter(
            value = "ip",
            description = "the IP address to lookup in the geoip database") String ip) {

        public final Schema schema = new SchemaBuilder().struct()
            .field("ping", Schema.OPTIONAL_STRING)
            .field("pong", Schema.OPTIONAL_STRING)
            .optional.build();
        return new Struct(schema).put("ping", "foo").put("pong", "bar");
    }
```

The schema in the returned struct uses lower-case fields, but the schema parsed by KSQL from the annotation uses capitalized field names. This causes non-obvious failures later on when serializing or trying to use the returned struct (e.g. in a dereference).

It's not obvious to a udf developer what the Schema in the Struct instance should be. Some ideas for improving this:
    - adding a function available for use from UDF/UDAFs for getting the expected return schema.
    - throwing an error immediately if the returned schema does not match the expected schema based on the annotation.

**Comment by big-andy-coates** [comment] 2020-11-18 09:20
Duplicate of https://github.com/confluentinc/ksql/issues/3624

**Closed by big-andy-coates** 2020-11-18 09:20 UTC
Labels: code-lifecycle-ux, engine, user-defined-functions, user-experience
