### ISSUE TITLE
GROUP BY is not working as expected

### ISSUE THREAD

**Issue by SergeyAshikhmin** [confluentinc/ksql#2477] opened 2019-02-22 12:20 UTC
To reproduce:
1) Create topic:

```shell
$ kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic topicInputCSV
```

2) Put next data in topic:

```
{"TransactionID":"9990000000000042","AccountID":"233","TxProcessingStartTime":"2019-02-18 11:33:39.503000000","Amount":"10"}
{"TransactionID":"9990000000000043","AccountID":"233","TxProcessingStartTime":"2019-02-19 11:51:24.400000000","Amount":"12"}
{"TransactionID":"9990000000000044","AccountID":"233","TxProcessingStartTime":"2019-02-20 12:03:38.750000000","Amount":"16"}
```

3) Create stream streamInputCSV :

```sql
CREATE STREAM streamInputCSV (TransactionID BIGINT,  AccountID INT,TxProcessingStartTime STRING, AMOUNT DOUBLE) \ 
      WITH (KAFKA_TOPIC='topicInputCSV', \
            VALUE_FORMAT='JSON', \
            TIMESTAMP='TxProcessingStartTime', \
            TIMESTAMP_FORMAT='yyyy-MM-dd'' ''HH:mm:ss.SSSSSSSSS', \          
            KEY='TransactionID' );
```

4) Clone that stream to streamInputCSV_02 :

```sql
CREATE STREAM streamInputCSV_02 \
WITH (PARTITIONS=1, TIMESTAMP='TxProcessingStartTime', \
         TIMESTAMP_FORMAT='yyyy-MM-dd'' ''HH:mm:ss.SSSSSSSSS'\
         ) AS \
SELECT * FROM streamInputCSV;
```

5) Run grouping query:

```sql
SELECT T1.TransactionID as TransactionID, T1.AccountID as AccountID, T1.TxProcessingStartTime as TxProcessingStartTime, T1.Amount as TransactionAmount, \
 SUM(T2.Amount) as SUMAMOUNT, COUNT(*) as CNT, SUM(T2.Amount)/COUNT(*) as AVG \
FROM   streamInputCSV T1 \
       INNER JOIN streamInputCSV_02 T2 \
        WITHIN (3 DAYS, 0 DAYS) \
        ON T1.AccountID = T2.AccountID \
WHERE   T1.TransactionID != T2.TransactionID \
AND   T2.ROWTIME != T1.ROWTIME \
GROUP BY T1.TransactionID, T1.AccountID, T1.Amount, T1.TxProcessingStartTime;
```

Actual result: Transaction 9990000000000044  has 2 rows

```
9990000000000043 | 233 | 2019-02-19 11:51:24.400000000 | 12.0 | 10.0 | 1 | 10.0
9990000000000044 | 233 | 2019-02-20 12:03:38.750000000 | 16.0 | 10.0 | 1 | 10.0
9990000000000044 | 233 | 2019-02-20 12:03:38.750000000 | 16.0 | 22.0 | 2 | 11.0
```

Expected result: Transaction 9990000000000044  has 1 rows, as grouping is doing via streamInputCSV columns only.

```
9990000000000043 | 233 | 2019-02-19 11:51:24.400000000 | 12.0 | 10.0 | 1 | 10.0
9990000000000044 | 233 | 2019-02-20 12:03:38.750000000 | 16.0 | 22.0 | 2 | 11.0
```

**Comment by miguno** [comment] 2019-02-24 10:55
Thanks for raising this, @SergeyAshikhmin.

The actual behavior that you observed is, in fact, today's expected behavior for KSQL.  A stream-stream is a windowed operation, and (in your example) it will always return two rows.  See the "innerJoin" column in the example table for stream-stream joins at https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Streams+Join+Semantics#KafkaStreamsJoinSemantics-KStream-KStreamJoin -- KSQL is built on top of Kafka's Streams API, hence it has the same join behavior.

Question: In your use case, why should the first output row for `9990000000000044` not be present in the output?  That is, this row:

```
9990000000000044 | 233 | 2019-02-20 12:03:38.750000000 | 16.0 | 10.0 | 1 | 10.0
```

FYI: There's a future work item tracked at https://github.com/confluentinc/ksql/issues/1030 ("Windowed aggregations: send only the final aggregation result of each window (cf. Suppress API of KStreams)") which might possibly be used to give more flexibility for stream-stream join behavior.

**Comment by SergeyAshikhmin** [comment] 2019-02-25 10:08
Hi, 
Correct, I was expecting to get only last row.  
In fact I am doing KTABLE at the end from query:
```sql
CREATE TABLE TableInputCSV_Last3Days as \
select T1.TransactionID as TransactionID, T1.AccountID as AccountID, T1.TxProcessingStartTime as TxProcessingStartTime, T1.Amount as TransactionAmount, \
 SUM(T2.Amount) as SUMAMOUNT, COUNT(*) as CNT, SUM(T2.Amount)/COUNT(*) as AVG \
FROM   streamInputCSV T1 \
       INNER JOIN streamInputCSV_02 T2 \
        WITHIN (3 DAYS, 0 DAYS) \
        ON T1.AccountID = T2.AccountID \
WHERE   T1.TransactionID != T2.TransactionID \
AND   T2.ROWTIME != T1.ROWTIME \
group by T1.TransactionID, T1.AccountID, T1.Amount, T1.TxProcessingStartTime;
```

And I was expecting to get one row with aggregations from T1, like it is in regular RDBMS tables and like in https://docs.confluent.io/current/ksql/docs/developer-guide/aggregate-streaming-data.html#aggregate-results-in-a-ksql-table

**Comment by miguno** [comment] 2019-02-25 14:34
I think you might also be interested in this feature request then: https://github.com/confluentinc/ksql/issues/530 "Support point-in-time queries for Tables (cf. queryable state)".

**Comment by mjsax** [comment] 2021-05-16 15:38
@SergeyAshikhmin When you say that you have two rows for `9990000000000044` are you actually referring to the output topic content? For this case, it's by design that there might be multiple records, because the output in the topic is a changelog stream. -- In stream processing, there is no such thing as a final result for an (non-windowed) aggregation.

I will close this ticket for now, as it seems the system behaves as designed. Feel free to follow up if you have more questions.

**Closed by mjsax** 2021-05-16 15:38 UTC
Labels: join-functions, question, window-functions
