### ISSUE TITLE
Add "sliding window" support for aggregation queries

### ISSUE THREAD

**Issue by ChenZhaobin** [confluentinc/ksql#7644] opened 2021-06-07 12:04 UTC
I want to calculate mean value based on current message within 10 minutes ,I have tried ' select  AVG(somefield) group by (anotherfield) within 10 minutes',but it threw an exception of "org.antlr.v4.runtime.InputMismatchException",
so how can I calculate the avarage value within 10 minutes  based on the newest message?

**Comment by MichaelDrogalis** [comment] 2021-06-07 16:45
Hi @ChenZhaobin. `WITHIN` can only be used with a join. You want to use [windows](https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#windows-in-sql-queries) to get a 10 minute rolling average. Windows can be used without joins.

**Comment by ChenZhaobin** [comment] 2021-06-08 01:29
It seems that [windows](https://docs.ksqldb.io/en/latest/concepts/time-and-windows-in-ksqldb-queries/#windows-in-sql-queries) can not meet my requirment just as this ticket :[KSQL Hopping Window : accessing only oldest subwindow](https://stackoverflow.com/questions/51794596/ksql-hopping-window-accessing-only-oldest-subwindow) , When the data comes in 10h:35m:20s, I want to get mean value of messages come in rang [10h:25m:20s,10h:35m:20s] ,not the windowed result [10h:25m,10h:35m] and [10h:35m,10h:40m] 

I will try to write a  [UDF](https://docs.ksqldb.io/en/latest/how-to-guides/create-a-user-defined-function/)  similar to `rolling_sum`

**Comment by mjsax** [comment] 2021-06-08 05:01
I think what you nee is a "sliding window". Those were added in Kafka Streams recently (https://issues.apache.org/jira/browse/KAFKA-5636) but we did not add support for ksqlDB yet. Should we repurpose this ticket as "feature request"?

**Comment by vcrfxia** [comment] 2021-06-15 16:45
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/6873. Please upvote the existing issue. Thanks!

**Closed by vcrfxia** 2021-06-15 16:45 UTC
Labels: P1, enhancement, sql-syntax, streaming-engine, window-functions
