### ISSUE TITLE
Add support for filtering based on Kafka message headers

### ISSUE THREAD

**Issue by danphanley** [confluentinc/ksql#658] opened 2018-01-25 20:20 UTC
From the source topic, do filtering based on header of the message, do no modification of the body, and write to a destination topic

**Comment by joewood** [comment] 2018-09-11 15:35
Is this still on the roadmap?

**Comment by apurvam** [comment] 2018-09-11 19:31
This is a great feature request, but it isn't on the roadmap at present.

**Comment by joewood** [comment] 2018-09-11 19:40
Would this be that difficult given that KIP-244 has landed in Kafka 2?

**Comment by apurvam** [comment] 2018-09-11 19:43
Yes, since that KIP only exposes headers in the processor API, not the DSL, which is what KSQL uses exclusively right now. Beyond the technical challenges, we also need to work out the language extensions for exposing the header information.

**Comment by joewood** [comment] 2018-09-11 19:53
Oh, didn't realize that. We really need Streams DSL to support headers too. :-) Surprised there's not an active dedicated KIP for that.

**Comment by Georgi-Ivanov-Fourth** [comment] 2020-01-06 07:54
Filtering based on message headers is must-have for multi-tenant scenarios. Otherwise the tenant meta-data should become part of the message payload - not a deal breaker, but there should be a better way.

**Comment by big-andy-coates** [comment] 2020-04-24 10:55
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/5167

**Closed by big-andy-coates** 2020-04-24 10:55 UTC
Labels: data-accessibility, enhancement

**Comment by joewood** [comment] 2020-04-24 11:39
OK, np. Can we keep the original issues open, that saves re-subscribing to new issues covering a 2 year old request?
