### ISSUE TITLE
WINDOWSTART not recognized for GROUP BY

### ISSUE THREAD

**Issue by harlev** [confluentinc/ksql#5595] opened 2020-06-10 18:14 UTC
When creating a windowed table, trying to use the `WINDOWSTART` in  GROUP BY generates an error

**To Reproduce**

1. ksqlDB 0.9.0
2. ksqldb-cli:0.9.0 
3. Steps to reproduce
* `CREATE STREAM s1 (a VARCHAR, b INT) WITH (kafka_topic='s1', partitions=1, value_format = 'avro');`
* `CREATE TABLE t1 AS SELECT count(*) FROM s1 WINDOW TUMBLING (SIZE 10 MINUTES) GROUP BY a EMIT CHANGES;`
* `SELECT count(*), WINDOWSTART FROM t1 GROUP BY WINDOWSTART EMIT CHANGES;`
* Get the error `Unknown column WINDOWSTART.`

Note that running `SELECT WINDOWSTART FROM t1 EMIT CHANGES;` **works successfully** in this scenario.

**Expected behavior**
Grouping on `WINDOWSTART` should work like for any other table column.

**Actual behaviour**

* CLI output: `Unknown column WINDOWSTART.`
* No error in the log while running the failed query.

**Comment by harlev** [comment] 2020-06-10 23:53
More insights:  
`SELECT * FROM t1 WHERE WINDOWSTART > 0 GROUP BY 1 EMIT CHANGES;` 
generates:
```
Unknown column WINDOWSTART.
```

While  
`SELECT * FROM t1 WHERE WINDOWSTART > 0 EMIT CHANGES;`  
works just fine.

**Comment by big-andy-coates** [comment] 2020-06-17 17:38
Thanks for reporting @harlev.  This is indeed an issue and a fix is on our roadmap, but will take a bit of reworking to make it work.   Closing this issue as a duplicate of https://github.com/confluentinc/ksql/issues/4397

**Closed by big-andy-coates** 2020-06-17 17:38 UTC
Labels: blocker, bug, needs-triage

**Comment by devopg** [comment] 2022-04-10 07:01
its fixed ? i got Unknown column WINDOWSTART in latest ksqldb

**Comment by mjsax** [comment] 2022-04-12 06:19
> Closing this issue as a duplicate of https://github.com/confluentinc/ksql/issues/4397

Not fixed. #4397 is still open. (This ticket was only closed as duplicate.)
