### ISSUE TITLE
Stream and encrypt fields 

### ISSUE THREAD

**Issue by joshualouis911** [confluentinc/ksql#3174] opened 2019-08-06 12:43 UTC
Hi, 

I am trying to encrypt personal data with in the message. Messages are published in to a kafka topic and stream process would stream and encrypt selective fields and publish in to different topics. These are JSON messages and we want the message structure to be retained with some of the columns being encrypted. I am exploring KSQL, is there an option to query these fields and replace with encrypted values.

1) Is KSQL an option 
2) How can we retain the JSON message structure from Topic after encryption

**Comment by miguno** [comment] 2019-08-22 15:03
Duplicate of https://github.com/confluentinc/ksql/issues/3175.

**Closed by miguno** 2019-08-22 15:03 UTC
