### ISSUE TITLE
Pull Queries: Support arbitrary pull queries

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3546] opened 2019-10-11 12:00 UTC
We should support a lot more functionality for pull queries, e.g.

- pull queries where the table is not materialized
- pull queries with no constraint on ROWKEY
- pull queries with JOINs or GROUP BY etc.

The distinction here is that a pull query runs from the beginning of time to current offsets.  For these more complex queries we should fall back to using a KS topology against the data in Kafka i.e. using materialized state stores is an _optimisation_.

We can then make enhancements over time to support more and more using materialized tables.

`EXPLAIN <some pull query>` should make it clear if a query is a 'table scan' ie reading all data from Kafka, or using a materialized table.

**Comment by vinothchandar** [comment] 2019-11-19 02:06
@derekjn @apurvam @big-andy-coates Are we planning to work on this in the Q4 timeframe? 

Can we prioritize them against feedback we get and schedule them for Q1 instead..

**Comment by big-andy-coates** [comment] 2019-12-11 15:51
Really, this requires https://github.com/confluentinc/ksql/issues/3541 first.

**Comment by agavra** [comment] 2021-02-03 20:46
Duplicate of #6726

**Closed by agavra** 2021-02-03 20:46 UTC
Labels: engine
