### ISSUE TITLE
KSQL creates streams with inconsistent Protobuf schema if the Protobuf definition has multiple messages

### ISSUE THREAD

**Issue by angoothachap** [confluentinc/ksql#8714] opened 2022-02-03 19:05 UTC
Describe the bug
If a proto file has a complex type first followed by a simple type, only the elements from the complex type are accessible in ksqldb; whereas if a simple type is followed by a complex type in a proto, ksqldb can find all elements.

To Reproduce
Steps to reproduce the behavior, include:
1. The version of KSQL.
    I used managed ksqldb
2. Sample source data.
    1. Schema: 
```
syntax = "proto3";
package io.confluent.examples.generated_sources.protobuf;

import "Customer.proto";

message MessageEnvelopeNotOneOf {
  Customer customer = 1;
  string messageHeader = 2;
}
```
The above schema creates the below stream in ksqldb:
```{
  "@type": "sourceDescription",
  "statementText": "describe MESSAGEENVELOPENOTONEOFSTREAM;",
  "sourceDescription": {
    "name": "MESSAGEENVELOPENOTONEOFSTREAM",
    "windowType": null,
    "readQueries": [

    ],
    "writeQueries": [

    ],
    "fields": [
      {
        "name": "CUSTOMER",
        "schema": {
          "type": "STRUCT",
          "fields": [
            {
              "name": "CUSTOMER_ID",
              "schema": {
                "type": "BIGINT",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_NAME",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_EMAIL",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_ADDRESS",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            }
          ],
          "memberSchema": null
        }
      }
    ],
    "type": "STREAM",
    "timestamp": "",
    "statistics": "",
    "errorStats": "",
    "extended": false,
    "keyFormat": "KAFKA",
    "valueFormat": "PROTOBUF",
    "topic": "MessageEnvelopeNotOneOf",
    "partitions": 6,
    "replication": 3,
    "statement": "CREATE STREAM MESSAGEENVELOPENOTONEOFSTREAM (CUSTOMER STRUCT<CUSTOMER_ID BIGINT, CUSTOMER_NAME STRING, CUSTOMER_EMAIL STRING, CUSTOMER_ADDRESS STRING>) WITH (KAFKA_TOPIC='MessageEnvelopeNotOneOf', KEY_FORMAT='KAFKA', VALUE_FORMAT='PROTOBUF', VALUE_SCHEMA_ID=100068);",
    "queryOffsetSummaries": [

    ],
    "sourceConstraints": [

    ],
    "clusterStatistics": [

    ],
    "clusterErrorStats": [

    ]
  },
  "warnings": [

  ]
}
```

2. Schema:
```
syntax = "proto3";
package io.confluent.examples.generated_sources.protobuf;

import "Customer.proto";

message MessageEnvelopeNotOneOfSimpleFirst {
  string messageHeader = 1;
  Customer customer = 2;
}

```
The above schema creates the below stream in ksqldb:
```
{
  "@type": "sourceDescription",
  "statementText": "describe p2;",
  "sourceDescription": {
    "name": "P2",
    "windowType": null,
    "readQueries": [

    ],
    "writeQueries": [

    ],
    "fields": [
      {
        "name": "MESSAGEHEADER",
        "schema": {
          "type": "STRING",
          "fields": null,
          "memberSchema": null
        }
      },
      {
        "name": "CUSTOMER",
        "schema": {
          "type": "STRUCT",
          "fields": [
            {
              "name": "CUSTOMER_ID",
              "schema": {
                "type": "BIGINT",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_NAME",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_EMAIL",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            },
            {
              "name": "CUSTOMER_ADDRESS",
              "schema": {
                "type": "STRING",
                "fields": null,
                "memberSchema": null
              }
            }
          ],
          "memberSchema": null
        }
      }
    ],
    "type": "STREAM",
    "timestamp": "",
    "statistics": "",
    "errorStats": "",
    "extended": false,
    "keyFormat": "KAFKA",
    "valueFormat": "PROTOBUF",
    "topic": "MessageEnvelopeNotOneOfSimpleFirst",
    "partitions": 6,
    "replication": 3,
    "statement": "CREATE STREAM P2 (MESSAGEHEADER STRING, CUSTOMER STRUCT<CUSTOMER_ID BIGINT, CUSTOMER_NAME STRING, CUSTOMER_EMAIL STRING, CUSTOMER_ADDRESS STRING>) WITH (KAFKA_TOPIC='MessageEnvelopeNotOneOfSimpleFirst', KEY_FORMAT='KAFKA', VALUE_FORMAT='PROTOBUF', VALUE_SCHEMA_ID=100073);",
    "queryOffsetSummaries": [

    ],
    "sourceConstraints": [

    ],
    "clusterStatistics": [

    ],
    "clusterErrorStats": [

    ]
  },
  "warnings": [

  ]
}```

3. Any SQL statements you ran

Expected behavior
both formats should give consistent results - all elements should be accessible from the complex type in addition to the simple type

Actual behaviour
inconsistent behavior as described
CLI output Given above

Error messages None
KSQL logs No error


Additional context None

**Comment by suhas-satish** [comment] 2022-02-10 22:21
This is a duplicate of https://github.com/confluentinc/ksql/issues/8714

**Comment by colinhicks** [comment] 2022-02-11 14:07
@suhas-satish did you mean to link a different issue here? #8714 is a self-reference.

**Comment by suhas-satish** [comment] 2022-02-11 17:03
Sorry, yes I meant to link https://github.com/confluentinc/ksql/issues/5265

**Comment by colinhicks** [comment] 2022-02-11 17:33
There may be some common cause, but to me there is a distinction between these two issues:

8714 indicates the order of message fields matters:
```
message MessageEnvelopeNotOneOf {
  Customer customer = 1;
  string messageHeader = 2;
}
```
vs
```
message MessageEnvelopeNotOneOfSimpleFirst {
  string messageHeader = 1;
  Customer customer = 2;
}
```
In the first case, the `messageHeader` field is not present in the sourceDescription fields, apparently because ksql ignores it. In the second case, `messageHeader` is present as expected.

--
5265 indicates ksql does not fully support protobuf schemas with multiple messages at the top level.
```
# mytypes.proto
message A { ... }
message B { ... }
message C { ... }
```
In this case, ksql only "sees" `message A`.

**Comment by suhas-satish** [comment] 2022-02-11 17:48
yes that makes sense. They're indeed not duplicates.

**Comment by jnh5y** [comment] 2022-02-14 17:10
Hi @angoothachap, @colinhicks and I tried to reproduce this issue and were not able to.  Here's what we tried; let us know if you hit this issue doing something slightly different.

We created a Protobuf Schema for a type like `Customer`.  (When I did it, I happened to use the `SampleRecord` type in the UI for Protobuf.). After that, we followed your example and created types like

```
import sample.proto; 

message CustomerFirst {
  SampleRecord customer = 1;
  string messageHeader = 2;
}
```

```
import sample.proto; 

message MessageFirst {
  string messageHeader = 1;
  SampleRecord customer = 2;
}
```

And then created streams with commands like:
`CREATE STREAM customerFirst WITH (kafka_topic='customerFirst', value_format='protobuf');` and `CREATE STREAM messageFirst WITH (kafka_topic=‘messageFirst’, value_format='protobuf');`

The output of `describe customerFirst;` contained this bit:
```
  "statementText": "CREATE STREAM CUSTOMERFIRST (CUSTOMER STRUCT<MY_FIELD1 INTEGER, MY_FIELD2 DOUBLE, MY_FIELD3 STRING>, MESSAGEHEADER STRING) WITH (KAFKA_TOPIC='customerFirst', KEY_FORMAT='KAFKA', PARTITIONS=1, VALUE_FORMAT='PROTOBUF', VALUE_SCHEMA_ID=6);",
``` 
and `describe messageFirst;` had:
```  "statementText": "CREATE STREAM MESSAGEFIRST (MESSAGEHEADER STRING, CUSTOMER STRUCT<MY_FIELD1 INTEGER, MY_FIELD2 DOUBLE, MY_FIELD3 STRING>) WITH (KAFKA_TOPIC='messageFirst', KEY_FORMAT='KAFKA', PARTITIONS=1, VALUE_FORMAT='PROTOBUF', VALUE_SCHEMA_ID=7);",```

From looking at this output, we can see that both streams have been created with both fields.

**Comment by jnh5y** [comment] 2022-03-04 21:02
@angoothachap just to follow up on this, does what Colin and I tried look reasonable?  Do you have any other details?  If not, we may close this in another week.

**Comment by jnh5y** [comment] 2022-03-07 20:12
@angoothachap and I chatted about this issue some today.  It looks like the order of operations was that an initial schema with just the first field was created, then the stream was created, and finally the schema had the messageHeader field added to it.  

Given that sequence of events, this is the current, expected behavior.

**Closed by jnh5y** 2022-03-07 20:12 UTC
Labels: question, streaming-engine
