### ISSUE TITLE
The PRINT function can skip the value to null

### ISSUE THREAD

**Issue by ReasonDuan** [confluentinc/ksql#5509] opened 2020-05-29 05:46 UTC
There are a lot of data values in the topic generated after the ksql having condition is null. When I use the PRINT function to print, all I see is empty content. Can I add a parameter to make PRINT not print data with a value of null?

`ksql> PRINT KSQL_FINGERPRINT_3MIN;
Key format: SESSION(KAFKA_STRING) or HOPPING(KAFKA_STRING) or TUMBLING(KAFKA_STRING)
Value format: ¯\_(ツ)_/¯ - no data processed
rowtime: 2020/05/29 05:31:20.383 Z, key: [612c34ed93f697ebd7d076d3@1590730200000/7308818617344418149], value: <null>
rowtime: 2020/05/29 05:31:20.652 Z, key: [486b6b4de35d1fd6f8b463b8@1590730200000/3978898435839161441], value: <null>
rowtime: 2020/05/29 05:31:20.839 Z, key: [e29baef458dd5d3701efcb52@1590730200000/7368895768746111841], value: <null>
rowtime: 2020/05/29 05:31:20.773 Z, key: [52bfbe3ab56c7909b3901258@1590730200000/7308871363703813990], value: <null>
rowtime: 2020/05/29 05:31:21.471 Z, key: [06618a3622a054911d1dbe0e@1590730200000/7378839135565952353], value: <null>
rowtime: 2020/05/29 05:31:21.791 Z, key: [f1940d8d360aad4615ecc72d@1590730200000/3618849186077570405], value: <null>
rowtime: 2020/05/29 05:31:22.166 Z, key: [81d8eb1e96f405406f2a31d7@1590730200000/3848899928893142583], value: <null>`

Like this:
`ksql> PRINT KSQL_FINGERPRINT_3MIN NOTNULL;`

**Comment by big-andy-coates** [comment] 2020-06-17 15:11
Hi @ReasonDuan - thanks for reporting. This is a known issue, which we're looking into. Closing this as a duplicate of https://github.com/confluentinc/ksql/issues/3616.

**Closed by big-andy-coates** 2020-06-17 15:11 UTC
Labels: enhancement
