### ISSUE TITLE
java.lang.NoClassDefFoundError when java.io.tmpdir is not writable

### ISSUE THREAD

**Issue by apurvam** [confluentinc/ksql#1332] opened 2018-05-22 20:19 UTC
KSQL leverages RocksDB which includes a C library. As part of the startup process of RocksDB, it has to extract the C library before it can be used. The location to extract the C library is determined by the `java.io.tmpdir` system property or `ROCKSDB_SHAREDLIB_DIR` environment variable.

If this directory is not writable, then the user will see an error like `Could not initialize class org.rocksdb.Options` when running a query which needs a state store. 

Here is an example failure mode:

```
$ ls | grep javatmp
drwxr-xr-x    2 apurva  staff     64 May 22 12:12 javatmp
$ KSQL_OPTS="-Djava.io.tmpdir=/Users/apurva/javatmp/" ./bin/ksql-server-start etc/ksql/ksql-server.properties
$ ./bin/ksql
... Welcome message ...
ksql> CREATE TABLE users_original (registertime BIGINT, gender VARCHAR, regionid VARCHAR, userid VARCHAR) WITH (kafka_topic='users', value_format='JSON', key = 'userid');

 Message
---------------
 Table created
---------------
ksql> select * from users_original;
Could not initialize class org.rocksdb.Options
Query terminated
ksql>
$ less ksql-server.log
[2018-05-22 12:15:32,702] ERROR Exception occurred while writing to connection stream:  (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:105)
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.Options
        at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:116)
        at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:167)
        at 
```

If the user runs into this, the best solution is to set `java.io.tmpdir` to a directory which is writable by all users.

In the above example executing `chmod +w javatmp` fixes the issue.

**Comment by surajkb74** [comment] 2018-05-23 23:14
After following your step (KSQL_OPTS="-Djava.io.tmpdir=/Users/apurva/javatmp/"), no more error.. When I query the table(in my example user_original), nothing happens.. looks like waiting for some input..
if I change the table to stream it works

CREATE TABLE users_original (registertime bigint, gender varchar, regionid varchar, userid varchar) WITH (kafka_topic='users', value_format='JSON', key = 'userid');

CREATE STREAM users_original_test (registertime bigint, gender varchar, regionid varchar, userid varchar) WITH (kafka_topic='users', value_format='JSON', key = 'userid')

**from ksql log.**

[2018-05-23 15:53:44,812] INFO Build logical plan for **select * from  users_original;.** (io.confluent.ksql.QueryEngine:101)
[2018-05-23 15:53:44,813] INFO KsqlConfig values:
        ksql.persistent.prefix = query_
        ksql.schema.registry.url = http://localhost:8081
        ksql.service.id = default_
        ksql.sink.partitions = 4
        ksql.sink.replicas = 1
        ksql.sink.window.change.log.additional.retention = 1000000
        ksql.statestore.suffix = _ksql_statestore
        ksql.timestamp.column.index = null
        ksql.transient.prefix = transient_
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
 (io.confluent.ksql.util.KsqlConfig:279)
[2018-05-23 15:53:44,857] INFO Streaming query 'select * from  users_original;' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:89)
[2018-05-23 15:54:11,865] WARN Query terminated due to exception:org.eclipse.jetty.io.EofException (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:99)
[2018-05-23 15:54:11,947] WARN Could not clean up the schema registry for query: _confluent-ksql-default_transient_7944794408484207284_1527116024821 (io.confluent.ksql.util.QueryMetadata:136)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)

**log for select * from user_stream;.** 

[2018-05-23 15:54:17,081] INFO Build logical plan for select * from user_stream;. (io.confluent.ksql.QueryEngine:101)
[2018-05-23 15:54:17,082] INFO KsqlConfig values:
        ksql.persistent.prefix = query_
        ksql.schema.registry.url = http://localhost:8081
        ksql.service.id = default_
        ksql.sink.partitions = 4
        ksql.sink.replicas = 1
        ksql.sink.window.change.log.additional.retention = 1000000
        ksql.statestore.suffix = _ksql_statestore
        ksql.timestamp.column.index = null
        ksql.transient.prefix = transient_
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
 (io.confluent.ksql.util.KsqlConfig:279)
[2018-05-23 15:54:17,142] INFO Streaming query 'select * from user_stream;' (io.confluent.ksql.rest.server.resources.streaming.StreamedQueryResource:89)
[2018-05-23 15:54:22,145] WARN Query terminated due to exception:org.eclipse.jetty.io.EofException (io.confluent.ksql.rest.server.resources.streaming.QueryStreamWriter:99)
[2018-05-23 15:54:22,191] WARN Could not clean up the schema registry for query: _confluent-ksql-default_transient_6119937906852273751_1527116057091 (io.confluent.ksql.util.QueryMetadata:136)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)

**Comment by parth22594** [comment] 2018-12-10 10:34
After follow this step. Got following error.


java.lang.UnsatisfiedLinkError: /tmp/tmpjava/librocksdbjni1513379826889322410.so: libstdc++.so.6: cannot open shared object file: No such file or directory
Caused by: /tmp/tmpjava/librocksdbjni1513379826889322410.so: libstdc++.so.6: cannot open shared object file: No such file or directory
Query terminated

**Comment by agavra** [comment] 2019-10-16 22:17
I think we should provide a more actionable error message by checking the permissions on the directory eagerly. Adding the fix-it-week label to this to make sure it gets tracked.

**Comment by ntsh999** [comment] 2020-07-13 08:00
I also received the same error message as mentioned in the org post. After applying the suggested fix chmod +w tmp and chmod +w /var/tmp on my temp directories I get the following error message. I am using confluent platform v 5.4.1 and OS is Ubuntu 18 with CIS hardened image from Azure. 

````
 java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.DBOptions
        at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:133)
        at org.apache.kafka.streams.state.internals.KeyValueSegment.openDB(KeyValueSegment.java:49)
        at org.apache.kafka.streams.state.internals.KeyValueSegments.getOrCreateSegment(KeyValueSegments.java:50)
        at org.apache.kafka.streams.state.internals.KeyValueSegments.getOrCreateSegment(KeyValueSegments.java:25)
        at org.apache.kafka.streams.state.internals.AbstractSegments.getOrCreateSegmentIfLive(AbstractSegments.java:84)
        at org.apache.kafka.streams.state.internals.AbstractRocksDBSegmentedBytesStore.put(AbstractRocksDBSegmentedBytesStore.java:148)
        at org.apache.kafka.streams.state.internals.RocksDBWindowStore.put(RocksDBWindowStore.java:61)
        at org.apache.kafka.streams.state.internals.RocksDBWindowStore.put(RocksDBWindowStore.java:27)
        at org.apache.kafka.streams.state.internals.ChangeLoggingWindowBytesStore.put(ChangeLoggingWindowBytesStore.java:111)
        at org.apache.kafka.streams.state.internals.ChangeLoggingWindowBytesStore.put(ChangeLoggingWindowBytesStore.java:34)
        at org.apache.kafka.streams.state.internals.MeteredWindowStore.put(MeteredWindowStore.java:186)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl$WindowStoreReadWriteDecorator.put(ProcessorContextImpl.java:535)
        at org.apache.kafka.streams.kstream.internals.KStreamJoinWindow$KStreamJoinWindowProcessor.process(KStreamJoinWindow.java:57)
        at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:118)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
        at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
        at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87)
        at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:432)
        at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:474)
        at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:536)
        at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:792)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:698)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:671)

````

**Comment by JimGalasyn** [comment] 2021-01-26 17:07
Fixed in https://github.com/confluentinc/ksql/pull/6897.

**Closed by JimGalasyn** 2021-01-26 17:07 UTC
Labels: documentation, fix-it-week
