### ISSUE TITLE
KSQLDB :: Create substream from existing stream for MAP attributes

### ISSUE THREAD

**Issue by mrunmayee003** [confluentinc/ksql#6833] opened 2021-01-05 12:44 UTC
I am currently new in this field and working on KSQLDB. I wanted to create sub stream from JSON data which contains map attributes inside it.

My JSON formatted data coming in existing topic.

  ```
  ksql> print Topic_name;
    Key format: ¯\_(ツ)_/¯ - no data processed
    Value format: JSON_SR or KAFKA_STRING
    rowtime: 2021/01/04 06:46:26.337 Z, key: <null>, value: {"fields":{"field1":"1","field2":"0","field3":"1","field4":"2"},"name":"test","tags":{"tag1":"abc","tag2":"def","tag3":"ghi","tag4":"xyz","tag5":"jkl"},"timestamp":34018905608}

```

Stream created for above JSON using existing topic

 `   ksql>create stream test(fields map<string,string>, name varchar, tags map<string,string>, timestamp bigint) with(kafka_topic='Topic_name',value_format='JSON_SR');`

I want to create sub stream from above stream using where clause on one of the fields and the data coming in MAP attributes is dynamic. Currently I am using below query to create substream.

```
ksql>create stream test_substream as select * from test where TAGS['tag1']='abc' emit changes;   
ksql> describe test_substream;

    Name: TEST_SUBSTREAM
     Field      Type
    
     FIELDS       MAP<STRING, VARCHAR(STRING)>
     NAME         VARCHAR(STRING)
     TAGS         MAP<STRING, VARCHAR(STRING)>
     TIMESTAMP    BIGINT
```

But when I am describing substream I could see data of all the fields are as similar as the original stream but when I am checking Topic (TEST_SUBSTREAM topic) associated with substream, it is showing ARRAY<VARCHAR> instead of MAP<VARCHAR, VARCHAR> datatype attributes. Hence select query is not returning any data for substream however I could see expected data is present in TEST_SUBSTREAM topic with array format. 

 
   The topic TEST_SUBSTREAM structure is as follows,
    Value column(s)
    Column name			 Column type
    
    FIELDS 				ARRAY<VARCHAR>
    
    NAME				VARCHAR
    
    TAGS				ARRAY<VARCHAR>
    
    TIMESTAMP			BIGINT

I am expecting data to be present in substream test_substream which is received as map attribute in original stream test.
Please help..

**Comment by agavra** [comment] 2021-01-29 23:25
Thanks for reporting this @mrunmayee003 - I was not able to reproduce this on my local master build of ksqlDB, so I suspect one of a few things might be going on. First, can you give us the version that you're using? Second, can you let me know what the schema of the event in Schema Registry is? It might have to do with the fact that maps are often treated as arrays of entries in schema registry. 

FWIW, if you are using schema registry, it's better to not supply the schema as part of the create statement:
```sql
create stream test with(kafka_topic='Topic_name',value_format='JSON_SR');
```
This will infer the correct data for schema registry.

---


```
ksql> create stream test(fields map<string,string>, name varchar, tags map<string,string>, timestamp bigint) with(kafka_topic='Topic_name',value_format='JSON_SR', partitions=1);

 Message
----------------
 Stream created
----------------
ksql> create stream test_substream as select * from test where TAGS['tag1']='abc' emit changes;

 Message
---------------------------------------------
 Created query with ID CSAS_TEST_SUBSTREAM_9
---------------------------------------------
ksql> describe test_substream;

Name                 : TEST_SUBSTREAM
 Field     | Type
------------------------------------------
 FIELDS    | MAP<STRING, VARCHAR(STRING)>
 NAME      | VARCHAR(STRING)
 TAGS      | MAP<STRING, VARCHAR(STRING)>
 TIMESTAMP | BIGINT
------------------------------------------
For runtime statistics and query details run: DESCRIBE EXTENDED <Stream,Table>;
```

**Comment by mrunmayee003** [comment] 2021-02-02 06:10
I had tried creating a stream with the same commands but data was not getting store in substream. So I tried creating substream with value_format AVRO. Now it is working.

`ksqldb>create stream test_substream  with(kafka_topic='test_substream ', value_format='AVRO') as select * from test where TAGS['tag1']='abc' emit changes;`

**Comment by agavra** [comment] 2021-02-02 16:13
Thanks for circling back @mrunmayee003 - I'm glad it's working. Feel free to re-open if I misunderstood, but I'm closing this out for now.

**Closed by agavra** 2021-02-02 16:13 UTC
Labels: question, streaming-engine
