### ISSUE TITLE
LATEST_BY_OFFSET and EARLIEST_BY_OFFSET do not support Decimal

### ISSUE THREAD

**Issue by vcrfxia** [confluentinc/ksql#5657] opened 2020-06-19 17:33 UTC
The current implementations of the `LATEST_BY_OFFSET` and `EARLIEST_BY_OFFSET` built-in aggregation functions do not support Decimal data types. It'd be useful for them to do so.

**Comment by big-andy-coates** [comment] 2020-06-19 17:43
Closing as a duplicate of https://github.com/confluentinc/ksql/issues/5437

**Closed by big-andy-coates** 2020-06-19 17:43 UTC
Labels: enhancement

**Comment by aabrams** [comment] 2021-10-13 09:05
Perhaps support for DECIMAL could be added quickly, with the other more complicated data structures delayed for UDAF improvements?
