### ISSUE TITLE
Cannot use WINDOWSTART system column in a windowed aggregation if it includes a stream-table join

### ISSUE THREAD

**Issue by rmoff** [confluentinc/ksql#7369] opened 2021-04-12 13:50 UTC
**Describe the bug**

Cannot use WINDOWSTART system column in a windowed aggregation if it includes a stream-table join. If the join is removed the system column can be used. 

**To Reproduce**

ksqlDB 0.15 (ccloud env `lksqlc-vz85j`)

This works: 

```
SELECT TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss','Europe/London') AS TS, 
       T.FULLDOCUMENT->PROD_ID, COUNT(*) AS TXN_PER_HOUR
FROM  TRANSACTIONS T  
WINDOW TUMBLING (SIZE 1 HOUR)
GROUP BY T.FULLDOCUMENT->PROD_ID
EMIT CHANGES;
```

This fails

```
SELECT TIMESTAMPTOSTRING(WINDOWSTART,'yyyy-MM-dd HH:mm:ss','Europe/London') AS TS, 
       T.FULLDOCUMENT->PROD_ID, COUNT(*) AS TXN_PER_HOUR , I.TXN_HOUR AS EXPECTED_TXN_PER_HOUR
FROM  TRANSACTIONS T  
LEFT JOIN  INVENTORY I ON T.FULLDOCUMENT->PROD_ID = I.PRODUCT_ID 
WINDOW TUMBLING (SIZE 1 HOUR)
GROUP BY T.FULLDOCUMENT->PROD_ID, I.TXN_HOUR
EMIT CHANGES;
```

Error: `Line: 1, Col: 26: SELECT column 'WINDOWSTART' cannot be resolved. `

**Comment by vcrfxia** [comment] 2021-04-20 21:42
This is a duplicate of https://github.com/confluentinc/ksql/issues/5931. Tracking there instead.

**Closed by vcrfxia** 2021-04-20 21:42 UTC
Labels: P1, bug, streaming-engine, user-experience
