### ISSUE TITLE
Static value in SELECT + GROUP BY

### ISSUE THREAD

**Issue by mbrancato** [confluentinc/ksql#1325] opened 2018-05-18 16:44 UTC
Is there support in KSQL for static values in a SELECT statement? This is usually implemented as either:
`SELECT 'value' AS field_name` or `SELECT field_name='value'`

KSQL appears to support the former version for some operations. In the latter version, KSQL appears to do a boolean comparison. In prior versions, say 0.2, KSQL supported a query that looked like:

```
SELECT 'value' AS field_name
...
WINDOW TUMBLING (SIZE 1 MINUTE)
GROUP BY field_name
...
```

In the current version (4.1.1) it fails with the error:

> Couldn't find field with name=STREAM_NAME.FIELD_NAME in schema. fields=[org.apache.kafka.connect.data.Field@40d89c9, org.apache.kafka.connect.data.Field@945f0188]

In the 5.0.0 beta version, it fails with the error:
> name is null

To achieve this, a phantom field / column must be defined in the stream.

Is there any way to achieve these static assignments? There may be opportunity to do this with a join, but I haven't explored that yet since the data is so small.

**Comment by big-andy-coates** [comment] 2018-10-22 14:19
KSQL doesn't currently support `GROUP BY` clauses that use UDFs. Unfortunately, struct field dereferencing is implemented in terms of UDFs under the hood and hence does not work. I'm working on a fix.

Partial duplicate of #1849

**Closed** 2018-10-30 01:32 UTC
