### ISSUE TITLE
Negative DOUBLE literals are not being parsed correctly

### ISSUE THREAD

**Issue by derekjn** [confluentinc/ksql#4682] opened 2020-03-02 20:26 UTC
**Describe the bug**
Negative `DOUBLE` literals are not being parsed correctly.

**To Reproduce**
1. Using ksqlDB version `0.7.1`.
2. CLI was built from source on the `5.3.x` branch, commit hash `cf9c6b9b621adb250c45c294571bcb59002a3d5f`.
3. Create the following stream (from [quickstart](https://ksqldb.io/quickstart.html)):

```sql
CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE)
  WITH (kafka_topic='locations', key='profileId', value_format='json', partitions=1);
```

4. Run the following `INSERT` statement:
```sql
INSERT INTO riderLocations (profileId, latitude, longitude) VALUES ('c2309eec', 37.7877, -122.4205);
```

**Expected behavior**
The `INSERT` should succeed.

**Actual behaviour**
This error is thrown:
```
line 1:90: extraneous input '-' expecting {'NULL', 'TRUE', 'FALSE', STRING, INTEGER_VALUE, DECIMAL_VALUE}
Statement: INSERT INTO riderLocations (profileId, latitude, longitude) VALUES ('c2309eec', 37.7877, -122.4205);
Caused by: line 1:90: extraneous input '-' expecting {'NULL', 'TRUE', 'FALSE',
	STRING, INTEGER_VALUE, DECIMAL_VALUE}
```
**Additional context**
The `INSERT` works as expected if a non-negative `longitude` value is used.

**Comment by derekjn** [comment] 2020-03-02 20:41
I don't encounter this issue when using the latest CLI image (`confluentinc/ksqldb-cli:0.7.1`). I first got this error when using a local build of the CLI, so there may be no issue here.

**Comment by big-andy-coates** [comment] 2020-06-03 10:05
Duplicate of https://github.com/confluentinc/ksql/issues/3610 (which is fixed)

**Closed by big-andy-coates** 2020-06-03 10:05 UTC
