### ISSUE TITLE
KSQL cli does not recognize long-form optional args

### ISSUE THREAD

**Issue by rodesai** [confluentinc/ksql#4890] opened 2020-03-25 06:46 UTC
**Describe the bug**
KSQL cli does not recognize long-form optional args (e.g. `--username` vs `--u`).

**Actual behaviour**
```
$ bin/ksql --username foo --password bar http://localhost:8080
At most 1 arguments may be specified but 3 were found
See the -h or --help flags for usage information
```

**Expected behavior**
```
$ bin/ksql -u foo -p bar http://localhost:8080

                  ===========================================
                  =       _              _ ____  ____       =
                  =      | | _____  __ _| |  _ \| __ )      =
                  =      | |/ / __|/ _` | | | | |  _ \      =
                  =      |   <\__ \ (_| | | |_| | |_) |     =
                  =      |_|\_\___/\__, |_|____/|____/      =
                  =                   |_|                   =
                  =  Event Streaming Database purpose-built =
                  =        for stream processing apps       =
                  ===========================================

Copyright 2017-2019 Confluent Inc.
....
```

**Comment by brianstrauch** [comment] 2020-04-06 04:03
I believe the error here is that the long-form version of `-u` is `--user` and not `--username`. Maybe this should be changed, since `--username` is more idiomatic.

**Comment by spena** [comment] 2020-04-27 17:33
The right long command is:
```
--user <userName>, -u <userName>
            If your KSQL server is configured for authentication, then provide
            your user name here. The password must be specified separately with
            the -p/--password flag
```

**Comment by spena** [comment] 2020-04-27 17:37
I will close this ticket as not a bug.

@brianstrauch I don't know what a good option would be. I looked at a couple of DBs for examples. Mysql users `--user` and Mongo uses `--username`.

**Closed by spena** 2020-04-27 17:37 UTC
Labels: bug
