### ISSUE TITLE
Support the -> operator with specifying the TIMESTAMP field

### ISSUE THREAD

**Issue by JamesHunter9** [confluentinc/ksql#4518] opened 2020-02-11 22:16 UTC
**Is your feature request related to a problem? Please describe.**

The TIMESTAMP feature is very useful since our metrics do contain the time the metrics are actually collected.  The collection time can be in the past when the data is collected and then later bulked loaded into the product. However, the time field in our schema is in a substructure (a record) of the schema.  The TIMESTAMP clause would not accept the -> operator when specifying the TIMESTAMP property (e.g., TIMESTAMP='METRICSOURCE->TIME').

**Describe the solution you'd like**
Support dereferencing a structure in the TIMESTAMP clause.

**Describe alternatives you've considered**
I had to modify our schema, adding a time field in the top structure.  I then had to modify one of the upstream services to duplicate the time information from the substructure to the top structure.

**Comment by MichaelDrogalis** [comment] 2021-11-16 21:39
Closing as duplicate of https://github.com/confluentinc/ksql/issues/2188

**Closed by MichaelDrogalis** 2021-11-16 21:39 UTC
Labels: enhancement
