### ISSUE TITLE
Unable to skip basic authentication for specified paths in ksqldb-server

### ISSUE THREAD

**Issue by mpistrang** [confluentinc/ksql#9206] opened 2022-06-16 13:43 UTC
**Describe the bug**
Use of the config option `authentication.skip.paths` does not actually allow the specified paths to skip basic authentication for ksqldb-server.

**To Reproduce**
Steps to reproduce the behavior, include:
1. Using this [fork](https://github.com/mpistrang/cp-all-in-one/tree/ksqldb-server-basic-auth-example/cp-all-in-one-community) of [confluentinc/cp-all-in-one](https://github.com/confluentinc/cp-all-in-one)
2.  In the `cp-all-in-one-community` directory un `docker-compose -f docker-compose.yml -f docker-compose.ksqldb-server-basic-auth.yml up -d`
3. Note that in the `docker-compose.ksqldb-server-basic-auth.yml` override file basic auth is configured for ksqldb-server along with `/healthcheck` defined in the `authentication.skip.paths` option.

**Expected behavior**
The command `curl localhost:8088/healthcheck` with no basic auth provided returns the health check information

**Actual behavior**
The command `curl localhost:8088/healthcheck` returns an HTTP 401

**Additional context**
I expect there is additional configuration that I am missing here, but so far I have not found what it could be.

**Comment by suhas-satish** [comment] 2022-06-17 19:09
@alapidas , this seems to be control plane stuff, can you take this?

**Comment by agavra** [comment] 2022-06-24 18:52
I was able to confirm the bug, working on a patch now.

**Comment by agavra** [comment] 2022-08-09 18:44
yes, this should be part of the 0.28 release :)

**Comment by nmckimm** [comment] 2022-09-20 11:23
Has anyone managed to get this working on version 0.28.2? The change has been merged but I still cant skip `/heartbeat` or `/lag` using `authentication.skip.paths`.

**Comment by lucasprograms** [comment] 2022-10-08 18:07
Not working for me either - trying to use the same skip paths configuration as seen here:
https://github.com/mpistrang/cp-all-in-one/blob/ksqldb-server-basic-auth-example/cp-all-in-one-community/docker-compose.ksqldb-server-basic-auth.yml#L11

**Comment by lucasprograms** [comment] 2022-10-17 14:02
hey @agavra , possible to reopen this?

**Comment by agavra** [comment] 2022-10-17 16:32
yeah I'll reopen this - cc @suhas-satish @alapidas

**Comment by lucasbru** [comment] 2022-10-25 15:02
I was able to reproduce the bug on master, and yes, the parameter is completely ignored for basic auth. I will implement a fix.

**Closed** 2022-11-02 11:13 UTC
Labels: bug, P0, streaming-engine
