### ISSUE TITLE
Provide first-class support for Avro-based message keys

### ISSUE THREAD

**Issue by robinroos** [confluentinc/ksql#3986] opened 2019-11-27 10:50 UTC
KSQL does not work fluently if the message key is defined with Avro.

Despite starting with Avro-based keys, which in my mind is the best design approach, I quickly had to revert to using String keys.

This is probably an Epic which would encompass several features:

1. make Group By return a stream with an Avro Key (if the input is Avro).
2. make it easy to SELECT STRUCT<...> FROM in order to re-partition with an Avro-based key (if the input is Avro)
3. others...

**Comment by apurvam** [comment] 2019-12-10 21:47
see #3533

**Comment by apurvam** [comment] 2019-12-10 21:48
closing as a duplicate of #3533

**Closed by apurvam** 2019-12-10 21:48 UTC
Labels: enhancement
