### ISSUE TITLE
TIMESTAMP_FORMAT does not respect '' escaping

### ISSUE THREAD

**Issue by singpolyma-shopify** [confluentinc/ksql#1439] opened 2018-06-14 20:35 UTC
`CREATE STREAM foo (thing_id BIGINT, event_timestamp VARCHAR) WITH (VALUE_FORMAT='JSON', KAFKA_TOPIC='triggers', TIMESTAMP='event_timestamp', TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ssX');`

The above appears to work.  But trying to select from the streams results in the following:

`Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd''T''HH:mm:ssX Unknown pattern letter: T`

Version: 5.0.0-beta30

**Comment by apurvam** [comment] 2018-06-15 00:45
Try to use double quotes, like so `‘yyyy-MM-dd’‘T’‘HH:mm:ssX’`. See: https://docs.confluent.io/5.0.0-beta30/ksql/docs/syntax-reference.html#create-stream

**Comment by psycotica0-shopify** [comment] 2018-06-15 15:07
Is that not the same as what he posted?

**Comment by apurvam** [comment] 2018-06-15 18:52
Not sure of the formatting, but it looks like there are two single quotes `''` in @singpolyma-shopify's snippet, but a single double quote `"` in mine.

**Comment by psycotica0-shopify** [comment] 2018-06-15 19:33
Oh. The docs definitely have two `'` (single quotes), and in your message above you have two `'` (single quotes).
Either way, `"` doesn't appear to work either.
I get:
```
Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd"T"HH:mm:ssX Unknown pattern letter: T
```

**Comment by rmoff** [comment] 2018-08-09 11:52
I am hitting this error too, on 5.0.0. 
Tried two single quotes `''`, double quote `"`, and double backtick ` `` `

    Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd''T''HH:mm:ssX Unknown pattern letter: T
    Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd"T"HH:mm:ssX Unknown pattern letter: T
    Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: T for configuration Invalid date format: yyyy-MM-dd``T``HH:mm:ssX Unknown pattern letter: T

**Comment by rmoff** [comment] 2018-08-09 11:59
It would be nice to be able to use the pre-defined formatters? e.g. `ISO_INSTANT`. Currently thows an error: 

    Caused by: Invalid value java.lang.IllegalArgumentException: Unknown pattern letter: I for configuration Invalid date format: ISO_INSTANT Unknown pattern letter: I

**Comment by rmoff** [comment] 2018-08-09 12:01
Seems CSAS handles the datetime parsing differently from simply `SELECT`, which works fine with double single quotes: 

    SELECT TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd''T''HH:mm:ssX')  FROM ENVIRONMENT_DATA;
    2018-08-08T17:02:13Z

**Comment by foresightyj** [comment] 2018-08-15 06:15
Hit the same problem here. Still no solutions?

**Comment by apurvam** [comment] 2018-08-15 23:45
I've marked this as a bug.

**Comment by foresightyj** [comment] 2018-08-16 00:58
Appreciated the help. Meanwhile, I will use unix timestamp for all my kafka topics.

**Comment by uurl** [comment] 2018-08-24 14:32
@apurvam @rmoff Fixed

**Closed** 2018-09-07 09:39 UTC
Labels: bug, good first issue
