### ISSUE TITLE
Spotbugs raising issue on java11, not on java8

### ISSUE THREAD

**Issue by andrewegel** [confluentinc/ksql#6596] opened 2020-11-10 20:06 UTC
**Describe the bug**
I was experimenting with build some of Confluent's projects with java11, and I discovered that on `master`, building with java11, a spot-bugs pops up:

```
% mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 11.0.9, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
...
% mvn -D skipTests install
...
[ERROR] Redundant nullcheck of resourceAsStream, which is known to be non-null in io.confluent.ksql.util.AppInfo.<static initializer for AppInfo>() [io.confluent.ksql.util.AppInfo] Redundant null check at AppInfo.java:[line 43] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
```

This doesn't happen on java8 - its a pretty simple reproduction case.

**To Reproduce**
Steps to reproduce the behavior, include:
1. The version of KSQL. 

Check out `master` branch. Try building project:

```
mvn -D skipTests install
```

Platform: MacOS 10.15.7, adoptopenjdk-11

2. Sample source data.

N/A

3. Any SQL statements you ran

N/A

**Expected behavior**
The project builds & doesn't raise a spot-bugs issue.

**Actual behaviour**
See above

**Additional context**
I acknowledge this will probably be a low priority. You can find me on slack if you need additional context/details.

**Comment by brianstrauch** [comment] 2021-01-04 04:53
Just ran into this issue as well, after building the project for the first time. It looks like this was caused by a combination of https://github.com/confluentinc/ksql/pull/6509 and https://sourceforge.net/p/findbugs/bugs/1169/.

This could be fixed by:
1. Updating SpotBugs
2. Excluding the rule `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE` in https://github.com/confluentinc/ksql/blob/master/findbugs/findbugs-exclude.xml
3. Reverting the changes from https://github.com/confluentinc/ksql/pull/6509

Not sure what the best route to take is, but hope this helps!

**Comment by mjsax** [comment] 2022-02-15 19:04
We should actually also ensure that we support Java17.

**Closed** 2022-03-22 18:20 UTC
Labels: bug, blocker, fix-it-week, query-engine, round-robin
