### ISSUE TITLE
Add support for KS suppress functionality

### ISSUE THREAD

**Issue by big-andy-coates** [confluentinc/ksql#3560] opened 2019-10-11 21:32 UTC
This should likely fit in to the new syntax we have for controlling result materialization, i.e. the `EMIT CHANGES`.  We've discussed `EMIT FINAL` for a final value for push queries and `YIELD FINAL` for pull queries.  However, we need to look at what the suppress functionality has to offer and how is best exposed in KSQL.

**Comment by big-andy-coates** [comment] 2019-10-11 21:34
see https://github.com/confluentinc/ksql/issues/3560

**Comment by big-andy-coates** [comment] 2019-10-16 10:40
see https://stackoverflow.com/questions/58358784/ksql-query-returning-unexpected-values-in-simple-aggregation

**Comment by agavra** [comment] 2019-11-05 17:19
opened #3754 to address this

**Comment by agavra** [comment] 2020-06-23 20:20
close as duplicate of #1030

**Closed by agavra** 2020-06-23 20:20 UTC
Labels: engine, enhancement
