### ISSUE TITLE
Corrupted Time Stamps between streams

### ISSUE THREAD

**Issue by andyrat33** [confluentinc/ksql#819] opened 2018-02-28 09:21 UTC
I am getting some very strange and inexplicable corruption of a timestamp field. Here is what I am seeing:
`select TIMESTAMPTOSTRING(first_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), first_switched, TIMESTAMPTOSTRING(last_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), last_switched, version from netflow_formatted  where first_switched < 1 or last_switched < 1 limit 10;`
To get 10 take 5 minutes
`0999-02-28 09:00:08.999Z | -30636284391001 | 2018-02-28 09:00:08.999Z | 1519808408999 | 9 
 0011-10-27 09:00:08.999Z | -61794370791001 | 2018-02-28 09:16:59.999Z | 1519809419999 | 9 
 0002-03-28 09:01:00.999Z | -62096770739001 | 0001-02-03 09:01:00.999Z | -62132885939001 | 9 
 0999-02-28 09:02:00.999Z | -30636284279001 | 2018-02-28 09:02:00.999Z | 1519808520999 | 9 
 0579-02-28 09:01:53.999Z | -43890476286001 | 2018-02-28 09:01:53.999Z | 1519808513999 | 9 
 0005-07-26 09:02:12.999Z | -61991708267001 | 2018-02-28 09:02:12.999Z | 1519808532999 | 9 
 2020-04-24 10:02:26.999+01 | 1587718946999 | 0002-02-28 09:02:26.999Z | -62099189853001 | 9 
 2018-02-04 09:18:39.999Z | 1517735919999 | 0098-04-25 09:02:48.999Z | -59064821831001 | 9 
 0002-02-28 09:03:09.999Z | -62099189810001 | 2018-02-28 09:03:09.999Z | 1519808589999 | 9 
 0003-05-29 01:39:09.999Z | -62059904450001 | 2018-02-28 09:03:09.999Z | 1519808589999 | 9 `
If I change the query to get only correct timestamps

`select TIMESTAMPTOSTRING(first_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), first_switched, TIMESTAMPTOSTRING(last_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), last_switched, version from netflow_formatted  where first_switched > 1 AND last_switched > 1 limit 10;`
I get the results instantly, proving the errors are in there but quite rare.
`2018-02-28 09:05:40.999Z | 1519808740999 | 2018-02-28 09:05:40.999Z | 1519808740999 | 9 
 2018-02-28 09:05:29.999Z | 1519808729999 | 2018-02-28 09:05:29.999Z | 1519808729999 | 9 
 2018-02-28 09:05:29.999Z | 1519808729999 | 2018-02-28 09:05:29.999Z | 1519808729999 | 9 
 2018-02-28 09:05:22.999Z | 1519808722999 | 2018-02-28 09:05:33.999Z | 1519808733999 | 9 
 2018-02-28 09:05:33.999Z | 1519808733999 | 2018-02-28 09:05:33.999Z | 1519808733999 | 9 
 2018-02-28 09:05:40.999Z | 1519808740999 | 2018-02-28 09:05:40.999Z | 1519808740999 | 9 
 2018-02-28 09:05:34.999Z | 1519808734999 | 2018-02-28 09:05:34.999Z | 1519808734999 | 9 
 2018-02-28 09:05:34.999Z | 1519808734999 | 2018-02-28 09:05:34.999Z | 1519808734999 | 9 
 2018-02-28 09:05:30.999Z | 1519808730999 | 2018-02-28 09:38:38.999Z | 1519810718999 | 9 
 2018-02-28 09:05:29.999Z | 1519808729999 | 2018-02-28 09:05:29.999Z | 1519808729999 | 9 `

The get to Netflow_Formatted stream I start with:
`create stream netflow (netflow varchar, host varchar) with (kafka_topic='netflow',value_format='JSON');`

That stream reads the netflow topic.

The next stream flattens the JSON
` select extractjsonfield(netflow,'$.output_snmp') as output_snmp, extractjsonfield(netflow,'$.dst_as') as dst_as, extractjsonfield(netflow,'$.dst_mask') as dst_mask, extractjsonfield(netflow,'$.in_pkts') as in_pkts, extractjsonfield(netflow,'$.ipv4_dst_addr') as ipv4_dst_addr, extractjsonfield(netflow,'$.src_tos') as src_tos, extractjsonfield(netflow,'$.first_switched') as first_switched, extractjsonfield(netflow,'$.flowset_id') as flowset_id, extractjsonfield(netflow,'$.l4_src_port') as l4_src_port, extractjsonfield(netflow,'$.ipv4_next_hop') as ipv4_next_hop, extractjsonfield(netflow,'$.src_mask') as src_mask, extractjsonfield(netflow,'$.version') as version, extractjsonfield(netflow,'$.flow_seq_num') as flow_seq_num, extractjsonfield(netflow,'$.ipv4_src_addr') as ipv4_src_addr, extractjsonfield(netflow,'$.in_bytes') as in_bytes, extractjsonfield(netflow,'$.protocol') as protocol, extractjsonfield(netflow,'$.last_switched') as last_switched, extractjsonfield(netflow,'$.input_snmp') as input_snmp, extractjsonfield(netflow,'$.tcp_flags') as tcp_flags, extractjsonfield(netflow,'$.flow_sampler_id') as flow_sampler_id, extractjsonfield(netflow,'$.l4_dst_port') as l4_dst_port, extractjsonfield(netflow,'$.direction') as direction, extractjsonfield(netflow,'$.src_as') as src_as from netflow;`
At this stage I have the fields but they are all of VARCHAR
` describe netflow_flattened;

 Field           | Type
-----------------------------------
 ROWTIME         | BIGINT
 ROWKEY          | VARCHAR(STRING)
 OUTPUT_SNMP     | VARCHAR(STRING)
 DST_AS          | VARCHAR(STRING)
 DST_MASK        | VARCHAR(STRING)
 IN_PKTS         | VARCHAR(STRING)
 IPV4_DST_ADDR   | VARCHAR(STRING)
 SRC_TOS         | VARCHAR(STRING)
 FIRST_SWITCHED  | VARCHAR(STRING)
 FLOWSET_ID      | VARCHAR(STRING)
 L4_SRC_PORT     | VARCHAR(STRING)
 IPV4_NEXT_HOP   | VARCHAR(STRING)
 SRC_MASK        | VARCHAR(STRING)
 VERSION         | VARCHAR(STRING)
 FLOW_SEQ_NUM    | VARCHAR(STRING)
 IPV4_SRC_ADDR   | VARCHAR(STRING)
 IN_BYTES        | VARCHAR(STRING)
 PROTOCOL        | VARCHAR(STRING)
 LAST_SWITCHED   | VARCHAR(STRING)
 INPUT_SNMP      | VARCHAR(STRING)
 TCP_FLAGS       | VARCHAR(STRING)
 FLOW_SAMPLER_ID | VARCHAR(STRING)
 L4_DST_PORT     | VARCHAR(STRING)
 DIRECTION       | VARCHAR(STRING)
 SRC_AS          | VARCHAR(STRING)`

The next stream fixes the data types.

`create stream netflow_fixed_final (OUTPUT_SNMP INTEGER, DST_AS INTEGER, DST_MASK VARCHAR, IN_PKTS BIGINT, IPV4_DST_ADDR VARCHAR,     SRC_TOS INTEGER, FIRST_SWITCHED VARCHAR, FLOWSET_ID INTEGER, L4_SRC_PORT INTEGER, IPV4_NEXT_HOP VARCHAR, SRC_MASK VARCHAR, VERSION INTEGER, FLOW_SEQ_NUM BIGINT, IPV4_SRC_ADDR VARCHAR, IN_BYTES BIGINT, PROTOCOL INTEGER, LAST_SWITCHED VARCHAR, INPUT_SNMP INTEGER, TCP_FLAGS  INTEGER, FLOW_SAMPLER_ID INTEGER, L4_DST_PORT INTEGER, DIRECTION VARCHAR, SRC_AS BIGINT) WITH (KAFKA_TOPIC='NETFLOW_FLATTENED', VALUE_FORMAT='JSON');`

So now I have the corrected data types

`ksql> describe netflow_fixed_final ;

 Field           | Type            
-----------------------------------
 ROWTIME         | BIGINT          
 ROWKEY          | VARCHAR(STRING) 
 OUTPUT_SNMP     | INTEGER         
 DST_AS          | INTEGER         
 DST_MASK        | VARCHAR(STRING) 
 IN_PKTS         | BIGINT          
 IPV4_DST_ADDR   | VARCHAR(STRING) 
 SRC_TOS         | INTEGER         
 FIRST_SWITCHED  | VARCHAR(STRING) 
 FLOWSET_ID      | INTEGER         
 L4_SRC_PORT     | INTEGER         
 IPV4_NEXT_HOP   | VARCHAR(STRING) 
 SRC_MASK        | VARCHAR(STRING) 
 VERSION         | INTEGER         
 FLOW_SEQ_NUM    | BIGINT          
 IPV4_SRC_ADDR   | VARCHAR(STRING) 
 IN_BYTES        | BIGINT          
 PROTOCOL        | INTEGER         
 LAST_SWITCHED   | VARCHAR(STRING) 
 INPUT_SNMP      | INTEGER         
 TCP_FLAGS       | INTEGER         
 FLOW_SAMPLER_ID | INTEGER         
 L4_DST_PORT     | INTEGER         
 DIRECTION       | VARCHAR(STRING) 
 SRC_AS          | BIGINT          `

And finally I have to convert the date from VARCHAR to BIGINT
`create stream netflow_formatted as select output_snmp, \
     dst_as, \
     dst_mask, \
     in_pkts, \
     ipv4_dst_addr, \
     src_tos, \
     STRINGTOTIMESTAMP(first_switched, 'yyyy-MM-dd''T''HH:mm:ss.SSSX') AS  first_switched, \
     flowset_id, \
     l4_src_port, \
     ipv4_next_hop, \
     src_mask, \
     version, \
     flow_seq_num, \
     ipv4_src_addr, \
     in_bytes, \
     protocol, \
     STRINGTOTIMESTAMP(last_switched, 'yyyy-MM-dd''T''HH:mm:ss.SSSX') AS  last_switched, \
     input_snmp, \
     tcp_flags, \
     flow_sampler_id, \
     l4_dst_port, \
     direction, \
     src_as \
  from netflow_fixed_final ;`

It's all a bit long really maybe if it were possible to shorten that process down it would work reliably!
I have looked at the input topic and I have NEVER seen any incorrect time stamps. The Netflow data is generated by 2 Routers one V9 Netflow and one V5 Netflow. It is logged in Logstash before being sent back to Kafka and is also logged in SiLK as well. There is zero likelihood that data arrives corrupted.

This is all done using a kafka cluster running version 1.0 and a ksql server running 0.5 
I can make any changes as this is VM based lab running VMware vSphere 6.5. Ubuntu 14.04 LTS for all the hosts (3 Kafka, 1 KSQL). 
I am really excited about what might be possible with KSQL from a InfoSec standpoint. See my blog blog[.]infosecmatters[.]net

**Comment by rodesai** [comment] 2018-02-28 19:15
Can you preserve the original timestamps in netflow_formatted. E.G:

`create stream netflow_formatted as select output_snmp, \ dst_as, \ dst_mask, \ in_pkts, \ ipv4_dst_addr, \ src_tos, \ first_switched as first_switched_original, \ STRINGTOTIMESTAMP(first_switched, 'yyyy-MM-dd''T''HH:mm:ss.SSSX') AS first_switched, \ flowset_id, \ l4_src_port, \ ipv4_next_hop, \ src_mask, \ version, \ flow_seq_num, \ ipv4_src_addr, \ in_bytes, \ protocol, \ last_switched as last_switched_original, \ STRINGTOTIMESTAMP(last_switched, 'yyyy-MM-dd''T''HH:mm:ss.SSSX') AS last_switched, \ input_snmp, \ tcp_flags, \ flow_sampler_id, \ l4_dst_port, \ direction, \ src_as \ from netflow_fixed_final ;
`

It would also be really helpful if you could provide a dump from your source topic that corresponds to a bad row from your output.

**Comment by andyrat33** [comment] 2018-02-28 22:36
Thanks for the suggestion. Here is the output from a select:
`ksql> select TIMESTAMPTOSTRING(first_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), first_switched, first_switched_original, TIMESTAMPTOSTRING(last_switched, 'yyyy-MM-dd HH:mm:ss.SSSX'), last_switched, last_switched_original, version from netflow_formatted  where first_switched < 1 or last_switched < 1 limit 10;
2018-02-28 23:28:36.999Z | 1519860516999 | 2018-02-28T22:33:36.999Z | 0002-02-28 22:33:36.999Z | -62099141183001 | 2018-02-28T22:33:36.999Z | 9
2018-02-28 23:28:36.999Z | 1519860516999 | 2018-02-28T22:33:36.999Z | 0002-02-28 22:33:36.999Z | -62099141183001 | 2018-02-28T22:33:36.999Z | 9
0034-02-17 22:34:17.999Z | -61090248342001 | 2018-02-28T22:34:17.999Z | 2018-02-23 10:01:17.999Z | 1519380077999 | 2018-02-28T22:34:17.999Z | 9
0034-02-17 22:34:17.999Z | -61090248342001 | 2018-02-28T22:34:17.999Z | 2018-02-28 02:34:17.999Z | 1519785257999 | 2018-02-28T22:34:17.999Z | 9
2018-02-28 22:34:17.999Z | 1519857257999 | 2018-02-28T22:34:17.999Z | 0034-01-28 22:34:17.999Z | -61091976342001 | 2018-02-28T22:34:17.999Z | 9`

**Comment by rodesai** [comment] 2018-03-01 01:49
The corruption is pretty interesting. Its almost always in the year and almost always takes the value of one of the other fields in the date. I think this is a race condition caused by multiple threads sharing KUDFs. I've filed another issue for that at https://github.com/confluentinc/ksql/issues/828. We can close this once thats fixed and we'v verified you don't see this corruption anymore.

**Comment by rodesai** [comment] 2018-03-08 19:07
This linked issue is fixed in master. Can you verify that you no longer see the corruption?

**Comment by andyrat33** [comment] 2018-03-08 23:48
The first tests look good. I will try a little longer and report back

**Comment by rmoff** [comment] 2018-06-21 15:24
Hi @andyrat33 ! Did you make any more progress on this? I'd like to close it if not.

**Closed** 2018-06-21 18:54 UTC
